### PR TITLE
Remove network::Error

### PR DESCRIPTION
**Pull request by tcharding**
The `network::Error` is not used, remove it.

(This description has been changed, the thumbs up emojis were put on the previous PR description.)

### CODE REVIEW

**Review by sanket1729 — APPROVED** [review]
crACK 94680a5c96afc6a36ce02aee40ac796a5cb7bef3.

**Review by apoelstra — DISMISSED** [review]
ACK 94680a5c96afc6a36ce02aee40ac796a5cb7bef3

**Comment by apoelstra** [comment]
This approach looks good to me, but I should mention two alternatives:

* Renaming `Error::Network` to `Error::Io`
* Just returning an `io::Error` directly from all the network funcitons

**Comment by tcharding** [comment]
Lolz, terrible work by me. The error is not even used, we can just remove it. (Found by exploring your suggestions @apoelstra).

**Comment by sanket1729** [comment]
> Lolz, terrible work by me. The error is not even used, we can just remove it.

I am also to blame here :)

**Review by sanket1729 — APPROVED** [review]
reACK 99aab446c3f569959f83ab72acfc43bb9e67a095

**Review by apoelstra — APPROVED** [review]
ACK 99aab446c3f569959f83ab72acfc43bb9e67a095

lol!!

**Pull request merged**
