### PR TITLE
Improve `witness` unit tests

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for moving the `Witness` type over to `primitives` refactor and improve all the unit tests that will be moved, do not touch the ones that will stay behind.

The first five patches are from #3406, the last is just a re-name of the test function I tried to refactor in https://github.com/rust-bitcoin/rust-bitcoin/commit/ac6fe3a8815127e8c4df5fbe3f8a7241679e7c48

### CODE REVIEW

**Comment by apoelstra** [comment]
I think the CI failure is a bug that the new tests expose, though I can't tell what exactly it is.

It may be related to our use of `to_ne_bytes` and `from_ne_bytes`, given that it triggers only on the big-endian test system. But in reading the code I can't tell exactly what's wrong here.

**Comment by apoelstra** [comment]
code review ACK 42a962ee082778b781154885bd04796642e726de but we need to address this failure before we can merge this.

**Comment by tcharding** [comment]
Mad, this might be a bug. In `Encodable` for `Witness` we are use `to_ne_bytes` (via `encode_cursor`), surely this is incorrect, a consensus serialization should be able to be passed between machines without relying on the endianness of the machine, right?

**Comment by tcharding** [comment]
Related comment you made (before my time): https://github.com/rust-bitcoin/rust-bitcoin/pull/627/files#r660852407

**Comment by apoelstra** [comment]
@tcharding we don't ever use that in the consensus encoding though. The consensus encoding uses varints. AFAICT we symmetrically use `encode_cursor` and `decode_cursor`, which in turn use `to_ne_bytes` and `from_ne_bytes`. So the endianness-specificness shouldn't be visible.

**Comment by apoelstra** [comment]
I don't think the comment you linked is related to this. That was about using `swap_bytes` to go between BE and LE. This is about using `ne_bytes` to "cast" 4 bytes to a u32, in a way that shouldn't be visible to consumers.

**Comment by tcharding** [comment]
Ah you are right we are only encoding the index in the index area of `content`, no drama - my bad.

**Review by apoelstra — APPROVED** [review]
ACK 5fab6b178f594db7f609d576b7cf906757c95dda successfully ran local tests

**Comment by tcharding** [comment]
Merge please. This is holding up more `primitives` work, onwards and upwards!

**Pull request merged**
