### PR TITLE
Io improvements backport

### PR DESCRIPTION
**Pull request by Kixunil**
Backport of IO improvements. Once we add the buffer here as well we may release 0.1.3

### CODE REVIEW

**Comment by Kixunil** [comment]
They failures are unrelated but maybe I should backport the fix too?

**Comment by apoelstra** [comment]
@Kixunil yeah, that'd be great if you could. It's straightforward enough and only touches Cargo.toml files, not real code.

Pretty offensive though that they broke the stable compiler even after such a tremendous amount of pushback.

**Comment by Kixunil** [comment]
OK, I will.

> they broke the stable compiler

Not really, it's just a lint and it's our responsibility for deciding whether lints are deny or not. Since the lints are capped in dependencies no downstream users are affected. Also the lint is very useful.

**Comment by Kixunil** [comment]
Something is seriously screwed up. The CI says there's a `base58` crate with some files but I don't see it in my FS nor in the web UI.

**Comment by apoelstra** [comment]
I see it in 13ec770f10c41080c7d76a10ab667bba9b9881ba.

**Comment by tcharding** [comment]
I edited the PR description to use 0.1.3 (you had 0.1.2)

**Comment by tcharding** [comment]
I got confused, your link @apoelstra is wrong I think?

There is no version bump in this PR, or did it get force pushed away? Also the version number in the PR description is wrong. The current released version of `bitcoin-io` is already at `v0.1.2`.

**Comment by tcharding** [comment]
> Something is seriously screwed up. The CI says there's a base58 crate

And even more strange there is mention of `base58check`???

**Comment by apoelstra** [comment]
The commit ID I posted is `origin/io-0.1.x` which is the merge target for this PR.

**Comment by tcharding** [comment]
Oh, why is the tag `io-0.1.2` not the target? Said another way, why is the tag not on commit `13ec770f io: Bump version to 0.1.2` (which is the target).

**Comment by tcharding** [comment]
And strangely this PR has no `base58` directory but both `upstream/io-0.1.x` and tag `io-0.1.2` do have that directory. And on bath the `base58` crate was called `base58check` still (so I assume its unreleased at that stage because we changed the name IIRC to release it).

**Comment by tcharding** [comment]
Maybe your index was stale in some way @Kixunil ? Perhaps fetch and rebase on either the tag or the `upstream/io-0.1.x` branch).

**Comment by apoelstra** [comment]
I don't know who created the branch (it was not me) but it is pointing to the head commit for #2596 which is the "release `io`" PR. That PR was based on a version of master 8 PRs behind, so the head commit is way out of date compared to the merge commit.

The tag, which I believe I created, is pointing to the merge commit of #2039 which is one PR later, and unrelated to io. Presumably this happened because I was merging multiple things at once and didn't tag/publish `io` until another PR had snuck in.

**Comment by tcharding** [comment]
Want to delete the tag and change it to commit `5269adfc Merge rust-bitcoin/rust-bitcoin#2596: Release tracking PR: io v0.1.2` - then we can hard reset the `io-0.1.x` branch to that tag and make it the target for this PR? Or just leave the tag as it is? Is it acceptable to change tags like that?

**Comment by Kixunil** [comment]
I've created the branch so that I have something to merge against. Indeed, I've picked the base incorrectly. I'm going to reset it. I'm still confused about the `base58` thing but hopefully it'll clear up when I fix the base.

**Comment by Kixunil** [comment]
@tcharding this PR doesn't bump the version because I want the `BufReader` one to get in as well.

**Comment by apoelstra** [comment]
@tcharding the existing tag matches what's on crates.io. I am not going to change it.

**Comment by tcharding** [comment]
I'm not contradicting you, just trying to understand; by 'on crates.io' you mean the code that is released in `bitcoin-io` for that version, right? When that version was built and published only code from `bitcoin-io` is included so since the following commit only touches `bitcoin` then the tag being moved back one commit makes no difference to what was released, and only helps to reduce confusion later in time when devs checkout the tag. The reason I asked "is it acceptable" to do such a thing is because it invalidates peoples local tags and I'm not sure how 'git fetch --tag' handles that - will people end up with two tags, which is obviously worse.

Either way, its not a big deal.

**Review by tcharding — APPROVED** [review]
ACK e1ce903c66b3e3779faa38e0eea7794c67f2660c

**Comment by tcharding** [comment]
The remaining errors are lint warnings on the `bitcoin` crate. Can we merge with them as is?

**Comment by Kixunil** [comment]
I thought I fixed all of the compile issues yesterday... :angry: We should've had pinning ages ago.

**Comment by apoelstra** [comment]
> When that version was built and published only code from `bitcoin-io` is included so since the following commit only touches `bitcoin` then the tag being moved back one commit makes no difference to what was released, and only helps to reduce confusion later in time when devs checkout the tag.

Ah, I had missed that the following commit only touched non-`io` code. Ok, we could move it if we wanted.

> The reason I asked "is it acceptable" to do such a thing is because it invalidates peoples local tags and I'm not sure how 'git fetch --tag' handles that - will people end up with two tags, which is obviously worse.

No. Tags are the worst. They have only one namespace, not separated by remote, so if we updated them upstream and called `git fetch --tag` then it'd just clobber the local tag. And if they then called `git fetch other-remote --tag` it'd clobber it again unless all the users' remotes had the same tag. (I'm not sure what happens if you just call `git fetch` without specifying a remote, and it tries to fetch conflicting tags from multiple remotes. Presumably the last one to be fetched wins.)

I advise we just don't touch them if we don't need to.

**Comment by tcharding** [comment]
Is there a reason you don't mention that this is the 6 patches from #3176 @Kixunil (assuming it is)?

**Comment by Kixunil** [comment]
There is  reason: it didn't occur to me that people wouldn't find it obvious. ;)

But you've just answered my question that I haven't even got to ask: whether to edit the commits and drop your ACK or do some additional improvements in later commits. I will do them separately because it'll make history look better and cherry-picking easier.

**Comment by apoelstra** [comment]
utACK c5f026031fb2d011341a32276128fe8a0375ff54

My local CI failed with some clippy warnings -- I that's just an artifact of nightly being unpinned on this branch. But I need to head out for the day soon, and I have several other test runs queued up so I likely won't have time to do a custom one until tomorrow.

**Review by apoelstra — APPROVED** [review]
ACK c5f026031fb2d011341a32276128fe8a0375ff54 successfully ran local tests

**Comment by apoelstra** [comment]
@tcharding can you ACK the latest commit?

**Review by tcharding — APPROVED** [review]
ACK c5f026031fb2d011341a32276128fe8a0375ff54

**Pull request merged**
