### PR TITLE
Change the parameter for control block verification

### PR DESCRIPTION
**Pull request by sanket1729**
- Changes the API from TweakedPublicKey to XonlyPublicKey. I believe we
introduced TweakedPublicKey to guard against creating address API. This
is confusing because when we want to verify control block we have to
call dangerous_assume_tweak.
- This is in true in most cases that the key would be tweaked, but we only
want to guard in while creating a new address. If we want to verify
blocks, we should deal with native X-only-keys regardless of how they
were created
- Also removes the & from a 32 Copy byte as discussed elsewhere.

### CODE REVIEW

**Review by Kixunil — APPROVED** [review]
ACK af09900c2fd7ca070cfe0dd7353e65652d07aaba

**Comment by tcharding** [comment]
FWIW looks good to me.

**Review by Kixunil — APPROVED** [review]
ACK 91c5d7192f4f588e580f0caf3427ca38547ee6ad

**Review by apoelstra — APPROVED** [review]
ACK 91c5d7192f4f588e580f0caf3427ca38547ee6ad

**Pull request merged**
