### PR TITLE
Fix deprecated v0.28.0

### PR DESCRIPTION
**Pull request by tcharding**
We have a bunch of things deprecated since v0.28.0, I believe we agreed to deprecate for two release cycles so this stuff can all be deleted now.

- Patch one does the `schnorr` module; the deprecated attribute usage is just plain wrong (see https://github.com/rust-bitcoin/rust-bitcoin/discussions/1275). Also, in an attempt to make the API more ergonomic, patch one adds re-exports of secp types.

- Patch 2 deletes all other code deprecated since v0.28.0

### CODE REVIEW

**Review by Kixunil — APPROVED** [review]
ACK 3f275f7f2b081eb805a94b44339145266a556364

I'd personally be fine with a shorter deprecation cycle. The crate is already undergoing frequent, large breaking changes so it doesn't change much.

**Comment by apoelstra** [comment]
Agreed, all I want from the deprecation cycle is users to have one version in which they get warnings instead of errors, so that they can fix their stuff piecemeal rather than in one mega-commit (or multiple non-compiling commits).

**Review by apoelstra — APPROVED** [review]
ACK 3f275f7f2b081eb805a94b44339145266a556364

**Comment by Kixunil** [comment]
It seems to me that the greatest value is being told what the new name is so you don't have to search the docs. And one release cycle provides this.

**Pull request merged**
