### PR TITLE
Refactor predict_weight function

### PR DESCRIPTION
**Pull request by yancyribbens**
I was thinking maybe we could re-factor `predict_weight` and close https://github.com/rust-bitcoin/rust-bitcoin/pull/1793.

### CODE REVIEW

**Comment by apoelstra** [comment]
Definitely agreed. This turns a no-allocation API into an unnecessary-allocation API, and reduces its flexibility.

**Comment by yancyribbens** [comment]
@Kixunil @apoelstra I updated the function signature to:

```
pub fn predict_weight<I, O>(inputs: &mut I, output_script_lens: &mut O) -> Weight
where
    I: Iterator<Item = InputWeightPrediction> + Clone,
    O: Iterator<Item = usize> + Clone,
    I::Item: Borrow<InputWeightPrediction>,
    O::Item: Borrow<usize>,
{
```

That just a mutable ref is passed and a second heap allocation is avoided.  What do you think?

**Comment by apoelstra** [comment]
>That just passes a mutable ref and a second heap allocation is avoided. What do you think?

I'm unclear on the benefit here ... this still makes the API harder to use and less flexible.

**Comment by yancyribbens** [comment]
I was hoping to make the fold that does three things more readable.  However I didn't think that type signature would need to be modified so much.

**Comment by yancyribbens** [comment]
Iterators in rust are much different than other languages I'm learning.  When an iterator is used it is consumed and theres no way to unwind it which is why the signature must be cloneable and mutable so that the same iterator can be copied and consumed again.

**Comment by yancyribbens** [comment]
Anyway, since this seems like a failed attempt to refactor this section in hopes of making it more readable it can be closed

**Comment by Kixunil** [comment]
I guess better just learn the combinators. Perhaps change fold to `for` if people really dislike this a lot but not sure if it'll help much.

**Comment by yancyribbens** [comment]
Iterators ought to perform better than for loops. It would be nice for this code path to have some benchmarks.

**Comment by Kixunil** [comment]
I think there wouldn't be a difference in this case. It applies when calling `collect` but in this case we're doing trivial math operations.

**Comment by yancyribbens** [comment]
I meant that generally iterators are easier for the compiler to reason about than something as generalized as a for loop.  I'm not sure if the rust compiler actually makes that type of optimization yet.

**Pull request closed without merging**
