### PR TITLE
add SECURITY.md

### LINKED ISSUE #1718: There is no SECURITY.md
`CONTRIBUTING.md` includes the following:
```
## Security

Security is the primary focus for this library; disclosure of security
vulnerabilities helps prevent user loss of funds. If you believe a vulnerability
may affect other implementations, please disclose this information according to
the [security guidelines](./SECURITY.md), work on which is currently in progress.
Before it is completed, feel free to send disclosure to Andrew Poelstra,
apoelstra@wpsoftware.net, encrypted with his public key from
<https://www.wpsoftware.net/andrew/andrew.gpg>.
```

However there is no file `SECURITY.md` in the repo?

### PR DESCRIPTION
**Pull request by apoelstra**
Draft of a SECURITY.md. Right now it only lists me -- if you are willing to be an alternate, don't be afraid to ask. Pretty-much any of the major regular contributors would be fine.

Fixes #1718

### CODE REVIEW

**Comment by tcharding** [comment]
If it adds any value I'm happy to be an alternate. I currently only have my gpg fingerprint on my website, I'll put my full pubic key up and then I can patch SECURITY.md after this merges if its wanted/needed.

**Review by tcharding — DISMISSED** [review]
ACK a29465e1cd7c23b91c06927cb781b520d4b1a6f6

**Comment by apoelstra** [comment]
@tcharding Sure, I'm happy to have you as an alternate. Agreed, we can maybe do it in a separate PR.

It would be nice if I could directly check your GPG fingerprint but I'm sure we could find some out-of-band way for me to authenticate, for these purposes. If we are together (at TABConf in the fall? in BTC Miami in May?) we should make a point of signing each others' keys.

**Comment by tcharding** [comment]
> we should make a point of signing each others' keys.

Yes definitely, lets do ours in Prague as well @Kixunil - `rust-bitcoin` web of trust :)

**Review by sanket1729 — DISMISSED** [review]
ACK a29465e1cd7c23b91c06927cb781b520d4b1a6f6

**Comment by sanket1729** [comment]
We can also add link via github.com if that's acceptable. `https://github.com/{user}.gpg` gives the gpg key for each user. You can find mine at https://github.com/sanket1729.gpg

**Comment by tcharding** [comment]
Cool, TIL. I won't bother putting mine on my web site then :)

**Comment by apoelstra** [comment]
Will wait for @Kixunil before merging.

**Review by Kixunil — DISMISSED** [review]
ACK a29465e1cd7c23b91c06927cb781b520d4b1a6f6

**Comment by Kixunil** [comment]
I use keybase for the key. I know it got bad rep for shilling shitcoins but it still works for its purpose.

**Comment by apoelstra** [comment]
Added `bitcoin-private`. Also reflowed all the text to 99 cols (sorry).

FYI 99 is much easier than 100 for me because I can type `099lb` to jump to that column and back to the previous word. If it were 100 I'd have to type an extra character.

**Review by sanket1729 — APPROVED** [review]
ACK 9ade4f36208f872cd21f2b0094204541858c97a6

**Review by tcharding — APPROVED** [review]
ACK 9ade4f36208f872cd21f2b0094204541858c97a6

**Pull request merged**
