### PR TITLE
Polish the `hashes` crate

### PR DESCRIPTION
**Pull request by tcharding**
`hashes 1.0.0` can't be far away, here is a quick polish (done while I waited for my car to get fixed).

Everything here is internal except stuff to docs. Note please I claim "internal change only" in a bunch of patches that do code moves but these effect the docs build because order is preserved in some instances.

### CODE REVIEW

**Comment by apoelstra** [comment]
These all look good. In 62617cf9acf880379cfeecb756eb438756d78a23 you move `from_engine` to `hash_type` in preparation for renaming it `general_hash_type`. I guess you then want to rename `hash_type_no_default` to something else?

This PR is good for now; additional changes can go in later PRs.

Will manually add API Break label because of the macro rename.

**Review by apoelstra — APPROVED** [review]
ACK 12f261c00958c918b1c991332ede64153ded0bb6; successfully ran local tests

**Comment by tcharding** [comment]
`hash_type_no_default` creates a type with inherent functions the same as `Hash` and `general_hash_type` creates one with inherent functions the same as `GeneralHash` - that is why I left it as is.

**Comment by apoelstra** [comment]
Oh, yeah, that's reasonable.

Will give Kix 48 hours before merging.

**Comment by tcharding** [comment]
Merge please.

**Review by apoelstra — APPROVED** [review]
ACK 1cb24c1f150bc2d65d0be439f2005f41d95ad23c; successfully ran local tests

**Pull request merged**
