### PR TITLE
merkle_block: add resource limit check during deserialization

### LINKED ISSUE #2606: deserializing network message can request arbitrary sized allocations
You can test the bitcoin/deser_net_msg.rs fuzztest with
```
73656e646d65726b6c65626c6f636b0080000000010000000000000003343333333333330333333333333334000000ffff000000000000002e2e2e310000000100000000312e2e2e2e2e2e2e000000000000000000000000000000000000000000000000000000000000000000ffffffffffffffff00000000000000000000000000000000000000000000000000000000000000000000002e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e6765746366636865636b70742e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e2e00000000000000000000000000000000000000000000b0b3e37fb13a4534caaf00ee0f777478696472656c61795b31db354aae4fdab52a9ad5255a60e2f807d72eb08893005e0d6e6f74666f756e642f21ed076bd50d250ac51fbff4268902056f11771bd47187854c252e4fda2768cd1280808080e76fbadfcdb86fa091d97c8d6c93476eb080d6d0225090a4400b046ad82937ebc7aa7c8f2e2e2e2e2e703433333333333303670000000000000100000000000000000003362c2c2c2c2c2c626f626b2c8014636b6c74190d0d
```
and it'll fail with
```
memory allocation of 576460752303423480 bytes failed
```

We need to fix this before the next release and may need to backport.

### PR DESCRIPTION
**Pull request by apoelstra**
Fixes #2606

### CODE REVIEW

**Comment by apoelstra** [comment]
I don't think this method is used except by applications implementing the p2p protocol (and I am not aware of any, at least not major ones) so I don't believe we need to bend over backward to contact or patch anybody.

But we should backport to all version back to 0.28 which is the oldest version I think is in wide use.

**Comment by apoelstra** [comment]
Fuzzed deserialization of `MerkleBlock` for 30 minutes so for with this PR. Will let it run overnight.

**Review by tcharding — APPROVED** [review]
ACK f1dcfab2934437501ed46274cfd5c366d776643f

Super cool to see this fixed.

**Comment by apoelstra** [comment]
Fuzzing has passed for 14.5 hours now (on a 32-core machine).

**Comment by tcharding** [comment]
Does that make it well and truly fu**ed?

**Comment by apoelstra** [comment]
> Does that make it well and truly fu**ed?

It means that the fix works. (Though we may want to tighten it; I think `MAX_VEC_SIZE` is orders of magnitude larger than we need....but I also want something that's obviously sufficient so we can merge this quickly. We can tighten it later.)

**Comment by tcharding** [comment]
Ugh, sorry man - that was a joke (I literally had "(joke)" after it at first and removed it. fuzzed == fu**ed and the other interpretation. Too smart for my own good :)

**Comment by apoelstra** [comment]
Oh, lol :) I missed the pun.

**Review by sanket1729 — APPROVED** [review]
ACK f1dcfab2934437501ed46274cfd5c366d776643f

**Pull request merged**
