### PR TITLE
internals: Bump version to 0.2.0

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for release bump the version and add a changelog entry. Includes updating the dependency in `bitcoin` and `hashes`.

### CODE REVIEW

**Comment by Kixunil** [comment]
I don't remember any breaking changes to the crate, do you?

**Comment by apoelstra** [comment]
I'm unsure about #1297. Other than that, no, no breaking changes.

**Comment by tcharding** [comment]
To be honest I didn't think too hard about it, I'm basically of the opinion that semver pre-1.0 in rust-land is a clusterf**k so just bump the version to be safe and save having to think about it.

**Comment by apoelstra** [comment]
IMHO it's fine to do a major bump on `internals` "just to be safe".

For any other crate in this repo, we would need to be much more careful :P.

Anyway this whole discussion is another argument for #1880.

**Comment by tcharding** [comment]
Yeah I was assuming that `internals` would never go to v1.0, should never appear in the public API and should get a version bump everytime we release anything (since, at least for now, we tend to release the whole stack).

Is it technically wrong to do a minor version bump that includes no code changes (e.g. docs only, as an extreme obviously contrived example)? Question relates to semver rules in general and also cargo's interpretation of semver.

**Comment by tcharding** [comment]
Now includes patches to update minimal/recent lock files. Please not the log in the minimal update because there are changes I cannot explain.

**Comment by tcharding** [comment]
Needs `once_cell` pinning, will do tomorrow.

**Comment by tcharding** [comment]
Alright, that's two hours of trying to sort out these dependencies - I'm giving up for now.

**Comment by tcharding** [comment]
related: https://github.com/rust-bitcoin/rust-secp256k1/pull/621

**Comment by tcharding** [comment]
Right, this has got be baffled. Why is the pinning not working on CI? It works locally.

**Comment by tcharding** [comment]
We should document this upgrade process, it is proving to be quite annoying and wasting a whole bunch of time.

**Comment by tcharding** [comment]
```
cargo 1.48.0 (65cbdd2dc 2020-10-14)
+ cargo update -p serde --precise 1.0.156
    Updating crates.io index
    Updating git repository `[https://github.com/llogiq/mutagen`](https://github.com/llogiq/mutagen%60)
error: failed to select a version for the requirement `once_cell = "=1.18.0"
```

The `once_cell` pinning shell command is not being run?

**Comment by tcharding** [comment]
> @tcharding you need to pin it in the included `Cargo-*.lock` files.

Oh shit, that sucks - that means we require different lock files for MSRV builds to non-msrv builds. 

Perhaps we should use `Cargo-minimal.lock` only for MSRV build (and rename it to `Cargo-msrv.lock`) and use `Cargo-recent.lock` for stable build. Then remove the `--locked` for beta/nightly builds?

**Comment by tcharding** [comment]
Added an initial patch that makes the MSRV tests only run against the minimal lock file, justified in the commit log.

**Comment by tcharding** [comment]
> you need to pin it in the included Cargo-*.lock files.

I didn't want to do this because it effects the non-MSRV CI runs.

**Comment by apoelstra** [comment]
> I didn't want to do this because it effects the non-MSRV CI runs.

Yes...we don't have separate lockfiles for MSRV and non-MSRV. That would be awful to maintain. It's fine to just not test with versions of crates that break MSRV.

**Comment by tcharding** [comment]
I'm not sure what to do about this one. Putting on ice until hex is released.

**Comment by apoelstra** [comment]
Hex is released now FYI :)

**Comment by tcharding** [comment]
BOOM!

**Comment by tcharding** [comment]
> > I didn't want to do this because it effects the non-MSRV CI runs.
> 
> Yes...we don't have separate lockfiles for MSRV and non-MSRV. That would be awful to maintain. It's fine to just not test with versions of crates that break MSRV.

So if I'm understanding you correctly we pin to versions that work with MSRV then test with these versions (i.e., minimal and recent never include versions higher than those pinned). This means everytime someone breaks semver rules and we have to change the pinning we have to update the comited manifests, is that an additional maintenance burden we want? It is already a PITA to fix the pinning (usually across the whole stack).

**Comment by apoelstra** [comment]
> So if I'm understanding you correctly we pin to versions that work with MSRV then test with these versions (i.e., minimal and recent never include versions higher than those pinned). This means everytime someone breaks semver rules and we have to change the pinning we have to update the comited manifests, is that an additional maintenance burden we want?

No, it means that whenever *rustc* breaks and we're forced to upgrade, we have to update our manifests. When a crate breaks semver we won't even notice because we won't upgrade to the new broken crate.

**Comment by tcharding** [comment]
ok, I've not _fully_ internalised everything you said but all the pinning stuff I did before was based on wrong assumptions on how things worked. Just hit me with a stick if I ask you the same thing again in a month.

**Review by apoelstra — APPROVED** [review]
ACK 8813a63ec90867f226f350cf66653c8da5b4249b

**Review by sanket1729 — APPROVED** [review]
utACK 8813a63ec90867f226f350cf66653c8da5b4249b

**Comment by apoelstra** [comment]
Nice :) we can release this today and maybe even release the new hex-conservative today.

**Review by apoelstra — APPROVED** [review]
ACK 8813a63ec90867f226f350cf66653c8da5b4249b

**Comment by apoelstra** [comment]
Tagged and published :)

**Pull request merged**
