### PR TITLE
Tracking PR for `v0.31.0-rc2` release

### PR DESCRIPTION
**Pull request by tcharding**
Prepare for the v0.31.0-rc2 release.

- Add changlog entries
- Add a `just update-lock-files` command
- Bump the version ready for next RC release

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 38960ab5a558e4467ab6bc5f54b0bb4bfb8c6a39

**Comment by apoelstra** [comment]
Looks great! This should be an easy one for others to ACK -- we are just adding a changelog and calling it a new RC.

Then in a week, if we have no trouble, we'll do a real release.

**Review by clarkmoody — APPROVED** [review]
ACK 38960ab5a558e4467ab6bc5f54b0bb4bfb8c6a39

**Comment by apoelstra** [comment]
Tagged and published.

We'll plan to re-tag and release this as 0.31.0 on Friday Oct 27, assuming nobody shows up with things we need to fix.

**Comment by sanket1729** [comment]
Thanks, that should be enough time for me to also play along with latest
rc.

**Comment by apoelstra** [comment]
If you need more time I'm happy to delay it!

**Comment by tcharding** [comment]
> Tagged and published.

Looks like you forgot to push the tag man.

**Pull request merged**
