### PR TITLE
Move `block::Header` to `primitives`

### PR DESCRIPTION
**Pull request by tcharding**
- Patch 1: Trivial preparation. 
- Patch 2 and 3: Reduce the API surface in a disappointing way due to the orphan rule.
- Patch 4: Do the move.

### CODE REVIEW

**Comment by apoelstra** [comment]
In 538299de8639b56497a66acfdb91fcfcd0a4eeb0:

Rather than removing the field from the debug output can you replace it with the fixed string `FIXME` or something? It's fine if it's ugly; this is just debug output; but we don't want to forget this.

**Comment by apoelstra** [comment]
Actually, in this case I think we should move `block_hash` over and just reimplement it directly. It's not a complicated function and it's pretty centrol to what `block::Header` is.

For refeence, we encode `version` `prev_blockhash` `merkle_root` `time` `bits` `nonce` in that order into a hash function. The two hashes are input directly. All the others are 32-bit little-endian integers.

**Comment by tcharding** [comment]
Yeah, nice. I'll hack it up.

**Comment by tcharding** [comment]
This is way nicer, top idea bro!

**Comment by apoelstra** [comment]
Will give Kix his requisite 48 hours' notice before merging, unless this is blocking stuff.

**Comment by tcharding** [comment]
Lets give him 48, thanks.

**Pull request merged**
