### PR TITLE
Update serde to 1.0

### PR DESCRIPTION
**Pull request by jeandudey**

### CODE REVIEW

**Comment by jeandudey** [comment]
What is happening with travis?

**Comment by dongcarl** [comment]
I think `serde-derive` uses requires 1.15 and Travis is supposed to be testing against 1.14

**Comment by dpc** [comment]
As I've stated in https://github.com/rust-bitcoin/rust-bitcoin/issues/98#issuecomment-411524256 , I don't know what are reasons behind debian stable being blocking requirement, but having `serde` support is quite fundamental since it's the facto standard for serialization in Rust, and a heavy interoperability chokepoint.

**Comment by apoelstra** [comment]
Only `serde_derive` requires 1.15; `serde` itself is fine with 1.14.

To get around `serde_derive` we have a pair of macros `serde_struct_impl` and `serde_struct_enum_impl`. These are nowhere near as powerful as `serde_derive` but we only need the basics.

`serde_struct_impl` can be updated with 1.0 without too much trouble (remove the `MapVisitor::missing_field` business which has been removed from serde and isn't used anyway) and `serde_struct_enum_impl`can just be deleted since we don't use it anywhere.

**Comment by jeandudey** [comment]
@apoelstra I'm going to close this in favor of #125 and keep the discussion there, I'm going to address your changes in a moment

**Pull request closed without merging**
