### PR TITLE
Use a vector of bytes in the PSBT `Input` type

### PR DESCRIPTION
**Pull request by tcharding**
Done in preparation for briging #1606 back to life.

The first patch creates a new local var, separate because `rustfmt` goes berserk on this change. Patch 2 does the sig to vector change.

### CODE REVIEW

**Comment by apoelstra** [comment]
concept ACK. Will actually ACK shortly. We may want to hold off until after the release on this, unless we are planning to get the ECDSA separation into this upcoming release. Otherwise it's a reduction in type safety without a ton of benefit.

**Comment by tcharding** [comment]
> We may want to hold off until after the release on this, unless we are planning to get the ECDSA separation into this upcoming release. Otherwise it's a reduction in type safety without a ton of benefit.

Good point. I'll do the ecdas separation shortly as a separate PR and we can wait for that to get some traction before thinking about merging this one. I don't think its super important to get it in next release.

**Comment by tcharding** [comment]
Do yo want some other visual marker on this PR so you remember not to merge it?

**Review by apoelstra — CHANGES_REQUESTED** [review]
Using "request changes" as a "hold off on merging til next release" marker.

**Comment by sanket1729** [comment]
Conceptually, this seems like a step backward. Going from strongly typed to weakly typed API. If anything I think we should make this an enum of `SegwitSig` and `LegacySig`

**Comment by tcharding** [comment]
> If anything I think we should make this an enum of SegwitSig and LegacySig

If we want that then I can close this and do it as part of the ECDSA separation work, @apoelstra what do you think?

**Comment by tcharding** [comment]
Thanks for the review @sanket1729!

**Comment by apoelstra** [comment]
I agree with @sanket1729, let's close this one.

**Comment by tcharding** [comment]
Done!

**Pull request closed without merging**
