### PR TITLE
Remove `private_key_debug_is_obfuscated` test

### PR DESCRIPTION
**Pull request by diogocanut**
Solves #3186.

### CODE REVIEW

**Comment by tcharding** [comment]
> Just need the confirmation from this comment https://github.com/rust-bitcoin/rust-bitcoin/issues/3186#issuecomment-2303546122 if we should move or delete.

Thanks for your contribution @diogocanut. Perhaps as an exercise, and also because it is in general good practice, please add a _why_ section to the commit log. You will then be able to answer your own question.

If you don't know what a "why section" means then check out: https://chris.beams.io/posts/git-commit/

**Comment by diogocanut** [comment]
@tcharding thanks. Added a new section to my commit log explaining the reasons.

**Review by apoelstra — APPROVED** [review]
ACK d2442af7028893bca461af36c080e5853a32693d; successfully ran local tests; sure

**Comment by diogocanut** [comment]
@tcharding Got it. I've updated the commit log. Thanks.

**Review by tcharding — APPROVED** [review]
ACK 7bff725494bed02bed7f5d2af8278c89aaf73f40

**Comment by tcharding** [comment]
Nice, thanks man.

**Review by apoelstra — APPROVED** [review]
ACK 7bff725494bed02bed7f5d2af8278c89aaf73f40; successfully ran local tests; sure

**Pull request merged**
