### PR TITLE
infallible conversions from hashes to secp256k1 message

### PR DESCRIPTION
**Pull request by bruteforcecat**
Close [824](https://github.com/rust-bitcoin/rust-bitcoin/issues/824)

Updated
The CI will be fixed after updating to new secp256k1 version including this change https://github.com/rust-bitcoin/rust-secp256k1/pull/410

### CODE REVIEW

**Comment by apoelstra** [comment]
There are two issues here:

1. Our CI is broken because of some honggfuzz issue. This should be fixed now as I just merged #848 
2. There is some issue with the `bitcoin_hashes` feature, which I haven't understood yet. But we should fix this, there's no reason rust-bitcoin shouldn't have this feature turned on.

**Comment by bruteforcecat** [comment]
> There are two issues here:
> 
>     1. Our CI is broken because of some honggfuzz issue. This should be fixed now as I just merged [Tempararily pin fuzzer on rust 1.58 #848](https://github.com/rust-bitcoin/rust-bitcoin/pull/848)
> 
>     2. There is some issue with the `bitcoin_hashes` feature, which I haven't understood yet. But we should fix this, there's no reason rust-bitcoin shouldn't have this feature turned on.

As u said, first issue is resolved after rebasing latest master. For the issue 2, it looks like it's related to no std. I am looking into this🙏🏽(Changed PR status to draft)

**Comment by tcharding** [comment]
For your reference, the CI failure has an open [issue](https://github.com/rust-bitcoin/rust-bitcoin/issues/830).

**Comment by bruteforcecat** [comment]
> For your reference, the CI failure has an open [issue](https://github.com/rust-bitcoin/rust-bitcoin/issues/830).

Yes I think the issue should be related to bitcoin_cash default-features is enabled in rust-secp256k1. I get the ci pipeline working by adding `default-features = false` in forked rust-secp


Related commits in my forked ones

rust-bitcoin https://github.com/bruteforcecat/rust-bitcoin/commit/19d1bfa00c35d7a2d7f2ce2a4b61c05f5753cfab
related github action https://github.com/bruteforcecat/rust-bitcoin/actions/runs/1908337297
rust-secp256k1 https://github.com/bruteforcecat/rust-secp256k1/commit/e3af3445e3744e92321e0c307f799fd042ca9600

**Comment by apoelstra** [comment]
Looks like this was fixed by #1118

**Pull request closed without merging**
