### PR TITLE
Expose XOnlyPublicKey in crate root

### PR DESCRIPTION
**Pull request by sanket1729**

### CODE REVIEW

**Comment by sanket1729** [comment]
It was previously exposed in 0.29.0 and we removed it in 0.30

**Comment by Kixunil** [comment]
IIRC @tcharding had some reason not to? I didn't think much about this one...

**Comment by apoelstra** [comment]
I'm easy. We can go ahead and put it back, along with these sighash types. I think we just thought it was too obscure.

**Comment by Kixunil** [comment]
IME public keys are way less obscure than sighash types.

**Comment by tcharding** [comment]
I was working under the idea that we decided on before, and documented in the release blog post, that "types exported at the crate root should be in the Bitcoin vernacular". Amusingly the `XOnlyPublicKey` was the exact type I used in the example in the blog post :)

I.e. "bitcoin pubkey" is in the vernacular but "bitcoin x-only pubkey" is not, or so I claimed, am I wrong?

One counter-argument is that having to 
```rust
use bitcoin::key::XOnlyPulbliKey;
use bitcoin::PublicKey
```
Is un-ergonamic.

Counter-argument to the counter-argument, one still has to go into the `key` module to get all the other taproot key types so why is _only_ the `XOnlyPublicKey` exported?

**Comment by Kixunil** [comment]
`bitcoin::PublicKey` should really be called `LegacyPublicKey`. And, as the name suggests, it probably shouldn't be used much anymore, so if we're not re-exporting `XOnlyPublicKey` I'd prefer to not export legacy stuff either.

It also looks a bit odd that `bitcoin::PublicKey` isn't the same as `secp256k1::PublicKey` but `bitcoin::XOnlyPublicKey` is the same as `secp256k1::XOnlyPublicKey`. I know exactly why and it's not wrong, just odd. I was trying to find if there's any reason to newtype it but couldn't. So if anyone knows of any that'd be helpful.

**Comment by apoelstra** [comment]
So, the reason `bitcoin::PublicKey` is exported under that name is exactly that it needs to be distinguishable from `secp256k1::PublicKey`. If we remove the re-export (which I agree with the logic of; we shouldn't be treating it as preferable to `XOnlyPublicKey`) then we should rename the type to `BitcoinPublicKey`.

As for newtyping `secp256k1::XOnlyPublicKey` ... I don't think we should do that. It's extremely annoying having distinct types in rust-bitcoin and rust-secp for legacy pubkeys, because as soon as you need a compressedness flag you have to virally change all your secp pubkeys to bitcoin ones, and then stick `.key` onto basically every access where you actually just want the pubkey. It is a big benefit of xonly public keys that the keys are just keys.

**Review by tcharding — DISMISSED** [review]
ACK d78d147579d28fac4e059318e85457509e27a7cf

**Comment by tcharding** [comment]
I'm acking this but FTR I'm not _exactly_ sure what we are exporting at the crate root and what we are not. Also reading the discussion above about `bitcoin::PublicKey` I can't figure out if there is anything actionable in it?

**Comment by Kixunil** [comment]
> I'm acking this but FTR I'm not _exactly_ sure what we are exporting at the crate root and what we are not. Also reading the discussion above about `bitcoin::PublicKey` I can't figure out if there is anything actionable in it?

Adding `verify` method to it which simply forwards to `secp256k1`.

**Comment by sanket1729** [comment]
There are two main ways for organizing types in root. 1) Ergomics, 2) Bitcoin vernacular. 

I think we can do both. We should definitely have all the bitcoin vernacular types exported, but also many of common types according to (1) Ergonomics.

**Comment by sanket1729** [comment]
I don't feel strongly enough about this. So, I am also okay with the way it is being done currently. But still would mildly prefer an export.

**Comment by tcharding** [comment]
I think there is a bunch of work still to be done on the crate level re-exports so we have time to discuss this. I'm pretty sure we aren't going to get it right first time but surely in the next couple of releases we can get this locked.

**Comment by tcharding** [comment]
Needs rebase please.

**Comment by sanket1729** [comment]
Rebased

**Comment by tcharding** [comment]
Needs `cargo +nightly fmt` bro

**Review by tcharding — APPROVED** [review]
ACK 1db0b21b84624ad27658c539efcd642c95272b30

**Review by apoelstra — APPROVED** [review]
ACK 1db0b21b84624ad27658c539efcd642c95272b30

**Pull request merged**
