### PR TITLE
use BTreeMap instead of HashMap to always serialize the same

### PR DESCRIPTION
**Pull request by RCasatta**
It happened to me the psbt added in the test case was sometimes serialized in a different byte array.
That is due to the fact this psbt has 2 partial sigs in the map and rust HashMap is randomized.
This PR propose to use BTreeMap which is visited in order.

### CODE REVIEW

**Comment by apoelstra** [comment]
concept ACK. Curious what others think. There will be a perf/memory hit here. But on the other hand PSBTs can never get that large in practice..

**Comment by apoelstra** [comment]
@RCasatta Can you add a PSBT fuzztest (or if there is one, make it properly roundtrip instead of counting fields or whatever hack currently exists)?

I remember testing the PSBT PR I had a lot of trouble because of this.

**Comment by RCasatta** [comment]
added PSBT fuzztest, since fuzz data could be deserialized even if fields are out of order, the comparison is done in the following way:

if the fuzzed data is successfully parsed into a PSBT, then the test serialize/deserialize/serialize to compare to our own serialization.

(The fuzzer found a match on wrong code 0a30a48, impressive)

**Comment by apoelstra** [comment]
Nice! I think that's the best we can do.

**Pull request merged**
