### PR TITLE
Change method return type for to_unsigned()

### PR DESCRIPTION
**Pull request by yancyribbens**
Any SignedAmount can now be cast to Amount since the range is the same.  Specifically, the range for SignedAmount is (- 21 million, 21 million) while the range for Amount is (0, 21 million).  Therefore any value from Amount can be cast to a SignedAmount and it will work.  Note it's not the same and still requires checking when going from SignedAmount to Amount since Amount can't handle the negative range.

### CODE REVIEW

**Comment by yancyribbens** [comment]
There is still a check required when going from signed to unsigned.  Marking as draft until I update it.

**Comment by yancyribbens** [comment]
Apologies for the noise.  This is now ready for review.

**Comment by yancyribbens** [comment]
rebased

**Comment by apoelstra** [comment]
In 84632b6b89e15d49b020305017742f470f17effe:

Need comment on the new cast.

**Comment by yancyribbens** [comment]
> Need comment on the new cast.

Updated comment.  Also, since we are allowing a loophole in the invarient, this comments on that and is based on the commit that adds `from_sat_unchecked`.  There's no reason we can't introduce that as a smaller PR for easy review.

```rust
    /// Converts to a signed amount.
    ///
    /// # Panics
    ///
    /// If Amount violates the invariant.
    pub fn to_signed(self) -> SignedAmount {
        SignedAmount::from_sat_unchecked(self.to_sat() as i64)
    }
```

**Comment by yancyribbens** [comment]
should be SighnedAmount not Amount.  Will update.

**Comment by yancyribbens** [comment]
~should be SighnedAmount not Amount. Will update.~

The original is correct.

**Comment by yancyribbens** [comment]
I used Tobin's copy comment for `_unchecked` since he disagreed with mine.

**Comment by apoelstra** [comment]
There is still no comment on the cast, and the doccomment is confusing. "Panics if `Amount` violates the invariant"? **We do not and should not attempt to document what happens if the user uses unchecked methods to violate invariants.** The point of invariants is that they are invariant.

**Comment by yancyribbens** [comment]
> There is still no comment on the cast, and the doccomment is confusing.

Sorry for my confusion.  Can you point me to what you mean by comment the cast?  I had thought you meant the `to_signed()` method needs commenting (which performs the cast).  I'll undo that comment since we don't need to comment on the invarient after all.

**Comment by apoelstra** [comment]
>Sorry for my confusion. Can you point me to what you mean by comment the cast?

I mean that, on the same line as `as i64`, there needs to be a comment explaining why it's ok to use a truncating cast. This way when we grep for casts we can see that it's justified.

**Comment by yancyribbens** [comment]
> I mean that, on the same line as as i64, there needs to be a comment explaining why it's ok to use a truncating cast. This way when we grep for casts we can see that it's justified.

Got it.  Thanks for the clarification.  The format will complain if it's on the same line, so I placed it above, unless  we really really need it on the same line.

**Comment by yancyribbens** [comment]
I see now that before this has a rustfmt skip just to keep it on the same line?  I guess I should follow suit with that.

**Review by apoelstra — APPROVED** [review]
ACK 3084d915c34e9023ab97aa58f7d7f0fa6660622b; successfully ran local tests

**Comment by tcharding** [comment]
This doesn't make the `amount` module material worse so I'm fine for it to merge. I'm not acking because this PR has problems but I don't want to invest the time to explain them. I'm going over the whole module anyways in #3794.

**Comment by yancyribbens** [comment]
> @yancyribbens I basically have no faith that your changes don't introduce bugs or are wrong in some other way that I didn't think out.

@tcharding To be fair, I don't have much faith in the quality of your reviews, which I think results in a lot of friction over the last few years.  There are maintainers on this project that when they Ack something, I'm confident they understand what they are Acking.  I've observed more than a few occasions where you Ack things you don't understand, and in one case, it came back to bite us both.  Making a mistake and missing something is unavoidable which is why a two ack policy is nice, but if the second ack is just an echo of the first, that doesn't provide much of a safe-guard.  I've seen many bugs of yours get caught by reviews, imagine how you would have felt if it was missed by a reviewer because they didn't understand what they were reviewing well enough.  This is one reason I choose to not Ack things unless I'm really sure, and since I'm not a maintainer, I consider it to be misleading even if I do go around typing Ack things I am confident on.

> To help me gain faith please do tiny patches and fully explain everything you do. 

Great idea and I encourage you lead the way and do the same.  Personally I try to make respectable size PRs and reviewable size commits to reduce the possibility of things being missed.

I hope we can understand each other and try to build trust in each others work.

**Comment by yancyribbens** [comment]
Here is the commit message you say give you no confidence:

```
What: Add unchecked variant

Why: This variant is supplied in cases where a Result type does not need to
be handled.
```

What exactly is it you disagree with so fervently.  Unchecked is added because we don't want to deal with the return type and perform `unwrap()`.  While I'm sure there's a lot more that could be said, possibly in a more accurate way, this isn't something that I would chastise as obviously wrong.  If looked at with the corresponding diff, what could be improved in your opinion?

**Comment by yancyribbens** [comment]
> this PR removes TryFrom but does not add From and does not mention either of these things in the git log)

This is a good call out that From should be added since TryFrom is removed.  However, I don't think that it's a dangerous or egregious miss and could be added as a followup.  Thank you for point this out though and I agree there could be something in the commit log about it as well.

**Comment by yancyribbens** [comment]
I reduced the PR size by pulling out all of the renames which can be done in a different commit.

**Comment by yancyribbens** [comment]
Added a commit which adds From impl as requested in review

**Comment by yancyribbens** [comment]
I think that's enough changes for this PR

**Comment by yancyribbens** [comment]
Added mention of removing TryFrom in the Git log as requested during review.  Thanks for the suggestion Tobin, I think this makes the commit more succinct.

**Comment by yancyribbens** [comment]
tidy commit so that skip fmt isn't needed

**Review by apoelstra — APPROVED** [review]
ACK 1044b1727faa3918aabefd82d152dcf117632757; successfully ran local tests

**Review by tcharding — APPROVED** [review]
ACK e13355318e61e341e7cf3f17257e44d19029c6eb

**Comment by tcharding** [comment]
@apoelstra please prioritise merging this PR.

**Pull request merged**
