### PR TITLE
units: Refactor docs style

### PR DESCRIPTION
**Pull request by tcharding**
Clippy in #2629 is complaining, but the complaints are fair today - just refactor the docs style to remove the issue.

Lets not get tricky, just use normal outer rustdoc style comments.

Docs only, and no content changes - can go in via the one ACK carve-out.

### CODE REVIEW

**Review by apoelstra — CHANGES_REQUESTED** [review]
NACK. This looks worse and I already filed multiple clippy bugs about this, which were fixed. Let's just wait for the fixes to get in.

**Comment by tcharding** [comment]
Oh, no worries, sorry I missed that.

**Comment by tcharding** [comment]
I still think this is a legit error:
```rust
error: item has both inner and outer attributes
    --> units/src/amount.rs:1602:1
     |
1602 | / #[cfg(feature = "serde")]
1603 | | pub mod serde {
1604 | |     // methods are implementation of a standardized serde-specific signature
1605 | |     #![allow(missing_docs)]
...    |
1620 | |     //! }
1621 | |     //! ```
     | |___________^
```

**Comment by tcharding** [comment]
The `allow` attribute should be below the `//! ...` docs.

**Comment by apoelstra** [comment]
Yeah, we can move the `allow` attribute. But that's not what the error is saying, and the error is not legitimate :)

**Comment by tcharding** [comment]
Ok, with my record of mistakes yesterday I'm not going to maintain my position on this but FTR I thought I moved the `allow` and one of the two lint errors went away - its mute anyway because the other one is as you say.

**Pull request closed without merging**
