### PR TITLE
Standardize constructor type function docs

### LINKED ISSUE #3575: Creates/constructs/build etc
How particular do we want to be on the `rustdocs` of 1.0 crates

We have various ways of saying the same thing

- `/// Creates a new Foo] ...`
- `/// Constructs a new Foo ...`
- `/// Constructs Foo ...

I accidentally scratched the surface of this issue in: https://github.com/rust-bitcoin/rust-bitcoin/pull/3565

### PR DESCRIPTION
**Pull request by jamillambert**
As discussed in issue #3575 there are various ways of saying a new object is created.

These have all be standardized to the agreed version.

Close #3575

### CODE REVIEW

**Comment by apoelstra** [comment]
This looks good. Though many of the address constructors need to be reworded further. e.g.

```
/// Constructs a new pay to script hash P2SH address from a script.
```

should be something like

```
Constructs a new pay-to-script-hash (P2SH) address from a script.
```

**Review by apoelstra — APPROVED** [review]
ACK 1649b68589834dfe9d5b63812da3e9f0e5930107; successfully ran local tests

**Review by tcharding — APPROVED** [review]
ACK 1649b68589834dfe9d5b63812da3e9f0e5930107

**Comment by tcharding** [comment]
I'm guessing you did patch one with some sort of search-and-replace command? If so, in future, can you throw that in the commit log - that way reviewer can just tab through super fast without thinking. As it was I got stuck on the first patch looking at the `Construct` vs `Constructs` and also reading the rest of the sentance - until I realized this was a straight search-and-replace (`s/Create/Construct/g`). But otherwise, the patch separation is good and made review faster. Thanks man, you saved me many OCD trigger events.

**Comment by jamillambert** [comment]
Thanks for the advice.  If there is a similar patch in the future I'll try and be clearer in the commit message, looking at it from a reviewers perspective.

I have also reworded the Address constructor docs, but will wait until this is merged and open a new PR since it's already approved.

**Comment by tcharding** [comment]
Thanks man, we generally always try to optimize for the reviewer because review time is typically way more scarce that dev time. (Also reviewing is hard and boring where as dev is way more fun.)

**Pull request merged**
