### PR TITLE
Use `test_data` for big objects, add big block for benchmarking

### PR DESCRIPTION
**Pull request by RCasatta**
In the first two commits I moved some data from source files to the newly introduced `test_data` dir, including it with `include_[str|bytes]!` macro.

The second-to-last commit introduces a big block in test_data which is very handy in ser/de benchmark (I used it for #672) because with smaller blocks you may not notice performance improvements.

Since I don't want to pollute the package the last commit excludes the `test_data` dir from the published package. I think it's fine to do it because dependent packages don't run dependencies tests.

### CODE REVIEW

**Comment by Kixunil** [comment]
Light review ack: didn't verify whether the hashes and data match but I think if they didn't it'd be caught by tests.

**Review by apoelstra — APPROVED** [review]
ACK eb1444330930709e5a797eaf750c04d1f0c75d10

Also did not check that the hashes etc match but I did check that the claimed blocks are actually the right blocks :). `include_bytes!` is very cool, good find!

**Comment by RCasatta** [comment]
Had to rebase after merging #680.

After rebase I added 247a14f4c313f76c787869b2cbeeea386151c8e2 to use big block instead of making one

**Review by apoelstra — APPROVED** [review]
ACK 247a14f4c313f76c787869b2cbeeea386151c8e2

I'm really happy with this. Great to be using real blocks rather than ad-hoc contraptions in our testing and benchmarking code.

**Review by Kixunil — APPROVED** [review]
tACK 247a14f4c313f76c787869b2cbeeea386151c8e2

(not sure if my machine is screwed up or tests started to take much longer time than previously can't investigate right now)

**Comment by RCasatta** [comment]
> (not sure if my machine is screwed up or tests started to take much longer time than previously can't investigate right now)

Maybe adding too many `include_[bytes|str]` every time could blow the binaries. I think a solution to this and to the necessity of sharing functions across tests is to have an internal-only `test-utils` crate which is used as a dev-dependency via path

**Pull request merged**
