### PR TITLE
Move key to the crate root

### PR DESCRIPTION
**Pull request by tcharding**
Done as part of flattening the `util` module.

Move the `key` module to the crate root, deprecated the module in `util` and fix all paths in the codebase to use the new path.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 03e7ea6cf3920de24bec77e993c41770f3f7fa8a

**Comment by Kixunil** [comment]
Concept ACK, needs rebase. This shouldn't go into `crypto` should it?

**Comment by apoelstra** [comment]
Heh IIRC it actually *does* go into `crypto` in #1260 (as it should, IMHO). Maybe we should close this one?

**Comment by Kixunil** [comment]
Oh, I thought it doesn't belong there because it doesn't actually perform cryptographic operations, just simple conversions. Also I fear `bitcoin::crypto::key` will be frequent and annoying to write. But we can test it first.

**Comment by apoelstra** [comment]
We should probably re-export all the key types at the root of `bitcoin-crypto` as well as re-exporting them again at the root of `bitcoin`.

**Comment by tcharding** [comment]
#1260 does not move `key` into `crytpo/`. It does re-export aggressively:
```rust
pub use crate::crypto::ecdsa::{self, EcdsaSig, EcdsaSigError};
pub use crate::crypto::hash::{self, bitcoin_merkle_root, bitcoin_merkle_root_inline};
pub use crate::crypto::merkleblock::{self, MerkleBlock, MerkleBlockError, PartialMerkleTree};
pub use crate::crypto::schnorr::{
    self, SchnorrSig, SchnorrSigError, TapTweak, TweakedKeyPair, TweakedPublicKey,
    UntweakedKeyPair, UntweakedPublicKey,
};
pub use crate::crypto::taproot::{
    self, ControlBlock, FutureLeafVersion, LeafVersion, NodeInfo, ScriptLeaf, TaprootBuilder,
    TaprootBuilderError, TaprootError, TaprootMerkleBranch, TaprootSpendInfo, TAPROOT_ANNEX_PREFIX,
    TAPROOT_CONTROL_BASE_SIZE, TAPROOT_CONTROL_MAX_NODE_COUNT, TAPROOT_CONTROL_MAX_SIZE,
    TAPROOT_CONTROL_NODE_SIZE, TAPROOT_LEAF_MASK, TAPROOT_LEAF_TAPSCRIPT,
};
```

**Comment by tcharding** [comment]
> We should probably re-export all the key types at the root of bitcoin-crypto as well as re-exporting them again at the root of bitcoin.

Oh that's an interesting idea, re-exporting _outside_ of new subcrates that we create, I had not thought of that. So would the idea be that everything is still available at `bitcoin::foo` irrespective of how many layers of crates we make.

**Comment by tcharding** [comment]
Also, I'm confused by the comments in this thread - do we want `key` in `crypto/` or in the crate root. Currently I have it in the crate root (this PR and #1260). How do keys fit into your previous comment someplace @apoelstra that you often use everything but the crypto stuff (I don't remember where it is, all I remember is "here be dragons" :)

**Comment by apoelstra** [comment]
@tcharding I would like `key` in `crypto` yes, but also re-exported at the crate root.

"here be dragons" might be a bit strong -- but the key types, just like signatures and hashes, are unlikely to be useful for "casual" users who aren't deconstructing/constructing transactions, and anybody directly using them needs to think about what they're doing.

**Comment by tcharding** [comment]
Cool, got it. Cheers

**Comment by tcharding** [comment]
Closing this, moving it to `crypto` in #1260

**Pull request closed without merging**
