### PR TITLE
Release tracking PR: `io v0.1.0`

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for an initial release; add a changelog file. The version number is already set to `v0.1.0`.

### CODE REVIEW

**Comment by tcharding** [comment]
Big day crew, lets go!

**Comment by apoelstra** [comment]
Nice. I believe https://github.com/rust-bitcoin/rust-bitcoin/pull/2453 was the last missing piece.

**Review by apoelstra — APPROVED** [review]
ACK a464ec66a7e1691a3a5ec9891f9ef078aa6903a0 woohoo

**Comment by tcharding** [comment]
Hell yeah!

**Review by Kixunil — APPROVED** [review]
ACK a464ec66a7e1691a3a5ec9891f9ef078aa6903a0

**Comment by apoelstra** [comment]
As is tradition, we get two ACKs and a merge and *then* find out that we're unable to publish.

0.1.0 is already published as a "placeholder version" on https://crates.io/crates/bitcoin-io

We need to bump to 0.2.0 to do an actual release.

**Comment by apoelstra** [comment]
Lol, true!

**Pull request merged**
