### PR TITLE
Move bip143 module to crate root

### PR DESCRIPTION
**Pull request by tcharding**
We are attempting to flatten the `util` module.

Move the `bip143` module to the crate root out of `util`.

Currently `src/util/` is ignored by the formatter so this move requires `bip143` module to be formatted. Formatting is done as a separate patch so reviewers can run `cargo +nightly fmt` and compare the diffs if so desired.

### CODE REVIEW

**Review by apoelstra — DISMISSED** [review]
ACK 3be29602b2a7f6fee1778fc4c58bf75c730f822e

**Comment by tcharding** [comment]
Rebase to pick up recent fuzzer change.

**Review by apoelstra — APPROVED** [review]
ACK 059ba8cf6672b411dd9d70afd406d5b7a44c3e5e

**Comment by tcharding** [comment]
Rebase only, no other changes. Unusually, there were not conflicts.

**Comment by apoelstra** [comment]
Needs rebase again

**Comment by tcharding** [comment]
Rebase and update path to `bip143` in rustdoc.

**Review by apoelstra — DISMISSED** [review]
ACK 3121bdad332b964b155b3723531dced21c0b0e68

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK d16cff1d5f2573fcc664f28381ebfa89fb4d04bb

**Comment by tcharding** [comment]
All the code in this module was deprecated in v0.28.0 - I think we should just delete it.

**Comment by tcharding** [comment]
bip143 deleted as part of https://github.com/rust-bitcoin/rust-bitcoin/pull/1276

Leaving open until #1276 gets the green light.

**Comment by apoelstra** [comment]
Lol, is it true that this module was *deleted* in #1276 but somehow this PR to move it is okay by Github?

**Comment by tcharding** [comment]
Yeah GitHub's idea of what is mergable is totally borked right now.

**Comment by tcharding** [comment]
This is unneeded now :)

**Pull request closed without merging**
