### PR TITLE
bump version to 0.29.2, fix `test_data` exclude

### PR DESCRIPTION
**Pull request by RCasatta**
backport of #1315 

reduce crate package from 1.7M to 500k

### CODE REVIEW

**Comment by apoelstra** [comment]
Looks like a new clippy lint is breaking CI

**Comment by RCasatta** [comment]
Should I fix clippy even if it's a backport?

**Review by sanket1729 — APPROVED** [review]
ACK 708bf120c051ce5eb109f2f74f6a2db1823230d9

**Comment by Kixunil** [comment]
Maybe we should bundle it together with a fix for #1307?

**Comment by apoelstra** [comment]
@RCasatta yeah, we might as well fix it even in a backport, since it's quick and easy.

@Kixunil yes, agreed, let's bundle those together.

**Comment by RCasatta** [comment]
Clippy fixed

**Comment by sanket1729** [comment]
Is the CI broken again :(

**Comment by apoelstra** [comment]
I think this is an old break -- turning off features in honggfuzz -- that we also need to backport.

**Review by tcharding — APPROVED** [review]
Patch 2: 8e2f93a37cd828a62685698d7433d6a5c3b7e95c could have been backported using https://github.com/rust-bitcoin/rust-bitcoin/pull/1299 but I confirmed that the diff of the two patches is identical.

ACK b11a7d0b7bdaf9f58018cd017dee86f0fda73fa3

**Comment by Kixunil** [comment]
Shouldn't the first commit be the last one?

**Comment by apoelstra** [comment]
I think it's fine -- both commits compile independently. There isn't really any hope for "every commit passes `cargo clippy`" as a rule, since clippy changes too often.

**Comment by Kixunil** [comment]
I mean a commit performing version bump usually also signifies "the crate was released in this state". So a different ordering could be confusing (yes, we also have tags which are better, but still).

Side note: I'm also kinda intrigued by the idea of adding a commit that bumps the version to the next one with the `-dev` suffix right after the release.

**Comment by tcharding** [comment]
Now you mention it @Kixunil, I tend to agree. Perhaps we should have the patch from #1299, followed by the three Hongfuzz patches followed by the version bump patch? I don't think its super important bit its nice to set a good precedent since we are likely going to be backporting more often soon enough.

**Comment by Kixunil** [comment]
I'm thinking maybe we should fix #1343 ASAP and backport as well?

**Comment by tcharding** [comment]
Perhaps so as not to put too much of a burden on @RCasatta we can do 0.29.2 with the changes in this PR then once we sort out #1343 I can do the backport and then we can release 0.29.3? (Unless of course you just love backporting so much Riccardo that you want to do it all :)

**Comment by RCasatta** [comment]
commits reordered, used @tcharding's clippy fixed

Ci all green

**Comment by apoelstra** [comment]
There are two approvals but neither is actually for the current tip of this branch.

@sanket1729 @tcharding can you re-ack?

**Review by tcharding — APPROVED** [review]
Bother, I did not notice yesterday but we probably should have a changelog entry as well
```
# 0.29.2 - 2022-10-27

Backport Hongfuzz fixes as well as some fixes for new clippy version.
```

ACK db8ff70c6d90d18d5aa85c4734748fc8bad21264

**Comment by tcharding** [comment]
Thanks @RCasatta!

**Review by apoelstra — APPROVED** [review]
ACK db8ff70c6d90d18d5aa85c4734748fc8bad21264

**Pull request merged**
