### PR TITLE
Fix to_v0_p2wsh docs

### PR DESCRIPTION
**Pull request by dongcarl**

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
No? It's still a redeem script, and a "witness script" isn't a thing?

**Comment by TheBlueMatt** [comment]
Or maybe "witness redeem script".

**Comment by dongcarl** [comment]
@TheBlueMatt I got the terminology from here: https://bitcoincore.org/en/segwit_wallet_dev/#creation-of-p2sh-p2wsh-address

**Comment by TheBlueMatt** [comment]
That also says "witnessScript" not "witness script", and fwiw, that's the *only* docs I've ever seen refer to it as such. I'll file an issue on bitcoincore.org.

**Pull request merged**
