### PR TITLE
[Trivial] add get_best_tip_height to blokchain

### PR DESCRIPTION
**Pull request by tamasblummer**
tip height is a useful information readily computed by the tree. It is e.g. needed to set the height in a version message that a peer would send. Added a public method to retrieve it.

### CODE REVIEW

**Comment by tamasblummer** [comment]
I figured tip height it is accessible through get_block(best_tip().bitcoin_hash()).unwrap().height but that's ugly

**Comment by tamasblummer** [comment]
I also support blockchain out into its own crate. May I go ahaead, as I already worked on otimizing its performance?

**Comment by apoelstra** [comment]
@tamasblummer Yes, I'd love that

**Comment by TheBlueMatt** [comment]
I'd say go for it!

**Comment by tamasblummer** [comment]
Working on it. @apoelstra @TheBlueMatt : I think the script interpreter code should also be retired in favor of libbitcoinconsenus.

**Comment by TheBlueMatt** [comment]
Yea the rust implementation is out of date anyway, should almost certainly go (especially since it's a mutually-exclusive-with-Script build option that is non-default)

**Comment by apoelstra** [comment]
Agreed, I'd welcome a PR to remove the script_consensus stuff (or I will make one myself when I get a moment)

**Pull request merged**
