### PR TITLE
Fix typos in docs

### PR DESCRIPTION
**Pull request by danielabrozzoni**
See #828

### CODE REVIEW

**Review by Kixunil — APPROVED** [review]
ACK 4a6a12011d01b68664964596d2647ea6110cc025

Thanks!

**Comment by apoelstra** [comment]
Thanks!

I wonder if we should close #828 and open a new one, or what.

**Comment by Kixunil** [comment]
> I wonder if we should close https://github.com/rust-bitcoin/rust-bitcoin/issues/828 and open a new one, or what.

I was thinking about it and concluded I like closing it because it will not cause noise in the new one.

**Comment by apoelstra** [comment]
Ok. I'll ACK and merge this, then close the issue.

**Review by apoelstra — APPROVED** [review]
ACK 4a6a12011d01b68664964596d2647ea6110cc025

**Pull request merged**
