### PR TITLE
Fix CI

### PR DESCRIPTION
**Pull request by apoelstra**
This is a rebase of #3195 on master (since #3200 was merged) and adds one commit which fixes a few missing imports, which it appears was missed in the other "fix CI" PRs.

### CODE REVIEW

**Comment by apoelstra** [comment]
Added a commit which fixes the pin of rust-bitcoin-maintainer-tools. (The previous pin wasn't working, which is how CI on master here got broken; we merged a PR over there and it was automatically pulled in here.)

**Review by Kixunil — APPROVED** [review]
ACK d03e5456a3e2064f3c14d0e8727c820dfee406be

**Comment by apoelstra** [comment]
I think we've only got a few hours before @tcharding is up so we'll wait for him to take a look.

**Comment by apoelstra** [comment]
@tcharding can you take a look at this?

**Review by tcharding — APPROVED** [review]
ACK d03e5456a3e2064f3c14d0e8727c820dfee406be

**Pull request merged**
