### PR TITLE
WIP: Encapsulate the hex module

### PR DESCRIPTION
**Pull request by tcharding**
Done on top of #2473. This PR is the last 4 patches.

Incomplete, still have to handle the `hash_newtype` stuff discussed below.

Attempt to fully encapsualte the `hex` crate, I say "attempt" because `hex_conservative` still shows up in the sidebar under "crates" heading when I build docs locally.

### CODE REVIEW

**Comment by tcharding** [comment]
@apoelstra can you please merge #2335 so I can undraft this PR, and then use it in #2444.

**Comment by apoelstra** [comment]
Interesting use of `pub(crate)` on the internal error, to make `map_err(error::HexToArrayError)`. It feels a little magical but I guess it's ok.

**Review by apoelstra — DISMISSED** [review]
ACK c68864afbd4fac0d24f5265211c24ac56dcb319b

**Comment by tcharding** [comment]
hmmm, after playing with hex yesterday and finding errors unusable in `rust-bitcoin` we may be better off providing constructors and using `map_err(FooError::new)`? Makes sense if we are going to provide getters.

**Comment by apoelstra** [comment]
I think `FooError::new` wouldn't work, in general, because we'd want it to be polymorphic.

**Comment by tcharding** [comment]
FWIW I just realized that this error is different to other errors, it exists solely to hide the `hex` crate. We aren't likely to want add anything to it. Also it makes no sense for a user to have a `hex` error and want to turn it into a `bitcoin::error` hex error because they don't know the version of hex we are using.

**Comment by tcharding** [comment]
Oh boy, this PR because really hard to do if we introduce all the generics in https://github.com/rust-bitcoin/hex-conservative/pull/67

**Comment by tcharding** [comment]
To remove the generics I used this horrible code
```rust
/// Hex decoding error.
// Intentionally opaque so as to hide `hex` from the public API - do not make the inner error pub.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FromHexInvalidCharError(pub(crate) hex::FromHexError<hex::InvalidCharError>);

impl fmt::Display for FromHexInvalidCharError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result { write_err!(f, "from hex"; self.0) }
}

#[cfg(feature = "std")]
impl std::error::Error for FromHexInvalidCharError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> { Some(&self.0) }
}

/// Hex decoding error.
// Intentionally opaque so as to hide `hex` from the public API - do not make the inner error pub.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct FromHexHexToArrayError(pub(crate) hex::FromHexError<hex::InvalidCharError>);

impl fmt::Display for FromHexHexToArrayError {
    fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result { write_err!(f, "from hex"; self.0) }
}

#[cfg(feature = "std")]
impl std::error::Error for FromHexHexToArrayError {
    fn source(&self) -> Option<&(dyn std::error::Error + 'static)> { Some(&self.0) }
}
```

**Comment by Kixunil** [comment]
I've just realized that this is pointless because `hash_newtype!` impls `FromStr` returning `HexToArrayError`. So either we have to modify the macro to allow wrapping errors (benefit: we can say "failed to parse transaction ID" in the error message), remove `FromStr` (please no) or stabilize `hex-conservative`.

**Comment by apoelstra** [comment]
Or we could wrap `HexToArrayError` once in `bitcoin_hashes` and change `hash_newtype!` to use that. We can even stick a `&'static str` into the wrapped error to give a description of the hash so that we can say "failed to parse transaction ID".

**Comment by Kixunil** [comment]
Yes, and only stabilize hashes. I was hoping we wouldn't need to stabilize hashes, just the output of `hash_newtype` macro but maybe it's not really possible/easy enough.

**Comment by tcharding** [comment]
Draft till the dust settles on the `hex` crate error work.

**Comment by tcharding** [comment]
We aren't doing this anymore.

**Pull request closed without merging**
