### PR TITLE
Release tracking PR: `bitcoin-units 0.2.0`

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for releasing `units v0.2.0` bump the version number, add a changelog entry, update the lock files, and depend on the new version in all crates that depend on `units`.

Close: #3095

### CODE REVIEW

**Comment by Kixunil** [comment]
What breaking change did we do? Can we postpone it until I make the `amount::*Error` breaking changes I planned to?

**Comment by tcharding** [comment]
> Can we postpone it until I make the amount::*Error breaking changes I planned to?

Next release eh.

**Comment by apoelstra** [comment]
Agreed with @tcharding -- since we aren't planning any `bitcoin` releases anytime soon I don't think we should be shy with new releases of the "building block" crates (especially major releases which are opt-in for all users).

**Comment by tcharding** [comment]
Woops, got a bit trigger happy with my worktree delete command again.

**Review by apoelstra — APPROVED** [review]
ACK 07a529a13210c84dfb7afa253b71c6fb5d0dcb02 successfully ran local tests

**Comment by tcharding** [comment]
Merge, tag, and release please!

**Comment by apoelstra** [comment]
Tagged and published.

**Comment by tcharding** [comment]
BOOM! Thanks man.

**Pull request merged**
