### PR TITLE
Automated daily update to rustc (to nightly-2024-05-29)

### PR DESCRIPTION
**Pull request by apoelstra**
Automated update to Github CI workflow `rust.yml` by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by apoelstra** [comment]
Heh, we decide to slow down the nightly updates and the very next one is one that breaks.

This looks like it might take a bit to work out -- latest nightly appears to have completely broken `cfg`.

**Comment by apoelstra** [comment]
https://github.com/rust-lang/blog.rust-lang.org/pull/1313

**Comment by apoelstra** [comment]
```
### How to expect custom cfgs without a `build.rs`?

There is **currently no way** to expect a custom cfg other than with `cargo::rustc-check-cfg` in a `build.rs`.

Crate authors that don't want to use a `build.rs` are encouraged to use Cargo features instead.
```

Fucking hell.

**Comment by tcharding** [comment]
> Heh, we decide to slow down the nightly updates and the very next one is one that breaks.

Yeah I saw this yesterday and cursed not-so-quietly to myself.

**Review by tcharding — APPROVED** [review]
ACK 4137c5c7a268493738ab0e8a686e01681360219a

**Pull request merged**
