### PR TITLE
wrap u8 and LeafVersion in backticks and square bracket in doc

### PR DESCRIPTION
**Pull request by bruteforcecat**
Found this minor doc issue while reviewing(learning) previous merged PR.

Close https://github.com/rust-bitcoin/rust-bitcoin/issues/763

### CODE REVIEW

**Review by dr-orlovsky — APPROVED** [review]
ACK 9835736ef5b1fcdbf0ec2f2aa80835a607f89fae

**Comment by Kixunil** [comment]
ACK 9835736ef5b1fcdbf0ec2f2aa80835a607f89fae

thanks!

**Comment by dr-orlovsky** [comment]
@Kixunil you haven't actually used "Approve" GitHub button and this PR is still unmergable because of that

**Review by Kixunil — APPROVED** [review]
ACK 9835736ef5b1fcdbf0ec2f2aa80835a607f89fae

**Comment by Kixunil** [comment]
Should've drink coffee *before* work :D

**Comment by apoelstra** [comment]
Does the Bitcoin Core github merge script also insist that you use the "approve" button?

**Comment by RCasatta** [comment]
> Does the Bitcoin Core github merge script also insist that you use the "approve" button?

I can confirm the push is declined if there aren't 2 approve button clicks

**Pull request merged**
