### PR TITLE
Improve hex conversions

### PR DESCRIPTION
**Pull request by alekseysidorov**
- Replace deprecated `rustc_serialize::hex` by the `hex` crate.
 - Implement `FromStr` for the Sha256d type
 - Implement `FromStr` for the Script type

### CODE REVIEW

**Comment by tamasblummer** [comment]
LGTM, not yet approving as it introduces a new library dependency. Since rust-seralize is deprecated this hcould be considered as intermediate step, agree @TheBlueMatt ? @alekseysidorov would you volunteer to get rid of the remaining use of rustc-serialize in subsequent PRs ?

**Comment by alekseysidorov** [comment]
That is, I have to split following PR into two: first PR with the replacing deprecated serialize and second with the `FromStr` implementations?

**Comment by tamasblummer** [comment]
Yes, the two are somewhat unrelated, better be two PRs. It would be good to have a PR that gets rid of rustc-serialize completely, not just adding a specific alternative for hex coding. We'd like to limit the number of dependencies in this project.

**Comment by apoelstra** [comment]
I'd like to use a dedicated function for hex encoding rather than a dep here. I thought we had one in rust-secp256k1 or something?

**Pull request closed without merging**
