### PR TITLE
Hygiene/single code style for all existing macros

### PR DESCRIPTION
**Pull request by dr-orlovsky**
While being not really important, had to do hygiene of all internal macros (since many of which I re-use in other places) such they now follow the same standard/coding style for all namespace prefixes (i.e. starting with `::` followed by a fully-clarified name).

Also added doc strings to some of the macros

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
FYI, have figured out how the macro system works:

* use `::std` instead of `$crate::std`: works well both for internal macros and exported. If `$crate::std` is used, it will not work in exported macros (compiler error)
* use `$crate::core` instead of `::core` – and you also have to specify `pub crate core` in `lib.rs`. `::core` is not working with exported macros

**Comment by stevenroose** [comment]
Is it worth it to have all this verbosity for macros we don't export?

**Comment by dr-orlovsky** [comment]
What I am sure is that
1) it worth to stick to some defined coding style throughout the code and not switch its arbitrary even within a single macro;
2) be prepared that the code may be forked and maintained by other Bitcoin-related projects outside of the concept of "let's make another wallet [library]" which are not fixed on the idea of limiting their functionality to the set of predefined scripts etc. This means it would be nice to have a library prepared to export macros you don't aim to export now - just not to copy-paste its code into their projects.

**Comment by dr-orlovsky** [comment]
seems Travis needs reset

**Comment by stevenroose** [comment]
I restarted the timed out test.

**Comment by dr-orlovsky** [comment]
I have rebased this onto master. Pls let me know if there any need in this.

**Comment by elichai** [comment]
I'm for better macro hygiene, it will also ease our life when we will update to edition 2018.
it also reduces ambiguity if you have the same type defined under different modules

**Comment by stevenroose** [comment]
ack 257ca8e504bd40b4ed13563bc8157b4c843be1fd

**Pull request merged**
