### PR TITLE
bitcoin: Tracking PR for release `v0.31.0` 

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for release of v0.31.0 bump the version number.

The changelog is already up to date because we have done two RC releases.

### CODE REVIEW

**Comment by tcharding** [comment]
> We'll plan to re-tag and release this as 0.31.0 on Friday Oct 27, assuming nobody shows up with things we need to fix.

ref: https://github.com/rust-bitcoin/rust-bitcoin/pull/2124#issuecomment-1771000358

**Review by apoelstra — APPROVED** [review]
ACK f4eb71c743cd1d719d071191061b77df7064eb0e

**Review by clarkmoody — APPROVED** [review]
ACK f4eb71c743cd1d719d071191061b77df7064eb0e

**Review by vincenzopalazzo — APPROVED** [review]
ACK https://github.com/rust-bitcoin/rust-bitcoin/pull/2140/commits/f4eb71c743cd1d719d071191061b77df7064eb0e

**Review by Kixunil — APPROVED** [review]
ACK f4eb71c743cd1d719d071191061b77df7064eb0e

**Comment by tcharding** [comment]
We found a changelog bug, https://github.com/rust-bitcoin/rust-bitcoin/pull/2143 needs to merge before this can be considered.

**Comment by apoelstra** [comment]
I think the changelog bug is minor enough that we shouldn't do a whole rc over it.

I wouldn't mind cutting a release off of master though without a rc, which contains:
* #2126 (`Debug` code only)
* #2096 (test code only)
* #2143 (changelog only)

**Comment by tcharding** [comment]
Sweet as, rebased on master. No other changes.

**Review by Kixunil — APPROVED** [review]
ACK efedf862b07d83298858c452b3780f804fb7537c

**Comment by apoelstra** [comment]
Let's do it!

**Review by apoelstra — APPROVED** [review]
ACK efedf862b07d83298858c452b3780f804fb7537c

**Comment by apoelstra** [comment]
Tagged and published.

**Comment by junderw** [comment]
CI says: "too many PRs! No cookie for you!"

**Comment by junderw** [comment]
Error: Error 422: Validation Failed: {"resource":"Release","code":"custom","field":"body","message":"body is too long (maximum is 125000 characters)"}

**Pull request merged**
