### PR TITLE
Fixing serde impl for PSBT inputs

### PR DESCRIPTION
**Pull request by dr-orlovsky**

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
thanks! utack, pending CI

**Comment by apoelstra** [comment]
Looks like this was caused because #508 and #478 were merged at the same time

**Review by stevenroose — APPROVED** [review]

**Comment by stevenroose** [comment]
#508 wasn't merged, though. I don't think this obsoletes #508 either, right? But I should probably rebase that?

**Comment by apoelstra** [comment]
Yeah, I think I meant #507 and #478, which were merged at the same time, though it's not obvious to me looking back where the conflict was.

Agreed, rebasing #508 would be great :)

**Pull request merged**
