### PR TITLE
[backport #658] Check for overflow in Script::bytes_to_asm_fmt()

### PR DESCRIPTION
**Pull request by apoelstra**
Backport of #658

### CODE REVIEW

**Review by sanket1729 — APPROVED** [review]
ACK 6c3434c526e7b8607ff30b63b2ccd9ef8dbd9d82

**Comment by apoelstra** [comment]
You can confirm the commits have identical diffs using `git range-diff`. So I am also claiming that my ACK from #658 applies here.

ACK 6c3434c526e7b8607ff30b63b2ccd9ef8dbd9d82

**Comment by romanz** [comment]
Many thanks!

**Comment by Kixunil** [comment]
Thanks from me as well!

**Comment by apoelstra** [comment]
FYI we will probably do another point release in the next couple days to more thoroughly kill this bug (i.e. we'll add some i686 fuzztests for these functions and find the other overflows)

**Comment by Kixunil** [comment]
Great! Shame I couldn't get #662 to work with `no-panic` then fuzz tests wouldn't be needed.

**Pull request merged**
