### PR TITLE
Added Ord and Hash implementations for the Address type

### PR DESCRIPTION
**Pull request by alekseysidorov**

### CODE REVIEW

**Comment by tamasblummer** [comment]
@TheBlueMatt: seems like an issue with fuzz test build chain.  Ignore?

**Comment by apoelstra** [comment]
It's unclear to me how to read this fuzz error.
Is the hex stuff at the very bottom an input that fails to deserialize?

**Comment by tamasblummer** [comment]
I assumed this is a problem in the fuzz framework as:
SIGNAL: SIGABRT (6)
FAULT ADDRESS: (nil)
INSTRUCTION: cmp____$0xfffffffffffff000,%rax
does not sound like an error message on purpose

**Comment by TheBlueMatt** [comment]
Looks like to me its the bech32 bump that caused it, and its legitimate. For reference, yes, the stuff at the bottom is the hex of the input that caused the fuzz target to fail, you can paste that into the 4th-to-last line in the fuzz target and run cargo test from within fuzz/ and you should be able to reproduce the error.

**Comment by apoelstra** [comment]
@alekseysidorov can you rebase this? It looks like a very useful PR.

**Comment by alekseysidorov** [comment]
Okay

**Pull request merged**
