### PR TITLE
Migrate CI to GitHub actions

### PR DESCRIPTION
**Pull request by sgeisler**
This PR is a a minimal viable migration of our CI to GitHub actions. Since travis seems more and more broken and will discontinue the sevice as we know it anyway such a migration seems the best path forward. For now there's one known caveat to this PR: coverage reporting isn't integrated yet. This is mostly because it was broken on travis too (for the last 6 months) and needs some debugging.

EDIT: It doesn't seem to run here, but it [works on my branch](https://github.com/sgeisler/rust-bitcoin/actions/runs/456720056).

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you move the fuzz target from stable to nightly? I think we're more likely to find interesting stuff that way.

**Review by apoelstra — DISMISSED** [review]
tentative ACK. Not sure why these actions are not running.

**Review by stevenroose — DISMISSED** [review]
Let's try figure out why it doesn't run before merging, no?

**Comment by sgeisler** [comment]
I guess @apoelstra could check in the GH UI if he has to activate something. My guess is that it doesn't want to run untrusted CI scripts for fear of leaking some secrets?

**Comment by sgeisler** [comment]
I moved the fuzztests. Let's see [if it still runs](https://github.com/sgeisler/rust-bitcoin/runs/1640314395) first before merging.

**Comment by apoelstra** [comment]
Closing in favor of #544

**Pull request closed without merging**
