### PR TITLE
Pin `serde` to 1.0.142

### LINKED ISSUE #1175: Pin serde in tests
`serde` now uses `resolver` feature which isn't supported by our MSRV. Our CI breaks without pinning.

### PR DESCRIPTION
**Pull request by Kixunil**
1.0.143 bumps MSRV higher than what we support.

Closes #1175 

Unfortunately I have to go now, will try to get back ASAP.

### CODE REVIEW

**Comment by apoelstra** [comment]
Frustrating. We'll have to also put back the `README` blob telling users to do this.

**Comment by Kixunil** [comment]
Yes, but I'd rather merge this and #1177 ASAP to minimize the damage and worry about doc later.

**Review by apoelstra — APPROVED** [review]
ACK 75366eb6cb77b6769779d45e0a98512282615ad8

**Comment by Kixunil** [comment]
I have to run again, please re-run tests in #1177 if this is merged while I'm gone.

**Review by apoelstra — APPROVED** [review]
ACK 7a28a56ac464a2cd9e5da32ef933b5e324b6ae4d

**Review by tcharding — APPROVED** [review]
ACK 7a28a56ac464a2cd9e5da32ef933b5e324b6ae4d

**Comment by tcharding** [comment]
I'm a little bit confused. In [this CI run](https://github.com/rust-bitcoin/rust-bitcoin/runs/7758620633?check_suite_focus=true) the 1.41.1 test pass but not the 1.47.1 and I can run tests locally with `+1.41.1`. I see that its the `cargo tree` command that fails, but for some reason `cargo tree` does not accept a toolchain. What am I missing?

**Comment by Kixunil** [comment]
@tcharding regarding 1.41 vs 1.47 it's caused by (IMO not great) process of introducing changes to `cargo`. Unknown fields added to `Cargo.toml` are ignored, but if there's actually a new unstable feature using them they start causing errors and when it's stabilized they start work fine. So there's a weird hole where things don't work.

**Pull request merged**
