### PR TITLE
Update to secp256k1 0.13

### PR DESCRIPTION
**Pull request by jonasnick**

### CODE REVIEW

**Comment by apoelstra** [comment]
blocked until we have released other breaking changes

**Comment by jonasnick** [comment]
The travis rust 1.22 build always times out. Works locally on my machine...

**Comment by stevenroose** [comment]
Hmm... Our Elements Travis tests also time out when compiling secp256k1-zkp. Could that be related?

**Comment by jonasnick** [comment]
It turns out I was not able to reproduce this problem because I used a Cargo.lock that was created with a newer rustc.
If I start with a fresh clone of the repo I can reproduce the infinite loop.

This is a [bug in cargo 0.23.0](https://github.com/rust-lang/cargo/issues/4810).
rust-bitcoinconsensus 0.16.4 (the latest) is not compatible with this PR because cc is pinned to `=1.0.26`.
Newer rust versions are able to just use rust-bitcoinconsensus 0.16.3.
My hypothesis is that if we release a new version of rust-bitcoinconsus that is compatible we won't run into the infinite loop, but I don't see a way to test that locally.
I've opened PR https://github.com/rust-bitcoin/rust-bitcoinconsensus/pull/9 in rust-bitcoinconsensus which will hopefully resolve this problem once released.

**Comment by jonasnick** [comment]
Superseded by #298

**Pull request closed without merging**
