### PR TITLE
Update generic param

### PR DESCRIPTION
**Pull request by yancyribbens**
Use W for Write

closes https://github.com/rust-bitcoin/rust-bitcoin/issues/3590

### CODE REVIEW

**Comment by apoelstra** [comment]
If we're gonna rename the generic why not also rename the variable?

**Review by apoelstra — APPROVED** [review]
ACK 266efd6e87b7027c8684fd653fbc2d9d8d27a3c4; successfully ran local tests; sure

**Comment by tcharding** [comment]
nack, we definitely need to change the variable name to.

**Comment by yancyribbens** [comment]
var name updated as well

**Review by tcharding — APPROVED** [review]
ACK 3523b8e1171663fc93ab25765271a1070a2d649f

**Review by apoelstra — APPROVED** [review]
ACK 3523b8e1171663fc93ab25765271a1070a2d649f; successfully ran local tests

**Pull request merged**
