### PR TITLE
use u128 in map_to_range

### PR DESCRIPTION
**Pull request by RCasatta**

### CODE REVIEW

**Comment by elichai** [comment]
Does anyone understands what this is supposed to do? it was added in #281
from the one line comment it sounds like it is supposed to be like a modular operation, but they aren't equivalent

**Comment by RCasatta** [comment]
>  but they aren't equivalent

You mean the old function `map_to_range` and the "new" one using u128?

I think they are equivalent, except the old one is not checking adding overflow in the term `a * d + c * b + h(b * d)`

**Comment by elichai** [comment]
> You mean the old function `map_to_range` and the "new" one using u128?

No, I meant the modulo operation and this function, which makes me ask what exactly is this function trying to achieve :)

**Comment by RCasatta** [comment]
From the bip158

**Comment by dr-orlovsky** [comment]
Was this function test covered before? It seems to me that the new version uses different algo and may produce different result

**Comment by RCasatta** [comment]
Yes, it's covered by bip158 test vector.

I previously did some tests with random inputs and the functions are equal (apart from the add overflow bug I mentioned in the old one). I can commit those tests if requested

**Comment by elichai** [comment]
> From the [bip158](https://github.com/bitcoin/bips/blob/master/bip-0158.mediawiki)
> 
> > The 64-bit SipHash outputs are then mapped uniformly over the desired range by multiplying with F and taking the top 64 bits of the 128-bit result. This algorithm is a faster alternative to modulo reduction, as it avoids the expensive division operation [3]
> 
> > [3] https://lemire.me/blog/2016/06/27/a-fast-alternative-to-the-modulo-reduction/

Thanks! I'll read Lemire's post and then review this PR :)

**Review by apoelstra — DISMISSED** [review]
utACK. I'm convinced that these are equivalent.

**Comment by apoelstra** [comment]
BTW - this PR is not into `master`. Is that intentional?

**Comment by RCasatta** [comment]
It was intentional, to group MSRV updates, but it could go alone, now targeting master

**Review by apoelstra — APPROVED** [review]
actual utack

**Review by elichai — APPROVED** [review]
ACK
this matches the code from before, and matches lemire's post

**Pull request merged**
