### PR TITLE
Feature gate the p2p module

### PR DESCRIPTION
**Pull request by tcharding**
Most users will never touch the `p2p` module, we can feature gate the whole thing.

### CODE REVIEW

**Comment by apoelstra** [comment]
Looks like CI failure is real.

**Review by sanket1729 — COMMENTED** [review]
concept ACK

**Comment by tcharding** [comment]
Win, running `cargo test` with no default features is useful now that we got rid of "no-std".

**Review by apoelstra — APPROVED** [review]
ACK b68c24a00d01676e6360553f17ea0f8d73a586fe

**Comment by Kixunil** [comment]
Yes and no. This should be a separate crate. But that can only happen when `primities` is done.

**Comment by tcharding** [comment]
So is that a NACK from you @Kixunil? Otherwise this can merge.

**Comment by Kixunil** [comment]
I'm not really sure what this achieves. Future compatibility with moving stuff around a bit yes but that's not a strong motivation to me. If you can measure compilation speed with and without (beware of cold/hot cache) and you see a significant difference that would convince me. Or if you can provide some other reason.

**Pull request closed without merging**
