### PR TITLE
Decrease Huffman Weights to u32

### PR DESCRIPTION
**Pull request by JeremyRubin**
This builds on https://github.com/rust-bitcoin/rust-bitcoin/pull/699 but is the more bikesheddable part since it changes the API.

> u32 of weight should be enough for any branch.
-- Bill Gates

### CODE REVIEW

**Comment by JeremyRubin** [comment]
rebased :)

**Review by dr-orlovsky — APPROVED** [review]
utACK 1518517374985ed10f6d82a21b007554025079a4

**Comment by Kixunil** [comment]
Looks legit but I'd like someone more experienced with probabilities than myself to confirm this is a good idea.

**Comment by JeremyRubin** [comment]
@Kixunil basically this restricts our "fidelity" in expressing relative probabilities to maximally 4 billion to one, and introduces a possible "optimization glitch" when we have more than 4 billion branches all of maximal weight (well formedness still fine).

I think it's very unlikely that we need to express something as more than 4 billion times more likely very often -- i.e. if you think you might use a signing path once per second for lightning, you'd use the other path once every 126 years.

I don't think this patch is critical, but some folks may not like using u128s internally.

**Review by Kixunil — APPROVED** [review]
Sounds good!

ACK 1518517374985ed10f6d82a21b007554025079a4

**Comment by JeremyRubin** [comment]
yeah to be clear i personally don't think this patch is needed, so it's really up to others if they think it's needed.

**Comment by dr-orlovsky** [comment]
Merging, since it has two ACKs for some time already and is quite trivial

**Comment by JeremyRubin** [comment]
I would like a post-merge ack i think maybe from @sanket1729 and @apoelstra if possible.

This was a follow up because there was some dissent on my use of u128 in a previous PR.

 I know I authored it but i am neutral on this so i don't think the usual 2 acks works since usualy 2 acks is really 3, including the author's.

**Comment by apoelstra** [comment]
yep, concept ACK

**Pull request merged**
