### PR TITLE
Mark funtions const

### PR DESCRIPTION
**Pull request by yancyribbens**
May as well mark these const as well.  Follow up to https://github.com/rust-bitcoin/rust-bitcoin/pull/3605

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 4c94695942de41e5eca4ac120db2e069c0bb037d; successfully ran local tests; yeah, I think this are all worth consting

**Comment by tcharding** [comment]
Might as well do the whole code base in one go, right?

Everything returned by `git grep 'fn checked_'`

**Comment by tcharding** [comment]
This PR could be marked as part of #1174

**Comment by yancyribbens** [comment]
> Might as well do the whole code base in one go, right?

Finding them might be easy, although as you can see from this PR, there's many potential changes to make them work in const context.   There's also many that probably practically can't be evaluated during compile time.

**Comment by apoelstra** [comment]
> Might as well do the whole code base in one go, right?

I think I tried this once and quickly became overwhelmed. I think we should accept small changes.

**Comment by tcharding** [comment]
Sweet, works for me.

**Review by tcharding — APPROVED** [review]
ACK 4c94695942de41e5eca4ac120db2e069c0bb037d

**Review by sanket1729 — APPROVED** [review]
ACK 4c94695942de41e5eca4ac120db2e069c0bb037d

**Pull request merged**
