### PR TITLE
Improve BadFormat error

### PR DESCRIPTION
**Pull request by hashmap**
use static string instead of heap allocated one.

### CODE REVIEW

**Comment by Kixunil** [comment]
I'd prefer adding those as additional variants and handle it in `fmt` impl.

**Comment by tcharding** [comment]
Thanks for your contribution @hashmap. Is this PR still live or shall we close it?

**Comment by hashmap** [comment]
@tcharding I was waiting for a refactoring to happen in this file, lmc if it still makes sense, otherwise I'll close it

**Comment by hashmap** [comment]
closing in favor of https://github.com/rust-bitcoin/rust-bitcoin/pull/1651

**Pull request closed without merging**
