### PR TITLE
Automated daily update to rustc (to nightly-2024-04-28)

### PR DESCRIPTION
**Pull request by apoelstra**
Automated update to Github CI workflow `rust.yml` by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
ACK a60ce917c605334f0ffc09f0634df22f4edf77f4

**Comment by tcharding** [comment]
If CI is green I'm not doing anything other than copying the commit hash and acking, that feels like manual labour for no benefit. Is there a better process, can I just merge these PRs instead or do you want you local CI to check them over first?

**Comment by apoelstra** [comment]
@tcharding nope, go ahead and merge these yourself. Though I would prefer if you still went through the exercise of copy/pasting the git ID so it's at least clear that what you merge is the same as the diff you looked at.

And if my local CI breaks due to nightly that's fine, it's something I can fix locally. No need to hold up PRs over it.

**Comment by tcharding** [comment]
Yep sure thing, I'll review, ack, and run the merge script.

**Pull request merged**
