### PR TITLE
Move `base58` to the crate root

### PR DESCRIPTION
**Pull request by tcharding**
Move `base58` module to the carte root, direct `rustfmt` to not format the digits array. Run formatter as a separate patch.

### CODE REVIEW

**Comment by apoelstra** [comment]
This one, like #1400, should eventually go in `bitcoin-str`, so we should decide on a name and create a module.

**Comment by apoelstra** [comment]
@Kixunil let's move discussion of `bitcoin-str` here from 1400 so that we're not interleaving project discussion with workflow discussion *and* Connor's actual PR.

How do you feel about creating a module called `string`, which we'll later (after next release say) promote to a crate `bitcoin-string`. We'll put `base58` in there as well as Connor's new trait, and other things as we see fit. We'll also re-export bitcoin-bech32 from there.

**Comment by Kixunil** [comment]
For `base58` I'd prefer a separate crate.

`string` module sounds good as a facade but I'm not convinced it needs to be a crate.

**Comment by apoelstra** [comment]
Ok, if we want `base58` to be its own crate then we can move it to the root here. concept ACK (though needs rebase)

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — DISMISSED** [review]
ACK c12a17b6a754536569efcb3d090a072a14b52a01

**Review by Kixunil — DISMISSED** [review]
ACK c12a17b6a754536569efcb3d090a072a14b52a01

**Comment by apoelstra** [comment]
Needs rebase. (Tried localy, it's a real merge failure)

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK 4c8570b512ca15631871b89c3be4b227259bf2a0

**Review by sanket1729 — APPROVED** [review]
ACK 4c8570b512ca15631871b89c3be4b227259bf2a0

**Comment by sanket1729** [comment]
Merging this as it marked as high prio

**Pull request merged**
