### PR TITLE
Add automated labeler job

### PR DESCRIPTION
**Pull request by Kixunil**
Rather than modifying the labels manually, which we often forget, we can label the PRs automatically. This will make it easier to search PRs.

### CODE REVIEW

**Comment by Kixunil** [comment]
Looks like we have to blindly merge this. I tested what I could. :(

**Comment by Kixunil** [comment]
OK, looks like not really-entirely blindly. :)

**Comment by apoelstra** [comment]
> OK, looks like not really-entirely blindly. :)

Unsure what you mean by this. But I did read the code until I had convinced myself what it was supposed to do. Happy to merge and then we can iterate.

**Review by apoelstra — APPROVED** [review]
ACK c6c5f0788074bcc03c5b17bc81f49a04a204b1bd

**Comment by apoelstra** [comment]
Will wait for @tcharding to ACK so he knows what's up.

**Comment by Kixunil** [comment]
> > OK, looks like not really-entirely blindly. :)
> 
> Unsure what you mean by this. But I did read the code until I had convinced myself what it was supposed to do. Happy to merge and then we can iterate.

At first I thought there's no way to test it but then I found out there was something else broken, did a test that only failed to actually assign the labels because of permissions which I believe is good enough for now, then changed it to `pull_request_target`.

**Review by tcharding — APPROVED** [review]
ACK c6c5f0788074bcc03c5b17bc81f49a04a204b1bd

All the yml stuff looks ok to me but after reading this I'm unsure what exact labels get added.

**Comment by Kixunil** [comment]
@tcharding the script appends labels named `C-$crate` to the yaml config where `$crate` is pulled from `cargo metadata` and we exclude fuzz for now (we could add it if it's useful but I consider it `test` label)

**Comment by tcharding** [comment]
Ah, sweet. Thanks

**Pull request merged**
