### PR TITLE
api: Run just check-api

### PR DESCRIPTION
**Pull request by tcharding**
Some wombat queued 100 PRs up and is constantly breaking the api text files.

### CODE REVIEW

**Review by storopoli — APPROVED** [review]
ACK 7cd67786af2c504760c76713fa28c8372feaba99

**Review by sanket1729 — APPROVED** [review]
ACK 7cd67786af2c504760c76713fa28c8372feaba99

Should we make the API check non-blocking in github until we have 1.0? Maybe just warn for now

**Comment by storopoli** [comment]
> ACK [7cd6778](https://github.com/rust-bitcoin/rust-bitcoin/commit/7cd67786af2c504760c76713fa28c8372feaba99)
> 
> Should we make the API check non-blocking in github until we have 1.0? Maybe just warn for now

Either that or maybe toggle [GitHub's Merge Queue](https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-a-merge-queue)

**Comment by tcharding** [comment]
Re-based and re-ran because more changes to the api files have gone in.

**Comment by tcharding** [comment]
Can you put this one when you get a chance please @apoelstra, I'll keep an eye open and rebase everything else I have open then so we can get back to a clean slate.

**Review by apoelstra — APPROVED** [review]
ACK 7cd67786af2c504760c76713fa28c8372feaba99; successfully ran local tests

**Review by apoelstra — APPROVED** [review]
ACK f412f2b149b73f6030fdd5565b3d5f920512f477; successfully ran local tests

**Pull request merged**
