### PR TITLE
util: Remove contracthash module

### LINKED ISSUE #322: contracthash module needs to be deprecated (or removed)
This is buggy and incomplete and its purpose is better served by rust-miniscript.

### PR DESCRIPTION
**Pull request by dongcarl**
Closes #322

### CODE REVIEW

**Comment by stevenroose** [comment]
Also remove its mention from the README then.

**Comment by apoelstra** [comment]
Steven points out that I need to update rust-miniscript to add the key-tweaking functions

**Comment by apoelstra** [comment]
I think rust-miniscript is pretty much good to go; I have an issue here: https://github.com/apoelstra/rust-miniscript/issues/61 about cleaning up the README and adding a changelog before bringing it under the org. I don't think there's anything more you need to wait for (though take a look at the open issues for lists of missing features).

I've been using it internally at Blockstream for over a year, and in some of my one-off chain-scanning projects.

**Comment by apoelstra** [comment]
(Abusing the "request changes" option to block this PR for a bit.)

**Comment by dongcarl** [comment]
> Also remove its mention from the README then.

Done, thanks!

**Comment by apoelstra** [comment]
Needs rebase since we deprecated `contracthash`; still blocked on rust-miniscript support for keytweaking.

**Comment by sanket1729** [comment]
Do we really want to remove this? I think this module should be updated for taproot tweak support? Or does it belong in `rust-miniscript` and not in `rust-bitcoin`?

**Comment by apoelstra** [comment]
@sanket1729 the module is broken in ways that I no longer remember, the API is from 2014, the form of tweaking that it does is needlessly more complicated than Taproot (although this scheme is in Liquid consensus code so it needs to live on in Liquid/rust-elements at least..), and it uses normal keys rather than Schnorr ones.

I think we should drop this module from rust-bitcoin and probably move the Liquid-specific stuff (the nonbroken parts) into rust-elements.

Originally I had intended to move this into rust-miniscript, because I imagined people doing general pay-to-contract constructions, but now I think such users would be better-served basing their code off of Taproot rather than this.

**Comment by dr-orlovsky** [comment]
Superceded by #871

**Pull request closed without merging**
