### PR TITLE
doc: correct Transaction struct encode_signing_data_to doc comment

### PR DESCRIPTION
**Pull request by collinsmuriuki**
Small fix to a small issue I noticed

### CODE REVIEW

**Review by sgeisler — APPROVED** [review]
Thank you for the fix! :)

**Review by stevenroose — APPROVED** [review]
ACK

**Comment by stevenroose** [comment]
Will have to be rebased after https://github.com/rust-bitcoin/rust-bitcoin/pull/583 is merged probably.

**Review by dr-orlovsky — APPROVED** [review]

**Review by sanket1729 — APPROVED** [review]

**Review by elichai — APPROVED** [review]
ACK. 
Tested that it produces the correct docs

**Comment by sgeisler** [comment]
just kick CI to use the new config

**Pull request merged**
