### PR TITLE
Fix `Uint256::increment` panics

### PR DESCRIPTION
**Pull request by TheBlueMatt**
This is #578 with review feedback addressed.

### CODE REVIEW

**Review by sgeisler — DISMISSED** [review]
utACK 9c256cc88e4b71f7ee4e486a10b0be26c31a5f66

EDIT: Why did we choose little-endian btw? Was hard to wrap my mind around the resulting mixed-endianess.

**Review by dr-orlovsky — COMMENTED** [review]
Frankly speaking, to be rust ideomatic, we should have `inc` function panic on overflows, and special `wrapping_inc`, `checked_inc` and `overflowing_inc` and `saturating_inc` functions... But we are not numeric crate, so the question is why we need this `increment` function at all? Shouldn't we implement those methods on `UInt*` types and just use appropriate `*_add(1)` for do the incrementing?

**Comment by dr-orlovsky** [comment]
Personally I had to update/extend current UInt* implementations in https://docs.rs/amplify_num/0.1.1/amplify_num/ crate, and did all those arithmetic methods there, so they can be taken from it if needed here (or just use it since it is MSRV compatible)

**Review by sanket1729 — DISMISSED** [review]
Ack 9c256cc88e4b71f7ee4e486a10b0be26c31a5f66
Unrelated to this PR and also does not affect the correctness of the fuzzer, but while reviewing I found this line to be slightly confusing. I think it should be 

> if data.len() != 16*2 { return; }

But since the +1 is explicitly added, I maybe also be misunderstanding the code. 

I think it should 
https://github.com/TheBlueMatt/rust-bitcoin/blob/9c256cc88e4b71f7ee4e486a10b0be26c31a5f66/fuzz/fuzz_targets/uint128_fuzz.rs#L30

**Comment by TheBlueMatt** [comment]
> Unrelated to this PR and also does not affect the correctness of the fuzzer, but while reviewing I found this line to be slightly confusing. I think it should be

Yep! Totally right. That's just stale against a (probably never upstreamed) version of that fuzz target.

**Review by apoelstra — APPROVED** [review]
ACK 5d71a9dd896808a45aaea684b8636af319eafb41

**Review by sanket1729 — APPROVED** [review]
ACK 5d71a9d

**Pull request merged**
