### PR TITLE
Format with latest rustfmt (0.99.1-stable)

### PR DESCRIPTION
**Pull request by bodymindarts**
Investigating the code base I noticed some dirty files that came from my editor
running `cargo fmt` automatically on save so I've commited the project formatted
by the latest rustfmt.

### CODE REVIEW

**Comment by apoelstra** [comment]
Please remove the 22-file format-only commit from this PR.

**Comment by bodymindarts** [comment]
@apoelstra I've rebased and removed that commit. Though I don't really understand the intention, at some point that diff is going to be added. If not in 1 big bang then step by step as ppl edit files and format them or?

**Comment by apoelstra** [comment]
It can be added when/if rustfmt ever stabilizes.

**Comment by apoelstra** [comment]
My understanding at the beginning of this thread was that an empty rustfmt file would tell auto-rustfmt tools to not enforce any rules. Is that correct?

**Comment by dpc** [comment]
Empty `rustfmt` file would tell auto-rustfmt tools to use default values, and possibly encourage using these tools.

**Comment by dongcarl** [comment]
I believe that it would be better to turn off all rules, and, over time, explicitly add rules as we agree on which ones are needed.

**Comment by dpc** [comment]
What is there to agree on? Rust has a defined standard formatting style. 

Frankly, I think it was a mistake to even have any configuration. It opens the door for C++ madness to slowly creep into Rust ecosystem, where everyone has their own opinion when do closing parenthesis go, and some projects use tabs and some spaces, camel case, etc. because "screw everyone, it's my project, and I like mine settings better than some stupid standard". `rustfmt` having configuration options for style is just additional work and complexity for the whole purpose of people be able to screw everybody else.

I eg. prefer tabs over spaces, but what's decided is decided, I have my editor set to spaces in `*.rs` and I format all my projects with plain `rustfmt` and I worry about real problems, and not trivialities. But dev community is just a bunch of [disagreeable](https://en.wikipedia.org/wiki/Big_Five_personality_traits) people, and they will never agree on anything, especially if it's trivial and actually insignificant, so I guess soon I will have to switching tabs and spaces in Rust too.

**Comment by sgeisler** [comment]
They seem to have released [version `1.0.0`](https://crates.io/crates/rustfmt-nightly) recently. I don't know how stable it actually is, but they write that only macros and some other obscure cases will be unstable. 

If wanted to use `rustfmt` I'd argue for a big-bang transition (even though it messes up `git blame`) and CI enforced formatting afterwards. For that to work we should define a fixed version of `rustfmt` to use for `rust-bitcoin` (the organization) and only change it when absolutely necessary. That would solve most of the instability issues (just not using new `rustfmt` versions). And some noise in form of a formatting PR every one or two years maybe doesn't sound too bad to me.

If we don't want `rustfmt` yet because of possible instabilities I'd like to close this PR (it doesn't do much anyway) and use #172 to track the stabilization progress of `rustfmt` instead.

**Comment by apoelstra** [comment]
I think it's fine to do a big-bang transition with rustfmt 1.0.0.

**Comment by apoelstra** [comment]
@bodymindarts would you like to redo this PR with rustfmt 1.0? Or should one of us take that on?

**Comment by dongcarl** [comment]
Closing due to inactivity. Leaving the issue #172 open.

**Pull request closed without merging**
