### PR TITLE
Add support for SHA384

### LINKED ISSUE #2483: SHA384
I have a not-particularly-bitcoin-specific usecase for SHA256/384/512 (DNSSEC validation), and was gonna just use bitcoin_hashes, but turns out it doesn't do 384. Given its ~0 additional code compared to 512/512-256, would folks be okay with adding it?

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Based on #2473 as we need support for 48-byte arrays <-> hex conversions.

Closes #2483

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
ACK b3a7c1464e1b89cf9e97db86280de6b3e9d3d234

**Comment by tcharding** [comment]
If you were to ack #2473 @TheBlueMatt we could get it in, @Kixunil is MIA.

**Review by Kixunil — COMMENTED** [review]
The last commit looks good.

**Comment by tcharding** [comment]
Can now be rebased, #2473 is in.

**Review by Kixunil — APPROVED** [review]
ACK 4e3bb7350af7a6a2789ef007ac06307ba0c54ffe

**Review by sanket1729 — APPROVED** [review]
ACK 4e3bb7350af7a6a2789ef007ac06307ba0c54ffe

**Pull request merged**
