### PR TITLE
Flesh out hex unit parsing API

### PR DESCRIPTION
**Pull request by tcharding**
Add to `units::parse` the complete suit of hex unit parsing functions:

- remove prefix
- assert without prefix
- parse with or without prefix
- parse with prefix
- parse without prefix
- parse prefix unchecked

Refactor `bitcoin` to use the exact function we need, removing code duplication.

This is a breaking change to `units`, it does however keep the current re-exports from the public, now empty, `bitcoin::error` module.

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you:

* Rename `hex_assert_prefixed` to `hex_check_prefixed` (same for `hex_assert_unprefixed`)
* Add a commit which drops the re-exported errors from rust-bitcoin. I think these are useful for simplifying the diff but probably shouldn't be in the final API.

Otherwise c5bc6e85ec91668d0e95e640e5d0bed850fc7b65 looks great!

**Comment by tcharding** [comment]
Done as suggested, also improved the docs on all the hex functions.

**Review by apoelstra — DISMISSED** [review]
ACK 805c634468ac191dd59dcaec017cf77566b865c8

**Comment by tcharding** [comment]
No changes, rebase only (was wanting to rebase #2770).

**Review by apoelstra — APPROVED** [review]
ACK cf3e1eb198413a2a0ad80f15b8a1bf98ea52b4e0

**Pull request merged**
