### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by calciumbe**
base58: fix typo
bitcoin: fix typo
chacha20_poly1305: fix typo
hashes: fix typo
units: fix typo

### CODE REVIEW

**Review by storopoli — APPROVED** [review]
ACK 589dd025df938da3efac277511836cda5c53aa06

Nice catches!

**Review by AumGupta — APPROVED** [review]
Good to go

**Comment by dpc** [comment]
BTW. https://github.com/crate-ci/typos

**Review by tcharding — APPROVED** [review]
ACK 589dd025df938da3efac277511836cda5c53aa06

**Comment by tcharding** [comment]
Thanks!

**Review by apoelstra — APPROVED** [review]
ACK 589dd025df938da3efac277511836cda5c53aa06; successfully ran local tests; thanks!

**Pull request merged**
