### PR TITLE
util::amount: Make from_sat constructor constant

### PR DESCRIPTION
**Pull request by stevenroose**
Currently unmergable because of MSRV but I heard talk about bumping it, so once it's bumped, this is a very much needed change :)

### CODE REVIEW

**Comment by tcharding** [comment]
Should we consider making all the basic conversion methods `const` (i.e., across the whole crate/stack)?

**Review by tcharding — APPROVED** [review]
ACK 31571cafbdc161ad3cc23e7bd6e52f242b03f055

**Comment by apoelstra** [comment]
Why are there now no CI checks?

**Comment by apoelstra** [comment]
Merged #964 .. hopefully that wakes up github and it reinstates all the actions?

**Review by apoelstra — APPROVED** [review]
ACK 31571cafbdc161ad3cc23e7bd6e52f242b03f055

I ran my local CI script and this seems pretty clearly unlikely to cause any breakage ... let's just merge it?

**Comment by tcharding** [comment]
lol, GitHub. Yeah let's merge, yolo!

**Pull request merged**
