### PR TITLE
Extension trait for `Script`

### LINKED ISSUE #3161: Stop using `self: Self`
After #3155 merges we can stop using `self: Self` and friends in the `define_extension_trait` macro.

### PR DESCRIPTION
**Pull request by Kixunil**
This moves methods from `Script` to extension traits in steps that should be easy to follow.

Moving to `primitives` requires doing the same with `ScriptBuf` so I'm holding off until this approach gets concept ACK (or alternatively someone else can do it :))

Closes #3161

### CODE REVIEW

**Comment by tcharding** [comment]
Works for me! Thanks for playing with this, I like it. I can copy your style and keep pushing forward with `ScriptBuf`.

ACK a5186146c2b432b7895e0430c42feef84b2c5731

**Comment by Kixunil** [comment]
I'm just about to go sleep so feel free to work on top of this if you want.

**Comment by tcharding** [comment]
I'm on light duties this week so not sure when I'll get to it but if I don't see a PR from you then I'll hack one up. I can ping you if/when I start working so you don't start and find a PR pushed up right under you :)

**Comment by Kixunil** [comment]
I'm thinking of prioritizing `push_decode` since it's my area of expertise even though it might make moving `primitives` take longer. WDYT?

**Comment by tcharding** [comment]
Go for it, I can chug away at `primitives`, I"ll work around you, lets get push decoding done.

**Comment by apoelstra** [comment]
Looks like there is a clippy lint against `self: &Self` that we need to whitelist.

**Comment by Kixunil** [comment]
@apoelstra after my changes we can just use `&self` again.

**Comment by tcharding** [comment]
Woops, I raised #3161 but I guess we should do it as part of 3ef05a2e823f2b507e665042e9191104933d3633

**Review by tcharding — DISMISSED** [review]

**Comment by Kixunil** [comment]
@tcharding done.

**Review by tcharding — APPROVED** [review]
ACK 08576976650f93912dbd568653c26911bcc9a69e

**Comment by tcharding** [comment]
Thanks man, we are getting somewhere now.

**Review by apoelstra — APPROVED** [review]
ACK 08576976650f93912dbd568653c26911bcc9a69e successfully ran local tests

**Pull request merged**
