### PR TITLE
 Correct consensus verify args, fix tests to catch error in travis

### PR DESCRIPTION
**Pull request by TheBlueMatt**
Ping @tamasblummer.

### CODE REVIEW

**Comment by tamasblummer** [comment]
ack

**Comment by TheBlueMatt** [comment]
Blocked on https://github.com/rust-bitcoin/rust-bitcoinconsensus/pull/1

**Comment by tamasblummer** [comment]
published bitcoinconsensus 0.16.2-0.16.0
Note that in Cargo.toml:
bitcoinconsensus = { version = "0.16", optional=true }
still resolves to 0.16.1
had to force with 
bitcoinconsensus = { version = "0.16.2-0.16.0", optional=true }
to use the new version

**Comment by TheBlueMatt** [comment]
Blocked on https://github.com/rust-bitcoin/rust-bitcoinconsensus/pull/2

**Comment by tamasblummer** [comment]
published 0.16.2

**Pull request merged**
