### PR TITLE
Rename Siphash::as_u64 to Siphash::to_u64

### LINKED ISSUE #3114: Rename `SIphash::as_u64` to `Siphash::to_u64`
The method doesn't return a reference.

### PR DESCRIPTION
**Pull request by shinghim**
Resolves #3114

### CODE REVIEW

**Review by Kixunil — APPROVED** [review]
ACK 5a91719755f3d57ac64a3c44d2285e11a8245d78

**Review by apoelstra — APPROVED** [review]
ACK 5a91719755f3d57ac64a3c44d2285e11a8245d78 successfully ran local tests

**Comment by tcharding** [comment]
Just flagging that we may want to look at all the breaking changes we have made right before we release and re-add deprecated things back in. We really really do not want a repeat of the `rust-bitcoin` `v0.29` to `v0.30` upgrade hell that we created.

However, ACK 5a91719755f3d57ac64a3c44d2285e11a8245d78

**Comment by apoelstra** [comment]
Yeah, this one we probably should've just required a deprecation before approving. It was an obscure enough corner of the library that I let it slide, but it's not like a deprecation would've been difficult.

**Pull request merged**
