### PR TITLE
Favour `to_vec` over `to_bytes`

### PR DESCRIPTION
**Pull request by tcharding**
Use `to_vec` and deprecate `to_bytes`, the opposite of what we did in #2585.

For functions that return a `Vec` by first allocating use function name `to_vec`. This explicitly excludes:

- Functions that return an array (`CompressedPublicKey::to_bytes`)
- Functions that consume self and return a `Vec` without allocating (`ScriptBuf::into_bytes`)

See #3025 for discussion and consensus. 

Close: #3025

### CODE REVIEW

**Comment by yancyribbens** [comment]
Thanks, `to_vec` is a better name I think, and I didn't want to fix the deprecation warnings for `to_bytes`.  I thought we could just revert the commit instead of requiring a deprecation cycle.  I guess it's been too long by now to revert the commit.

**Comment by apoelstra** [comment]
In f875f28e621bb8dd49493dab47463669b75ff34c:

You say 'since = "0.33.0"` but probably the actual version will be 0.32.5 and/or 0.33.0-alpha.0. Better to just put TBD here.

**Comment by apoelstra** [comment]
Ditto in 5d695ead7a74f1984528e36d57e6c50a8afb292b

**Comment by apoelstra** [comment]
And 6671f38df370aa7a3c93e5940cd24bab7f826222.

Otherwise 6671f38df370aa7a3c93e5940cd24bab7f826222 looks good.

**Review by apoelstra — APPROVED** [review]
ACK a51768af3f3d4c8e138e1ded250800810bedc903; successfully ran local tests

**Pull request merged**
