### PR TITLE
Add encode::serialized_len global method

### PR DESCRIPTION
**Pull request by stevenroose**
Relevant: #266.

With https://github.com/rust-bitcoin/rust-bitcoin/issues/263 this could be even more trivial, just a sink and returning the return value. I can give https://github.com/rust-bitcoin/rust-bitcoin/issues/263 a shot next weekend.

### CODE REVIEW

**Comment by apoelstra** [comment]
Doesn't #265 do this?

**Comment by dpc** [comment]
> Do you know the performance penalty that actually encoding the object causes?

I would be surprised if with `--release` and `-C lto` there's any difference between all these proposed methods. Seems to me like all of them are trivially optimizable by just dead-code elimination, as long as they don't have side effects (which should always be the case for encoding). I would be very interested in seeing a benchmark. :)

**Comment by stevenroose** [comment]
> Do you know the performance penalty that actually encoding the object causes?
> 
> I need something similar for allocationless encoding of lightning invoices. For that I intend to use the recursively _calculated_ length. Would that be possible too here by e.g. giving the `Encodable` trait an `encoded_len(&self) -> usize` function that just calculates the resulting size.
> 
> That _seems_ to be more efficient if it works (idk if we have some weird encoding algorithms for keys/sigs that are easier to execute than to calculate the output length for).

That doesn't work without requiring implementers to provide that method. The reason is that the impl of Encodable is generic over an Encoder so you can't use the impl you're defining with another type of encoder, like a counting one. (I tried that at first.)

> I would be surprised if with --release and -C lto there's any difference between all these proposed methods. Seems to me like all of them are trivially optimizable by just dead-code elimination, as long as they don't have side effects (which should always be the case for encoding). I would be very interested in seeing a benchmark. :)

You're saying that if you just use an allocating encoder and the compiler notices the allocated data wouldn't be used, it wouldn't actually allocate it? That's quite possible. But still it'd be worth having a helper method that actually does that for you without having to create a new `Vec` and invode serialize.

> Doesn't #265 do this?

Yeah with #265 you could just have a sink writer (`io::sink()`?) and return the return value of `consensus_encode`. In that case, this helper method is probably not worth it to have.

I think in that case this would work:

```rust
let tx = Transaction { ... };
let len = tx.consensus_encode(&mut io::sink()).unwrap();
```

So yeah I think this PR can be closed with #265.

**Comment by apoelstra** [comment]
Closing in favor of #265. Good call that `io::sink` is already available as a dummy encoder.

**Pull request closed without merging**
