### PR TITLE
Separate out merge method into public trait

### PR DESCRIPTION
**Pull request by tcharding**
Recently we (*cough* Tobin) made the `Map` trait private and neglected
to add a public API for merging together two PSBTs. Doing so broke the
`psbt` module.

Add a public trait `Merge` and implement it for
`PartiallySignedTransaction` using the code currently in the `merge`
method of the now private `Map` trait.

Motivated by https://github.com/rust-bitcoin/rust-bitcoin/pull/841

### CODE REVIEW

**Comment by Kixunil** [comment]
What is the reason this is a trait and not inherent methods? Do people generally need to abstract over merging different items?

**Comment by JeremyRubin** [comment]
I think it makes sense to have it as a trait, but I would envision the trait to be something more like Add.
```rust
trait Merge<With> {
    fn merge(&mut self, other: With) -> Result<(), Error>;
}
```

So that we might be able to define more structured Merging (e.g., merge raw tx into PSBT, PSBT V1 into V2 but not V2 into V1, etc).


However this is likely overkill v.s. as @Kixunil points out, an inherent method for it (which can also just be a wrapper around the Map type).

**Comment by Kixunil** [comment]
@JeremyRubin if someone actually has need for that (which I won't believe until I see an actual real-life example of code abstractly working on those types) then we can add `With` backward-compatibly by defaulting it to `Self`.

**Comment by apoelstra** [comment]
Seconding "let's make this an intrinsic method".

Also, I'd like to call it `combine` instead of `merge`.

**Comment by tcharding** [comment]
Updated PR as suggested:

- Used 'combine' instead of 'merge', this makes the diff a bit bigger to change a bunch of identifiers that use 'merge'.
- Implemented methods directly on the types instead of a trait.

**Comment by JeremyRubin** [comment]
i'm kinda meh on changing the name from merge / combine since it's a breaking change for no great reason.

Can you add a deprecated wrapper around combine called merge? We can then remove it after a release or two...

**Comment by apoelstra** [comment]
The old name was confusing and inconsistent with PSBT terminology, which is how it got deleted originally without anybody raising their eyebrows.

But yes, we should put a deprecated wrapper around it.

**Comment by tcharding** [comment]
I don't think we can deprecate it because the API break was making `Map` private. We can't use deprecate on that change. Unless I"m missing something?

**Comment by tcharding** [comment]
If we really want to use deprecate we could make `Map` public again then add deprecate massage to each of the trait methods individually then make `Map` private after another release? Seems like a lot of hooh-hah considering the taproot release is so massively breaking anyways.

**Comment by apoelstra** [comment]
Ah, ok, sounds good.

If the `merge` method was actually just part of the `Map` trait, which made no sense from an API perspective anyway, I'm fine dropping it without ta deprecation.

**Review by apoelstra — APPROVED** [review]
ACK 5e2449922db4a4ebf5550bd55151ac37af6e3225

**Comment by JeremyRubin** [comment]
My point was that you can add an inherent method names merge that is the
same as combine, not make map a public trait

**Comment by apoelstra** [comment]
@JeremyRubin it would be weird to add a new deprecated method that didn't exist before, even if it had the same name as a  method on a deleted trait.

**Comment by Kixunil** [comment]
Yeah, users would still get failure on non-existing trait.

**Comment by JeremyRubin** [comment]
ah it _used_ to exist as an inherent in 0.26 https://docs.rs/bitcoin/0.26.2/bitcoin/util/psbt/struct.PartiallySignedTransaction.html#method.merge, i guess in 0.27 it was moved to the trait, I wasn't sure when the refactor to Map was (altho it looks like it was a part of 0.27)

**Comment by apoelstra** [comment]
Lol, given that it existed in 0.26 I actually wouldn't mind re-adding and deprecating it now. But I would mildly prefer not to.

**Comment by JeremyRubin** [comment]
whatever works!

**Pull request merged**
