### PR TITLE
Clean up import aliases

### PR DESCRIPTION
**Pull request by tcharding**
Three trivial clean ups of import aliases.

### CODE REVIEW

**Comment by Kixunil** [comment]
Possibly better to remove the deprecated stuff?

**Review by apoelstra — APPROVED** [review]
ACK 7307363c2ec06f5b8d81d4ba595c2a944e6e5ba8

**Comment by tcharding** [comment]
> Possibly better to remove the deprecated stuff?

Can you clarify please mate, I'm not following you?

**Review by sanket1729 — APPROVED** [review]
ACK 7307363c2ec06f5b8d81d4ba595c2a944e6e5ba8. These are clean improvements

**Comment by sanket1729** [comment]
I think KixUnil is suggesting that we remove the deprecated stuff altogether since we have allowed users 1 major version to update. I don't know what should be an ideal deprecation cycle? 

Maybe one major release is too soon? On another hand, we do a lot of breaking changes, so cleaning up this code is perhaps better. My vote is to remove the deprecated stuff, but it's not a strong preference

**Comment by tcharding** [comment]
> Can you clarify please mate, I'm not following you?

Face palm, the 'deprecated' line _immediately_ above  my changes.

I believe we agreed on deprecation for at least one release but since we _may_ be pushing an MSRV release super fast perhaps we leave the 'deprecated since 0.28' in for an extra one?

**Comment by sanket1729** [comment]
> I believe we agreed on deprecation for at least one release but since we may be pushing an MSRV release super fast perhaps we leave the 'deprecated since 0.28' in for an extra one?

Agreed.

**Pull request merged**
