### PR TITLE
test: Add a test for incorrect message signature in `is_signed_by_address`

### PR DESCRIPTION
**Pull request by Shatnerz**
In response to this comment: https://github.com/rust-bitcoin/rust-bitcoin/pull/819#discussion_r801477961

This should be straightforward. Let me know if there are any style issues. I tried to keep things similar to the existing test while cutting out any extra cruft to keep things small.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK e391ce9939de1a9954f37a0da1e3afa5227cfae3

**Review by Kixunil — APPROVED** [review]
ACK e391ce9939de1a9954f37a0da1e3afa5227cfae3

I think it'd be nice to have another test that has a correct signature for correct message but *the address* is different. This would protect us if someone refactors the code and forgets to check the address. I actually experienced something similar in unrelated cryptographic code and it's also a bit similar to the fraud faketoshi attempted.

**Comment by Shatnerz** [comment]
> I think it'd be nice to have another test that has a correct signature for correct message but _the address_ is different. This would protect us if someone refactors the code and forgets to check the address. I actually experienced something similar in unrelated cryptographic code and it's also a bit similar to the fraud faketoshi attempted.

@Kixunil Is that not what the existing test is doing (not this PR)?

```
let p2wpkh = ::Address::p2wpkh(&pubkey, ::Network::Bitcoin).unwrap();
assert_eq!(signature2.is_signed_by_address(&secp, &p2wpkh, msg_hash), Ok(false));
let p2shwpkh = ::Address::p2shwpkh(&pubkey, ::Network::Bitcoin).unwrap();
assert_eq!(signature2.is_signed_by_address(&secp, &p2shwpkh, msg_hash), Ok(false));
```
P2WPKH and P2SH_P2WPKH address are derived from the same key, but they fail due to only P2PKH being supported.

I'm not sure what other ways the addresses could be different. The network could be different but it should always pass with the same pubkey. I don't think I understand what you are trying to get at.

**Comment by apoelstra** [comment]
There is no difference between "valid signature with wrong message" and "invalid signature", assuming the siganture is formatted correctly.

**Comment by apoelstra** [comment]
Yes.

**Review by dr-orlovsky — APPROVED** [review]
ACK e391ce9939de1a9954f37a0da1e3afa5227cfae3

**Pull request merged**
