### PR TITLE
Remove Amount::fmt_value_in

### LINKED ISSUE #2952: Remove `Amount::fmt_value_in`
This method can now be replaced by `display_in`, which also supports non-default formatting options. This would also allow us removing `Default for FormatterOptions` hopefully preventing formatting issues.

### PR DESCRIPTION
**Pull request by shinghim**
Saw this mentioned in #3556 

Fixes #2952

### CODE REVIEW

**Comment by tcharding** [comment]
lol, you managed to put up PRs #3621 and #3612 (note the last two digits), I got mildly confused.

**Comment by tcharding** [comment]
I created this discussion to see if we want to merge this: https://github.com/rust-bitcoin/rust-bitcoin/discussions/3622

**Comment by apoelstra** [comment]
Yeah, I think it's reasonable to just delete things on master and deprecate them in 0.32.x.

**Review by apoelstra — APPROVED** [review]
ACK 0348801ef30d1cdfdc40cd2316671532d4c06141; successfully ran local tests

**Comment by tcharding** [comment]
> Yeah, I think it's reasonable to just delete things on master and deprecate them in 0.32.x.

Before anyone goes and deletes _all_ deprecated code, this comment is referring to deprecated code in leaf crates (those soon to be 1.0 e.g, `units`) not in `bitcoin` crate. Holla if I'm wrong @apoelstra

**Review by tcharding — APPROVED** [review]
ACK 0348801ef30d1cdfdc40cd2316671532d4c06141

**Comment by apoelstra** [comment]
Yeah, agreed -- we do expect to have more pre-1.0 `bitcoin` releases so we should keep stuff around in those.

**Pull request merged**
