### PR TITLE
Refactor `consensus` module

### PR DESCRIPTION
**Pull request by tcharding**
Includes #2203

All patches with brief commit logs starting with `Move ...` are simple code moves.

The purpose of this PR, which can be seen by just reviewing the last patch, is to enable usage of:
- `consensus::serialize`, `consensus::deserialize`, etc. instead of `encode::deserialize`
- `decode::Error` instead of `encode::Error` as error return type of `consensus_decode`

### CODE REVIEW

**Comment by tcharding** [comment]
The consensus traits are the root cause of our `io` dramas (re core2/no-std) as well. I don't have hard evidence but I have a feeling it would be better to wrap the `io::Error` instead of returning it - then no matter what we do it will be easier. So this PR has quite a few potential benefits IMO.

**Comment by Kixunil** [comment]
> The consensus traits are the root cause of our `io` dramas (re core2/no-std) as well.

Indeed.



> because the consensus traits are so widely used.

That's precisely why I recommend waiting for the other part. It's so widely different that if it's accepted it will lead to *another* super-massive refactor.

**Comment by tcharding** [comment]
> That's precisely why I recommend waiting for the other part. 

I'm not sure which thing you are referring to, can you link please.

**Comment by Kixunil** [comment]
It wasn't released yet, I finally did: https://docs.rs/push_decode/latest/push_decode/ There's still a bunch of things to resolve but the general idea should be there.

**Comment by tcharding** [comment]
The rebase of this is too hard, but I like the result `consensus::deserialize`, `decode::Error` etc. 

@apoelstra does this get a concept ack or nack from you - if concept ack I'll redo the whole thing.

**Comment by apoelstra** [comment]
concept ACK for sure. But if possible can you split the new PR into more commits?

**Comment by tcharding** [comment]
Yep of course, thanks.

**Comment by tcharding** [comment]
Will go back over this and fix my mistakes with fresh eyes.

**Comment by tcharding** [comment]
Note to self, do not touch this PR again untill #2066 resolves.

**Comment by apoelstra** [comment]
I kinda think we should re-export everything from `consensus` and make the `encode`/`decode` modules private.

**Comment by tcharding** [comment]
Then one cannot write `decode::Error`, is `consensus::Error` as good. In my opinion it is slightly less descriptive because but not ambiguous because there is no `encode::Error`. What do you rekon?

**Comment by apoelstra** [comment]
Unsure. I think I prefer `consensus::Error` ... it is true that there is no `encode::Error` but I think there used to be one (but we replaced it with `io::Error`) and it wouldn't surprise me if there was one again.

**Comment by apoelstra** [comment]
I think it's fine if the user is using the `consensus::ReadExt` trait whose methods return a `consensus::Error`, and if the user never sees any `decode` module at all.

**Comment by tcharding** [comment]
Righto, and the `consensus::deserialize` (and trait) are re-exported too. That works for me.

**Comment by tcharding** [comment]
> I think it's fine if the user is using the `consensus::ReadExt` trait whose methods return a `consensus::Error`, and if the user never sees any `decode` module at all.

I realised that with this in mind we don't need to do the internal code moves, we can just hide the `encode` module and achieve the same serene new public API :)

**Comment by tcharding** [comment]
Superseded by #2212

**Comment by Kixunil** [comment]
Regarding encode error, I'm pushing for design that will never allow it again.

Regarding making it private: I have love-hate relationship with it. On one hand consensus-encoding is very different thing from script interpreter but they are both thrown in `consensus` module becuase of the common word but I don't really have a better name.

But anyway, I hope much of the consensus module will be moved to a crate or removed entirely. We'll see.

**Pull request closed without merging**
