### PR TITLE
Expose PartialMerkleTree fields

### PR DESCRIPTION
**Pull request by 0xB10C**
Would be nice to have a way of accessing the the fields of [`PartialMerkleTree`](https://docs.rs/bitcoin/0.27.1/bitcoin/util/merkleblock/struct.PartialMerkleTree.html) when, e.g., receiving a [`MerkleBlock`](https://docs.rs/bitcoin/0.27.1/bitcoin/util/merkleblock/struct.MerkleBlock.html) over the network.

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
I think the getters are more preferable, since with making this fields public we can create arbitrary invalid instances.

**Comment by tcharding** [comment]
Hey @0xB10C are you planning on working on this? Otherwise I can convert it into an issue and add the 'good-first-issue' label so one of the new guys can pick this up. Cheers.

**Comment by 0xB10C** [comment]
> Hey @0xB10C are you planning on working on this? Otherwise I can convert it into an issue and add the 'good-first-issue' label so one of the new guys can pick this up. Cheers.

I was planning to pick it up at some point - but yes, feel free to convert it to a good-first-issue.

**Comment by tcharding** [comment]
Closing, a new issue has been created to track this: https://github.com/rust-bitcoin/rust-bitcoin/issues/1046

**Pull request closed without merging**
