### PR TITLE
Add a test parsing transaction with a huge witness

### PR DESCRIPTION
**Pull request by Kixunil**
This transaction broke past versions of `rust-bitcoin` and LND so this adds a test to avoid reintroducing the problem in the future.

See also https://github.com/romanz/electrs/issues/783

I'm publishing this immediately for research purposes. I can clean it up later if required (low on time rn) or we may even not merge it if there is a better test.

### CODE REVIEW

**Comment by romanz** [comment]
IIUC, the failure is due to `byte_size` being 12000072 = 500003 * 24:
```
                let byte_size = (len as usize)
                                    .checked_mul(mem::size_of::<$type>())
                                    .ok_or(self::Error::ParseFailed("Invalid length"))?;
                if byte_size > MAX_VEC_SIZE {
                    return Err(self::Error::OversizedVectorAllocation { requested: byte_size, max: MAX_VEC_SIZE })
                }
```
and indeed the witness definition has changed between 0.27.1 and 0.28.0:
```diff
diff --git a/src/blockdata/transaction.rs b/src/blockdata/transaction.rs
index 4ecac18..445da7d 100644
--- a/src/blockdata/transaction.rs
+++ b/src/blockdata/transaction.rs
@@ -196,7 +198,7 @@ pub struct TxIn {
     /// Encodable/Decodable, as it is (de)serialized at the end of the full
     /// Transaction. It *is* (de)serialized with the rest of the TxIn in other
     /// (de)serialization routines.
-    pub witness: Vec<Vec<u8>>
+    pub witness: Witness
 }

```

**Comment by Kixunil** [comment]
AFAIU even 0.28 is unaffected. This PR just adds test out of caution.

**Review by elichai — APPROVED** [review]
ACK, this is an important test, as this tx did break production systems

**Comment by sanket1729** [comment]
I could not foresee the impact when I opened https://github.com/rust-bitcoin/rust-bitcoin/issues/997. It also lists other potential ways in which block decoding could fail, but all of them required the miner to specifically craft a non-standard tx. Perhaps, this is a lesson for us for back-porting all bug fixes related to decoding/encoding even if they "require miner assistance to deploy".

**Comment by sanket1729** [comment]
Upon more investigation, this issue is not completely fixed in 0.28. The PR that changes `Witness` only accidentally fixes it for 0.28 while decoding things with a large `Witness`. #997  lists other things that are still possible to crash with 0.28. This is cleanly fixed in 0.28 with #1023.

**Comment by sanket1729** [comment]
I have created #1360 as a backport for 0.28 users.

**Review by tcharding — APPROVED** [review]
ACK d6ca7e4b9f02d076d0f968ae5ed4389627ecca27

**Pull request merged**
