### PR TITLE
Release tracking PR: `v0.32.0-rc2`

### PR DESCRIPTION
**Pull request by tcharding**
Bother, I've made a mistake. The setting of the "TBD" field needs to be on master. Please see #2699

### CODE REVIEW

**Comment by apoelstra** [comment]
We also have some "use of deprecated fields" errors in CI here. Not sure why they are suddenly appearing.

Since we have pins on everything now I would like to see green CI (ok, wasm is allowed to fail :)) on all PRs to this branch, so I guess we've gotta fix this.

**Comment by tcharding** [comment]
You mean `kani` not wasm, right? And yes, except for `kani` I'd expect to see this all green. The deprecated stuff is fixed in #2687, I'll rebase on top of that to prove it.

**Comment by tcharding** [comment]
The `kani` guys are working on a fix, they seem to smash out releases so I don't think we will have to wait long.

https://github.com/model-checking/kani/issues/3142

**Comment by tcharding** [comment]
> No, I mean wasm. wasm tooling has no pinning capability and the WASM ecosystem together lacks the cognitive capacity for it.

Ah I get ya, you mean wasm fails are acceptable, not that we should have one today.

**Comment by apoelstra** [comment]
Yep, exactly.

**Comment by tcharding** [comment]
I am not personally going to test this release candidate, I tested already with a local patched version of RC 1 with all the patches in this release applied. Is anyone else testing these RC releases? Can we drop the `v0.32.0` immediately instead of doing rc2?

**Comment by apoelstra** [comment]
>Can we drop the v0.32.0 immediately instead of doing rc2?

Yeah, I think that's fine. We tested rc1, this was the only issue that we found, bluntly I think it's an issue that doesn't even matter, and we fixed it.

**Comment by tcharding** [comment]
Closing in favour of #2706

**Pull request closed without merging**
