### PR TITLE
Tapsighash test vectors

### PR DESCRIPTION
**Pull request by sanket1729**
Based on #695 . Adds the remaining test vectors to test sighash paths. Will rebase after #695

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
Needs rebase

**Review by apoelstra — APPROVED** [review]
ACK 6648477ff2471a79451952aa4f32cb9cd2a4fe58

**Comment by RCasatta** [comment]
Needs rebase

**Comment by sanket1729** [comment]
Rebased

**Review by apoelstra — APPROVED** [review]
ACK 92ee5a7e5f053c9ed3282b78f5202c7b10f6b814

**Review by RCasatta — APPROVED** [review]
ACK 92ee5a7e5f053c9ed3282b78f5202c7b10f6b814

Maybe one day we can have an internal-only crate `test-utilities` used as a dev-dependency where we can put things like `fn bip_341_read_json`

**Pull request merged**
