### PR TITLE
Consolidate feature flags

### PR DESCRIPTION
**Pull request by shinghim**
little bit of cleanup

### CODE REVIEW

**Comment by apoelstra** [comment]
I don't like this. It's harder to read and more likely to cause merge conflicts.

**Comment by shinghim** [comment]
I checked other feature flags and didn't see an instance where we were using multiple `#[cfg(...)]` flags. I also saw many usages of `#[cfg(all(...))]` so i thought that was the convention for this repo.

**Comment by apoelstra** [comment]
At some point we pulled these ones apart. I'd kinda like to pull the rest of them apart too.

**Comment by yancyribbens** [comment]
I don't think this improves readability

**Comment by shinghim** [comment]
Though i do prefer the style in the PR, I opened this cause i noticed that the flags here were the only ones that weren't consistent with how it's done in the rest of the codebase. Not a huge deal one way or the other, just wanted them to be the same

**Comment by tcharding** [comment]
It only just came up the other day, it was my impression that we all agreed having them separate is easier to read and more maintainable. No one has gotten around to PR'ing the change since we discussed it.

**Comment by shinghim** [comment]
gotcha, i didn't see. Created #3446 to track

**Pull request closed without merging**
