### PR TITLE
hashes: Add Hash::from_bytes_iter to construct hashes from iterators

### PR DESCRIPTION
**Pull request by stevenroose**
Is there any interest in a method like this? I'm not necessarily a fan myself, was just in a situation where I was doing this a lot and it would save the me the "engine, from_engine dance" each time.

### CODE REVIEW

**Comment by Kixunil** [comment]
Sounds useful. How about implementing `FromIterator` for all raw hash types? You could then just call `.collect()` on the iterator. Though I wonder if it would be obvious.

Also I'd suggest naming the method `hash_byte_chunks` since the signature allows non-iterators (e.g. &[&[u8]]) to be passed in.

**Comment by stevenroose** [comment]
Oh yeah that rename makes sense. As for FromIterator, yeah I would only do that alongside an explicit method. Discoverability of functionality is very important. Explicit methods do that, traits are often very bad at that :p

**Comment by Kixunil** [comment]
I personally find the traits completely fine, often easier. But it's true that I would be likely confused about this one. (Though from the signature it makes sense we're not creating the hash bytes themselves because it'd have to create a `Result`)

**Review by apoelstra — APPROVED** [review]
ACK 94a6caf204062a5c6b958cf6d866c13913537e27

**Pull request merged**
