### PR TITLE
Fix some typos

### PR DESCRIPTION
**Pull request by GoodDaisy**
1. Fix typos in rustdocs:

    hexidecimal -> hexadecimal
    lenght -> length

2. Fix typos in test function names:

    u256_wrapping_add_wraps_at_boundry -> u256_wrapping_add_wraps_at_boundary
    u256_wrapping_sub_wraps_at_boundry -> u256_wrapping_sub_wraps_at_boundary

### CODE REVIEW

**Comment by apoelstra** [comment]
e5c12c1ad8708afcdc4bd532fe9ad781cde40947 looks great, but could you squash these into one commit?

**Comment by tcharding** [comment]
Thanks for your contribution! These changes are easy to read so its not a big deal but if you plan on doing some more involved changes it would be great if you could please use some text in the PR description. If you would like to be super thorough you could have done these changes in two patches
- "Fix typos in rustdocs"
- "Fix typos in test function names"

The easier you make it for reviewers the more likely your changes are to get quickly acked and merged.

Thanks for helping us out, we can always use it!

**Comment by GoodDaisy** [comment]
@apoelstra @tcharding Thanks for very much your reviews, especially for the best practice!

**Review by apoelstra — APPROVED** [review]
ACK 04f3e939a72fa4a1351a5557106a93f00b949fde

**Review by tcharding — APPROVED** [review]
ACK 04f3e939a72fa4a1351a5557106a93f00b949fde

**Comment by tcharding** [comment]
Thanks man, nice cleanups. Keep at it.

**Pull request merged**
