### PR TITLE
Do minor error fixes

### PR DESCRIPTION
**Pull request by tcharding**
While reviewing #2335 I noticed a few places that error code needed some love.

### CODE REVIEW

**Comment by tcharding** [comment]
cc @Harshit933 in case you are keen to try your hand at code review.

**Review by Kixunil — APPROVED** [review]
ACK fb81bff61f7a447168932fd7e69b7067cc299d16

**Review by Harshit933 — APPROVED** [review]
ACK [`fb81bff`](https://github.com/rust-bitcoin/rust-bitcoin/commit/fb81bff61f7a447168932fd7e69b7067cc299d16)

Looks good!

**Review by apoelstra — APPROVED** [review]
ACK fb81bff61f7a447168932fd7e69b7067cc299d16

**Pull request merged**
