### PR TITLE
Revert "Add effective_value method"

### PR DESCRIPTION
**Pull request by tcharding**
This reverts commit d69d62822d448c7ef33df85f441bbb8c5faec7b7.

This commit added a function to the public API that is not of a high enough standard for a 1.0 release. It objectively makes the code base worse and subjectively makes our job of getting to 1.0 harder.

The function can be implemented outside of `rust-bitcoin` so no user is hobbled if we do not include this function.

### CODE REVIEW

**Comment by apoelstra** [comment]
concept NACK. This is a useful computation and we ought to support it.

**Comment by tcharding** [comment]
It adds functionality while objectively making the code base worse than it was before. Are we going forwards or backwards?

**Comment by Kixunil** [comment]
It really doesn't seem that bad except for `BASE_WEIGHT` being a bad name. I couldn't come up with a better one before but now I'd use `NON_SIGNATURE_WEIGHT`.

**Comment by tcharding** [comment]
I reserve the right to get pissed off again down the track when I feel obliged to clean it up.

**Pull request closed without merging**
