### PR TITLE
Deprecate `SignedAmount`

### PR DESCRIPTION
**Pull request by tcharding**
We currently provide a very basic signed integer type `SignedAmount`. It is not obvious what this type is for. On top of that it only provides a primitive subset of integer operations.

Also, there is ongoing discussion about what `Amount` is even for. Is it a type to represent the value that a single utxo can have? Is it a type that can represent a total transaction amount? Is it a type for summing all bitcoin moved by all transactions for all time? Is it for parsing and pretty printing bitcoin amounts (sats and BTC)? Its not clear.

It seems that the `SignedAmount` is either unneeded or incomplete. Lets deprecate it (and later remove it) to save us the maintenance burden.

### CODE REVIEW

**Comment by Kixunil** [comment]
It can be used for displaying negative bitcoin amounts - pretty useful in UIs representing "you sent sats".

Should we instead expose the `Display` constructor?

**Comment by tcharding** [comment]
> Should we instead expose the Display constructor?

I like that idea.

**Comment by tcharding** [comment]
Check out the last commit @Kixunil, I added `negative` method to `Display` so users can do:
```rust
    let amount = Amount::from_sat(1000);
    let s = format!("{}", amount.display_in(Denomination::Satoshi).negative());
    assert_eq!(s, "-1000");
```

**Comment by Kixunil** [comment]
Nice idea! To be clear I'm still not sure if `SignedAmount` should be deprecated or just without limit. I will have to think about it more. "this number represents satoshis" is a very useful concept so that you don't accidentally mix it with e.g. number of potatoes being sold.

**Comment by tcharding** [comment]
Putting this on ice until we move `Amount` during the crate smashing work.

**Comment by Kixunil** [comment]
I don't think this is still relevant. We've so far doubled down on `SignedAmount` support, I don't see it going away.

**Comment by tcharding** [comment]
Fair.

**Pull request closed without merging**
