### PR TITLE
Make transaction version `i32` rather than `u32`

### LINKED ISSUE #287: Transaction version should be i32 not u32
Currently transaction version is defined as a `u32`
https://github.com/rust-bitcoin/rust-bitcoin/blob/master/src/blockdata/transaction.rs#L257

According to bitcoin source code this should be `i32` https://github.com/bitcoin/bitcoin/blob/c65c77c721b69f1782509145d62978d31c9a1d78/src/primitives/transaction.h#L289.

While the value _should_ always be 1 or 2, there are at least two notable exceptions: txid `35e79ee733fad376e76d16d1f10088273c2f4c2eaba1374a837378a88e530005` has a version of `-2130706433` and `c659729a7fea5071361c2c1a68551ca2bf77679b27086cc415adeeb03852e369` has a version of `-1703168784`.

### PR DESCRIPTION
**Pull request by apoelstra**
Fixes #287

### CODE REVIEW

**Comment by TheBlueMatt** [comment]
I'd kinda rather just fix Bitcoin Core to make transaction version a uint32_t? AFAIR, the only consensus enforcement over tx versions actually casts it to uint32_t instead of using it as signed, so as far as consensus is concerned, tx's version is unsigned.

**Comment by apoelstra** [comment]
Heh, I'd love for Core to be the one to change.

Agree that there is no observable effect of this change anywhere.

**Comment by TheBlueMatt** [comment]
No, there *is* observable change here - if you check the version field in trying to determine if the locktime stuff will be enforced it has to be a u32. Of course you should know that you may need to cast it cause its clearly defined, but still.

**Comment by tamasblummer** [comment]
This should rather be fixed in Core.

**Comment by amoskyler** [comment]
Chiming in here - it does not appear that core will be fixing this as it is intentional and working as expected.

https://github.com/bitcoin/bitcoin/issues/11561#issuecomment-378693945
https://github.com/bitcoin/bitcoin/pull/12430#issuecomment-365470695

There are definitely observable implications of this change. As mentioned in #287 there are at least two transactions with negative transaction versions, and core treats them as such (the rpc server responds with negative values). These values are in fact handled incorrectly by this library.

**Comment by TheBlueMatt** [comment]
Hmmm, I think that first comment is actually wrong. The CSV code casts to unsigned before checking. May be worth revisiting upstream and seeing what Core wants to do before we move forward.

**Comment by TheBlueMatt** [comment]
Looks like we'll do https://github.com/bitcoin/bitcoin/pull/16525 upstream, making tx version unsigned in all observable things.

**Pull request closed without merging**
