### PR TITLE
Move `test_data/*` to `tests/data`

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for adding integration tests in the standard Rust `tests/` directroy; move the contents of `test_data` to `tests/data`.

This was originally part of #724 but that is proving to take an eon to merge so lets put this patch in first. Can then be used by #935 (cc @DanGould).

### CODE REVIEW

**Comment by DanGould** [comment]
ACK https://github.com/rust-bitcoin/rust-bitcoin/pull/1347/commits/374008b81238c505350980389d52c05ce2e4114f

**Comment by RCasatta** [comment]
Remember to update the exclude field in `Cargo.toml`

**Comment by tcharding** [comment]
> Remember to update the exclude field in `Cargo.toml`

Ah yes, thanks man.

**Comment by tcharding** [comment]
Force pushed fix to exclude `tests/` it manifest as suggested.

**Comment by sanket1729** [comment]
Oops, sorry I merged #935 which already contained this commit. We can use this PR to iterate if needed, otherwise, we can close this.

**Comment by apoelstra** [comment]
I'm ok with closing.

**Comment by tcharding** [comment]
My bad, I'll double check its all merged correctly, I made things worse trying to make them easier :)

**Pull request closed without merging**
