### PR TITLE
Add `minimal_non_dust` to `TxOut`

### LINKED ISSUE #1459: Add `fn minima_non_dust(script_pubkey: Script)` constructor to `TxOut`
This is useful for creating fee-bump (anchor) outputs. Computed as `serialized_size * DUST_FEE_RATE`.

### PR DESCRIPTION
**Pull request by Kixunil**
In some scenarios it's useful to create outputs with minimal relayable value. E.g. outputs designated for fee bumping using CPFP. A method for this is useful.

This implements a constructor of `TxOut` that computes the minimal non-dust value from the passed script.

Closes #1459

This one is quite easy, so if we could get it in 0.30, that'd be great.

### CODE REVIEW

**Comment by apoelstra** [comment]
Looks good to me. Checked that this matches `IsDust` in Bitcoin Core. I'm a little surprised it doesn't distinguish between segwit and Taproot, but this is a bit of a weird and approximate function anyway.

**Review by apoelstra — APPROVED** [review]
ACK 6be89bf94f7f944f8b2a78e953379cc17f61716d

**Comment by Kixunil** [comment]
> I'm a little surprised it doesn't distinguish between segwit and Taproot, but this is a bit of a weird and approximate function anyway.

It's actually intentional to not make dust limit too low. I don't remember where I've read it though.

**Review by tcharding — APPROVED** [review]
ACK 6be89bf94f7f944f8b2a78e953379cc17f61716d

**Pull request merged**
