### PR TITLE
Close `amounts` error types

### PR DESCRIPTION
**Pull request by tcharding**
Close the two pubic enum error types in `units::amounts`. All the other structs are closed already because they either have private fields or marked `non_exhaustive`.

### CODE REVIEW

**Review by sanket1729 — APPROVED** [review]
ACK 8c4ea3725531750231077aa9077cef50569a78b2

**Comment by apoelstra** [comment]
With
```
rustc 1.83.0 (90b35a623 2024-11-26)
cargo 1.83.0 (5ffbef321 2024-10-29)
PR: rust-bitcoin #3674
Commit: 0c369e2c6f5896999822f6287f79bc55f84deedd
Tip: false
Workspace: addresses (main: true)
Features: [default]
Lockfile: /nix/store/iybh1ppa0c0vgp4922yms6r8pblvrh9l-source/Cargo-minimal.lock (main: true)

Nightly: false
Run clippy: false
Run docs: false
Run check-api: false
Release mode: false
```

This fails with
```
error[E0433]: failed to resolve: use of undeclared type `Parserror`
  --> units/src/amount/error.rs:60:13
   |
60 |             Parserror::MissingDenomination(_) =>
   |             ^^^^^^^^^
   |             |
   |             use of undeclared type `Parserror`
   |             help: an enum with a similar name exists: `ParseError`
```

**Comment by tcharding** [comment]
ugh, typo in `ParseError` - cheers.

**Comment by tcharding** [comment]
> IOW the first commit does not build.

I would have also accepted "build your patches and read your diffs - noob"

**Comment by tcharding** [comment]
lol, hilarabad. After writing that joke above I realised I had done neither before force pushing and the second patch was _still_ broken. Face palm.

**Review by apoelstra — APPROVED** [review]
ACK fd2a5c1ec79f337fb3695c030c9fb6b4671468f2; successfully ran local tests; thanks!

**Comment by apoelstra** [comment]
Will one-ACK merge since this is identical to the verison Sanket acked except for the fixed typo.

**Pull request merged**
