### PR TITLE
Automated daily update to rustc (to nightly-2024-11-27)

### PR DESCRIPTION
**Pull request by apoelstra**
Automated update to Github CI workflow `rust.yml` by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
ACK 987e31a188672b65fc3505b813cba3d3abd28165

**Comment by tcharding** [comment]
Can we switch to just doing this once a week?

**Comment by apoelstra** [comment]
@tcharding sure -- can you PR to change the Github action?

**Comment by tcharding** [comment]
#3686

**Pull request merged**
