### PR TITLE
Check for overflow in Script::bytes_to_asm_fmt()

### PR DESCRIPTION
**Pull request by Kixunil**
This adds an overflow check in `Script::bytes_to_asm_fmt()` motivated by
`electrs` issue. While it was not tested yet, I'm very confident that
overflow is the cause of panic there and even if not it can cause panic
becuase the public function takes unvalidated byte array and reads
`data_len` from it.

The `electrs` issue: https://github.com/romanz/electrs/issues/490

~~Strangely, this breaks a test case and I can't see why. I'm publishing in case someone wants to help.~~

Edit: One damn character. :D Should be OK now.

### CODE REVIEW

**Comment by Kixunil** [comment]
We found the offending transaction and I added a test cases for its outputs and checked that old code causes them to fail because of overflow. Now I'm certain this was actually a bug and it was the bug that caused electrs issue.

**Comment by Kixunil** [comment]
Note that I noticed a few more overflows that I think are unlikely to happen in practice but intend to send a PR later.

**Review by romanz — APPROVED** [review]

**Review by TheBlueMatt — APPROVED** [review]
LGTM, is it possible to add a fuzz target for this function? It does seem like a good target for a fuzzer.

**Comment by Kixunil** [comment]
Great idea! Though it'd be nice if this got fixed quickly, so not sure if worth dismissing a review.

Also forgot to ask if we can get a point release with this fix (and possibly others).

**Comment by TheBlueMatt** [comment]
Yea, seems like a good thing to put in a new PR, doesn’t have to be here.

**Comment by Kixunil** [comment]
Yes, that's one of them - each match harm has such. I was actually looking into converting iteration to iterator, systematically removing all overflows and merging repeated code via macro (not fn due to `return` statement), but then found the issue with 16-bits. I will continue assuming 16-bit is unsupported and 32-bit is. Also I tried to use `no_panic` originally and the compiler can't prove there's not panic. I'd like to analyze asm eventually.

Anyway, since this has two approvals and it'd be really nice to get it into electrs could this be merged and released in point version, please?

**Comment by apoelstra** [comment]
ACK 76cf74fa9b44e4ce376fcaba5e7eff77463f12cd

**Pull request merged**
