### PR TITLE
Remove unnecessary lifetimes

### PR DESCRIPTION
**Pull request by tcharding**
Linter with new nightly toolchain finds another lifetime that can be elided, do so.

### CODE REVIEW

**Comment by tcharding** [comment]
Found by #3467

**Review by storopoli — APPROVED** [review]
ACK ddde3162ff8417531920aa16e12d7ac73bc5207d
Successfully ran local tests.

**Comment by tcharding** [comment]
> Successfully ran local tests.

lol, @apoelstra writes that because he has an enormous machine that runs a plethora of tests. (And I assume he has a script that pushes the actual message to GitHub.) And he wants the line to appear in the commit history, which it does if its on the same line as the ACK (I think, you'd have to check the merge script to confirm that).

**Comment by tcharding** [comment]
Thanks for the review though @storopoli, review effort is super valuable, appreciate it.

**Review by apoelstra — APPROVED** [review]
ACK ddde3162ff8417531920aa16e12d7ac73bc5207d; successfully ran local tests; not bad, just one

**Comment by tcharding** [comment]
Has two acks, not going to rebase just to pick up WASM fix. All other CI jobs are green.

**Pull request merged**
