### PR TITLE
Move `FromHex` out of hashes and into internals

### PR DESCRIPTION
**Pull request by tcharding**
As we did with the other hex logic; move the code from `hashes::hex` to `internals::hex::parse`.

caveat: I don't know what exactly we are up to with hex, did you have something else in mind @Kixunil? 

### Notes

This makes the `bitcoin::prelude::*` public and puts the `FromHex` trait in it. (If this is ok perhaps we want to chuck a bunch of re-exports in it for our common types?)

### CODE REVIEW

**Comment by tcharding** [comment]
Woops, did some end-of-day polishing and managed to break something, will fix tomorrow (stable test all run locally)

**Comment by Kixunil** [comment]
There's a bunch of things I intended to do with `FromHex`, one of them being only implementing it for `Vec` and call it `VecExt`. The rest should use `FromStr` where appropriate. I think `Script` is an exception that can have an inherent method. Also I think this would be easier after #1189

**Comment by tcharding** [comment]
Went to do #1189 like you suggested and ended up with #1565

**Comment by tcharding** [comment]
Close in favour of https://github.com/rust-bitcoin/rust-bitcoin/pull/1573

**Comment by Kixunil** [comment]
Disagree with closing, #1573 seem too far still.

**Comment by tcharding** [comment]
I responded in the thread of #1573

**Pull request closed without merging**
