### PR TITLE
Add Arbitrary to Weight

### PR DESCRIPTION
**Pull request by yancyribbens**
Adds Arbitrary to the Weight type.  I had meant to add this with the initial Arbitrary PR but I overlooked it.

### CODE REVIEW

**Review by Kixunil — DISMISSED** [review]
ACK bfd93a8b03eee51446119f8e2eeb69789d1ed92c

**Review by tcharding — DISMISSED** [review]
ACK bfd93a8b03eee51446119f8e2eeb69789d1ed92c

**Comment by tcharding** [comment]
nit: I'd prefer all the `Arbitrary` impls to be way down the bottom of files near the `tests` mod because they are needed to be read all that often.

**Comment by yancyribbens** [comment]
> nit: I'd prefer all the Arbitrary impls to be way down the bottom of files near the tests mod because they are needed to be read all that often. (Or at the bottom of all the types code if there are multiple types in a single file.)

Sure mate, no problem.  Done.

**Review by tcharding — APPROVED** [review]
ACK f8edbd1f4570bbd07d824aecf9237e2021204a66

**Comment by tcharding** [comment]
Thanks, appreciate it.

**Review by Kixunil — APPROVED** [review]
ACK f8edbd1f4570bbd07d824aecf9237e2021204a66

**Comment by yancyribbens** [comment]
Thanks, Cheers.

**Pull request merged**
