### PR TITLE
Implement `FromStr` for `UDecimal`/`Decimal`.

### PR DESCRIPTION
**Pull request by jeandudey**
Solves #140

### CODE REVIEW

**Comment by jeandudey** [comment]
Done

**Comment by apoelstra** [comment]
Nice, thanks! Unfortunately it looks like it failed trying to roundtrip the number '6' (which I kinda expected to happen ... that should obviously parse as a 6, but then I'd expect it to serialize as 6.00000000, so I guess the fuzz test needs to be more accepting... perhaps it should parse, then serialize, then parse again, and check that both parses gave the same `Decimal` / `UDecimal`?)

In future I'd appreciate if fuzz-tests would appear in their own commit, because they're generally independent of other changes and can be reviewed independently.

**Comment by jeandudey** [comment]
Done :+1:, fuzz tests are now in their own commit.

**Comment by jeandudey** [comment]
Build is failing because `rust-bitcoinconsensus` doesn't build on 1.14.0, the `cc` crate was updated and doesn't build on 1.14.0 anymore.

**Comment by jeandudey** [comment]
Tracking issue: alexcrichton/cc-rs#336

**Comment by apoelstra** [comment]
Looks like there is also a failing fuzz test case (hex `2d3735363539383732343037353635393837323434` which you should be able to copy into your fuzz binary's unit test, then run `cargo test` in the `fuzz/` directory to reproduce)

**Comment by jeandudey** [comment]
That hex string is the number `-75659872407565987244`, it's too large to fit in the `mantissa` field. The `Decimal`/`UDecimal` parsing functions now return `Error::TooBig` when an overflow occurs.

**Comment by apoelstra** [comment]
I don't mind the churn, but you may find life easier if you run `./travis-fuzz.sh` locally before pushing (and maybe edit the file to do more iterations).

I'm glad we're finding this stuff though ... I expect all of these issues existed in the old code, we just never sussed them out.

**Comment by jeandudey** [comment]
@apoelstra I can't do fuzzing right now on my PC (some reasons, not related to this), that's why I'm pushing and fixing.

**Comment by jeandudey** [comment]
Also the tests are failing with the bytes `302e333434343034333334343333303333303333302039333330203b3333` (a very large fp number), but crashes when `dec.to_string` is called, I found out that this line in the `Display` implementation is causing this error (an overflow panic):

```rust
        let ten = 10i64.pow(self.exponent as u32);
```

Not sure how to handle this though.

**Comment by apoelstra** [comment]
I think we should just forbid exponents larger than 18. I guess this could cause issues for Dogecoin or something but we don't support anything like that now.

**Comment by jeandudey** [comment]
lol, the build is finally green

**Comment by apoelstra** [comment]
Thanks so much! Seems like most of the bugs were latent and had been hanging around since 2014 so it's awesome to finally clear them out.

**Pull request merged**
