### PR TITLE
Clean up after subcrate creation

### PR DESCRIPTION
**Pull request by tcharding**
During the recent creation of the `bitcoin` subcrate I got a few things wrong, not putting `embedded`, `fuzz`, and the changelog into the new subcrate. PR also includes updating `.gitignore` and adding a changelog to `internals`.

This was originally part of 

#1284 but its stand alone work and should be more easily reviewable done separately.

### CODE REVIEW

**Comment by apoelstra** [comment]
concept ACK, though to be clear -- did we land on `fuzz/` being a per-crate thing? In an earlier version of #1284 we were mixing fuzztests for `bitcoin` and `hashes`. This has something of a benefit in that we can fuzz everything altogether in one CI job, but it also is potentially confusing. I forget where we landed there.

**Comment by tcharding** [comment]
In the discussion thread of #1284 you suggest doing fuzzing per crate, I think I remember coming to the same conclusion myself, though I may be mixing it up with the embedded tests, which are definitely per crate. I can come back and merge all the fuzzing together later on if needed without too much trouble.

**Review by apoelstra — APPROVED** [review]
ACK 72238fdb6685b2919f1ce108bb89bc42e52c1093

**Comment by tcharding** [comment]
Force pushed to fix non-existent merge conflicts.

**Review by apoelstra — APPROVED** [review]
ACK 7d62159d303ca64335653e4e985d26698427402d

**Comment by tcharding** [comment]
Perhaps don't merge this one, looks like https://github.com/rust-bitcoin/rust-bitcoin/pull/1284 might go in, it includes all the changes in this PR (although the commits are different, my bad, I can't remember why but I seem to have squashed the last two commits of this one into the second last commit of 1284 (the "import bitcoin_hashes" patch)).

**Comment by tcharding** [comment]
There is no merge conflict with `fuzz/fuzz_targets/deserialize_psbt.rs`

**Comment by apoelstra** [comment]
Now that #1284 is in, what is the state of this PR?

**Pull request closed without merging**
