### PR TITLE
transactions: add a note about `get_vsize` and standardness rules

### PR DESCRIPTION
**Pull request by darosior**
If they ever hit a discrepancy they must really be doing something dodgy but hey :)

### CODE REVIEW

**Review by Claudio060320 — APPROVED** [review]

**Review by Claudio060320 — CHANGES_REQUESTED** [review]
#665

**Review by Kixunil — APPROVED** [review]
Looks good. If you'd like to make it awesome consider adding some guidance in which applications this matters (probably only nodes?).

**Review by dr-orlovsky — APPROVED** [review]
ACK 826fed53f21c8a2380a157247e5eaf5ac9d61e62

**Comment by darosior** [comment]
This matters for any application crafting then broadcasting exotic transactions. IIRC i had put that in the doc comment?
‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Review by Claudio060320 — APPROVED** [review]

**Review by sanket1729 — APPROVED** [review]
ACK 826fed53f21c8a2380a157247e5eaf5ac9d61e62. Verified the implementation with bitcoin core.

**Pull request merged**
