### PR TITLE
Release v0.22.0

### PR DESCRIPTION
**Pull request by stevenroose**
I think we want to wait for https://github.com/rust-bitcoin/rust-bitcoin/issues/284.

### CODE REVIEW

**Comment by apoelstra** [comment]
We don't want to bump the secp or bitcoinconsensus versions in this release, so that people have an opportunity to update to the new APIs without needing to update everything at once.

**Comment by apoelstra** [comment]
We will release 0.23 with no changes except for the dep bumps.

**Comment by stevenroose** [comment]
Ah yeah right, forgot about that. Will update accordingly.

**Comment by apoelstra** [comment]
@stevenroose can you add #349 to this and remove "Blocked"

**Pull request merged**
