### PR TITLE
switch to github actions

### PR DESCRIPTION
**Pull request by apoelstra**
See #541 for context.

### CODE REVIEW

**Review by sgeisler — APPROVED** [review]
Doesn't really count since the changes are mine, but ACK :laughing:

**Review by sanket1729 — APPROVED** [review]
Looks good. Cr Ack

**Review by sanket1729 — COMMENTED** [review]
I usually separate the fuzz things into a separate VM because it runs the longest and run the other nighty tests in other VM. 
This should reduce the CI time without any cost.  What do others think about it?

**Comment by apoelstra** [comment]
@sanket1729  I think you can do that in another PR, so we can get this one in without changes :) but I agree it's a good idea.

**Review by dr-orlovsky — APPROVED** [review]

**Comment by apoelstra** [comment]
Ok, implicit ACKs from me and @sgeisler because we made the PR, an actual ACK from stevenroose on #541, and acks from Sanket and Dr Orlovsky which don't count. Works for me.

**Pull request merged**
