### PR TITLE
Format the `merkle_tree` module

### PR DESCRIPTION
**Pull request by tcharding**
Run `cargo +nightly fmt` and commit the changes to the `merkle_tree` module. No manual changes, only those introduced by `rustfmt`.

### CODE REVIEW

**Review by tcharding — COMMENTED** [review]
`rustfmt` changes only, gets an implicit ack from @Kixunil 

ACK f55c4099d53653f493b4c2c93801c3e9789da671

**Comment by tcharding** [comment]
The changes in this PR are also in https://github.com/rust-bitcoin/rust-bitcoin/pull/1353 but I wanted to do this trivial PR to prove the new rustfmt PR process (one ack + implicit ack from @Kixunil under some conditions).

**Review by apoelstra — APPROVED** [review]
ACK f55c4099d53653f493b4c2c93801c3e9789da671

**Comment by apoelstra** [comment]
Github won't let me merge with only one ACK -- I think maybe @Kixunil should use the approve button here and say explicitly that he's waiving the second ACK since this is a format-only change?

**Review by Kixunil — APPROVED** [review]

**Pull request merged**
