### PR TITLE
Move bip152 module to crate root

### PR DESCRIPTION
**Pull request by tcharding**
We are attempting to flatten the `util` module.

Move the `bip152` module to the crate root out of `util`.

Currently `src/util/` is ignored by the formatter so this move requires `bip152` module to be formatted. Formatting is done as a separate patch so reviewers can run `cargo +nightly fmt` and compare the diffs if so desired.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK c77f3f5771bd3be0b5ad498ad978afad96709c16

**Comment by tcharding** [comment]
Rebase to pick up recent fuzzer change.

**Review by apoelstra — DISMISSED** [review]
ACK 884747eafee4c6bcab4cdada546ab2d571ffabd8

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Comment by apoelstra** [comment]
Needs rebase again :)

**Review by apoelstra — DISMISSED** [review]
ACK 458006d63427250e0d5b74a82585f0d09df5e523

**Review by apoelstra — DISMISSED** [review]
ACK 549e54b9ecfba38eb709331abff936b20d1f83fd

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK 89361ebefc71d8029a6daef13e0ba4fd80f0d5f1

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — DISMISSED** [review]
ACK 1ac02b8164489b9c5431e8398e2e27e113a1a5b5

**Comment by tcharding** [comment]
Rebase only.

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — DISMISSED** [review]
ACK b54b1d603acd9de921ef72b6493ad38979fd0127

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — DISMISSED** [review]
ACK ecda366fe2ff8367db0d512c5f26d8393004ec8d

**Review by apoelstra — APPROVED** [review]
ACK 4057c268297f5c1dc5a5e63ef8757b9351f3bb04

**Review by sanket1729 — APPROVED** [review]
code review ACK 4057c268297f5c1dc5a5e63ef8757b9351f3bb04

**Pull request merged**
