### PR TITLE
Refactor transaction weight

### PR DESCRIPTION
**Pull request by yancyribbens**
Followup from https://github.com/rust-bitcoin/rust-bitcoin/pull/1835.  Call `predict_weight` from `weight` instead of `scaled_size()` https://github.com/rust-bitcoin/rust-bitcoin/pull/1835#issuecomment-1543687210.  I think we could also deprecate `scaled_size()` and `strippedsize()` in a future refactor.

### CODE REVIEW

**Comment by yancyribbens** [comment]
Also removed `checked_weight` since seemingly the only purpose was to check that `weight` was the same as `predict_weight` which will now always will be true since `weight` now calls `checked_weight`.

**Comment by tcharding** [comment]
Can you justify these changes in each commit log please. It is hard to review a PR that says "refactor" when the changes look much more invasive that a refactor.

**Comment by apoelstra** [comment]
@tcharding I think this is actually a pure refactor. If you diff both commits at once you can see that it's essentially moving the "manual" `predict_weight`-based weight function out of a test harness and into `weight`.

The result is that `weight` and `predict_weight` both use the same codepaths, so we can be assured that they're in sync. Though it may make `weight` a tiny bit slower, I suppose.

It looks like there are a bunch of unit tests, none of which were changed (other than the removal of the `check_weight` function which just asserted that the old and new code were the same), so I'm reasonably confident that there is no change here.

**Review by apoelstra — APPROVED** [review]
ACK f5591d8dee0551830e13d1dfff3cd01d6399053e

**Review by tcharding — APPROVED** [review]
ACK f5591d8dee0551830e13d1dfff3cd01d6399053e

**Comment by tcharding** [comment]
Cheers

**Pull request merged**
