### PR TITLE
Set release version in deprecated attribute

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for release replace "TBD" with the next release version - `v0.32.0`.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK f96bbebdcc68684863981726321cb1a308d8103c

**Comment by tcharding** [comment]
@sanket1729 come save us and review this please, lets get the rc2 out this week. Just this one and then we can release (#2688).

**Comment by tcharding** [comment]
There is no explicit one ack carve out for this PR. It only changes the strings in `deprecated` attributes, can you BDFL this in please @apoelstra?

I'm increasingly thinking that our 2-ack merge policy does not work if we do not have 3 devs focused daily on the project. Its difficult to execute things that should take a week if we don't have short PR turn arounds for trivial but blocking things (like this PR which is blocking the next RC #2688).

**Review by storopoli — APPROVED** [review]
ACK f96bbebdcc68684863981726321cb1a308d8103c

BDFL 😂

**Comment by apoelstra** [comment]
Yeah I'll BDFL it.

**Pull request merged**
