### PR TITLE
primitives: Add missing re-exports

### PR DESCRIPTION
**Pull request by tcharding**
Add re-exports of types from `taproot` and `merkle_tree`.

### CODE REVIEW

**Review by jamillambert — APPROVED** [review]
I am not sure I understand the criteria for what to re export and what not to, e.g. exporting `sequence::Sequence` and not `witness::Witness` or `transaction::Transaction`.  But reading the relate issue it looks like this is not worth worrying about since missing ones can easily be added later.

ACK 0518186ed510d0fe648a9ac3449260eaf47b34d2

**Comment by apoelstra** [comment]
`witness::Witness` is already reexported.

`transaction::Transaction` definitely should be -- @tcharding can you update this PR to do so?

**Comment by tcharding** [comment]
> I am not sure I understand the criteria for what to re export and what not to

- In `bitcoin` the criteria is "in the bitcoin venacular" eg `bitcoin::Transaction`
- Common errors are re-exported at the module level so eg `foo::Error` (but `foo::error::SomeNicheError`) 
- In `primitives` (and `units`) basically every thing is re-exported at the crate root unless the type is always used with a path eg `absolute::LockTime` (because we have `relative` as well).

**Comment by tcharding** [comment]
Added `Transaction` - my mistake, thanks.

**Comment by jamillambert** [comment]
Thanks for the explanation, I have a better understanding now.

ACK 2b7cb04265cdb2d62c1bcc645e19d8bafa132b4b

**Review by apoelstra — APPROVED** [review]
ACK 2b7cb04265cdb2d62c1bcc645e19d8bafa132b4b; successfully ran local tests

**Pull request merged**
