### PR TITLE
Run the formatter

### PR DESCRIPTION
**Pull request by tcharding**
We recently introduce a bunch of formatting issues with the new `io` crate, run the formatter.

### CODE REVIEW

**Comment by tcharding** [comment]
I wonder why this is different to #2202?

**Review by apoelstra — APPROVED** [review]
ACK bec86a9289a24d319261a21aa8fbfcdf9954eed5

**Comment by apoelstra** [comment]
But gonna merge #2202 which will require this one to be rebased, I think.

**Comment by tcharding** [comment]
So glad we changed the process to save Steven some work and now both you and I both have additional pointless work to do each day :)

**Comment by apoelstra** [comment]
Lol, well, every week anyway.

And I like this. It takes 30 seconds to review, 10-15 minutes to test, and when it's done I've read through some RSS tabs and reduced my Github notifications by one.

**Comment by tcharding** [comment]
I"ll just leave this for the bot.

**Pull request closed without merging**
