### PR TITLE
Add basic bip39 phrase parsing and generation

### PR DESCRIPTION
**Pull request by stevenroose**
Implementation based on https://github.com/rust-bitcoin/rust-wallet/blob/master/wallet/src/mnemonic.rs.

This is only half the BIP39 spec. The seed generation requires PBKDF2 for which I would have to add an extra dependency.

So followup on merging this would be my question if we're ok with adding a dependency for PBKDF2. [RustCrypto](https://github.com/RustCrypto/password-hashing) has a [`pbkdf2` crate](https://crates.io/crates/pbkdf2) that would be sufficient.

I know we try to avoid extra crypto dependencies, that's why I'm asking here.

We could also not merge this into rust-bitcoin and favor the [`bip39` crate](https://crates.io/crates/bip39) instead, but the implementation there seems quite a lot less efficient. (It allocates a lot more data in the parse steps, maintains a reverse-lookup map for the wordlists.)

### CODE REVIEW

**Comment by apoelstra** [comment]
Concept NAK adding BIP39 support, as per IRC discussion.

Definite NAK regarding any `RustCrypto` dependencies. Their attitude toward software stability is incompatible with rust-bitcoin.

**Comment by dpc** [comment]
Could this be a separate `rust-bitcoin-bip39` crate? Regarding `RustCrypto` - could it be an intermediate step? Or could it be just forked and modified to guarantee stability?

**Comment by stevenroose** [comment]
@apoelstra yeah I implemented mnemonic generation and parsing first and then when I saw the pbkdf2 requirement, I already realized that's probably the reason it wasn't already in rust-bitcoin in the first place.

@dpc there is the bip39 crate that seems to have all functionality. I guess wallet implementers don't care all that much about performance anyway.

**Comment by dpc** [comment]
@stevenroose My concern was mostly about trustworthiness of another crate with anothe author vs maintained by `rust-bitcoin`.

**Comment by stevenroose** [comment]
I see your concern. I also noticed the coding style in the bip39 crate is quite different from rust-bitcoin's standards. But well, it is what it is and the bip39 crate works. I've been using it successfully for a week now :)
Sad thing they [use failure for errors](https://github.com/infincia/bip39-rs/issues/19).

**Comment by dpc** [comment]
I went ahead and [reviewed it again](https://github.com/infincia/bip39-rs/issues/20).

Makes me think - maybe `rust-bitcoin` could have `rust-bitcoin-3rd-party` or something where it re-exports 3rd party crates pinned to versions that passed the review of project members or something?

**Comment by elichai** [comment]
@stevenroose If you're still interested in creating a `rust-bip39` as part of `rust-bitcoin` I would be interested to join in, and even implement pbkdf2 so we won't need `RustCrypto`.

I'd like to use that in a future RSA/PGP project.

**Comment by stevenroose** [comment]
@elichai I decided to just use rust-tiny-bip39 instead. It worked correctly (I verified the usage with libwally bindings). But yeah I wouldn't be opposed to a bip39 crate in rust-bitcoin. It's a widely-used standard and I believe people would have more confidence in a crate maintained here. Especially if the alternative is a crate that forked off from a crate that has an incorrect implementation...

**Pull request closed without merging**
