### PR TITLE
hashes: Default to `no_std`

### PR DESCRIPTION
**Pull request by tcharding**
`hashes` is `no_std` ready, lets default to `no_std`.

Done as part of #2413

### CODE REVIEW

**Comment by tcharding** [comment]
Strange errors showing up in CI on this and other PRs?

**Comment by apoelstra** [comment]
This one looks real; it's related to imports of types which are affected by nostd.

**Comment by tcharding** [comment]
No worries, thanks. Looks like I have some more work to do. Will come back to this.

**Comment by tcharding** [comment]
Note to self, consider updating manifest catagories and keywords to include no-std same as in `bitcoin-io`.

**Comment by apoelstra** [comment]
Hashes does not build with `--no-default-features --features serde` 5f38652d03596c8693fc95464e0f1848a910e401

**Comment by tcharding** [comment]
Interesting, that exposes a hole in CI also then. Will investigate, thanks. Tip your local CI bot for me, he is doing good work.

**Comment by tcharding** [comment]
This is getting a bit silly, one has to wonder at if there is not a better way
```rust
#[cfg(test)]
mod tests {
    #[cfg(feature = "alloc")]
    #[allow(unused_imports)] // Less maintenance if we just import these.
    use crate::alloc::{format, string::ToString, vec, vec::Vec};
    #[cfg(any(feature = "alloc", feature = "serde"))]
    use crate::{sha256d, Hash as _};
```

**Comment by apoelstra** [comment]
This is partially fallout from https://github.com/rust-lang/rust/issues/121708 .. though I think it actually predates that issue.

We have a couple options. One is to just `allow` redundant imports on all our test modules. I'm not thrilled with this because imports *do* become stale. A better one would be (similar to what you've done) to `cfg_attr` allowing redundant imports unless all features are enabled. (But I'm uncertain how to specify "all features". Could be gross to do.)

**Comment by tcharding** [comment]
What if we had a test prelude module (ie., gated on `#[cfg(test)]`) that imported all the alloc related rubbish and also all the individual hash modules, and we allow unused imports in it. Then in each unit test can just do `use crate::test_prelude::*;`

**Comment by tcharding** [comment]
> Could be gross to do.

"gross", what are you, five?

(Not sure if that joke translates to text, but I mean it in the most jovial of ribbing ways.)

**Comment by apoelstra** [comment]
I'm not a huge fan of `prelude` modules, even for tests, because it means that you can't search for the location of symbols within the file that they appear in.

**Comment by tcharding** [comment]
Yeah I've heard you say that before, maybe I'm missing something, but when do you ever need to search for alloc/core/std type e.g,. `Vec`?

**Comment by tcharding** [comment]
Oh, I literally suggested putting non-std types in a prelude :(

**Comment by tcharding** [comment]
Just FTR this PR is good to merge, we are just having a discussion on the pain of imports for `no_std` crates.

**Comment by apoelstra** [comment]
> but when do you ever need to search for alloc/core/std type e.g,. `Vec`?

To understand what set of feature-gates are controlling their import logic, which is important when reviewing code that should work in a no-std context.

But yes, for non-std types the problem with wildcards is even clearer.

**Comment by tcharding** [comment]
> > but when do you ever need to search for alloc/core/std type e.g,. `Vec`?
> 
> To understand what set of feature-gates are controlling their import logic, which is important when reviewing code that should work in a no-std context.

Interesting, so are you saying that when you review no-std code you are thinking "what are the feature gate requirements for this code"? And then you like to look at the imports to see if it matches your thoughts?

I always have treated prelude to mean "there are a set of feature gated imports that work with this code" and because its in one place it implies "and they are sane because we looked before and don't change them much". Where as when the feature gated imports are in each place I have to reason about them to check if they are sane.

**Comment by tcharding** [comment]
Needs rebase, this feature gating is boring as hell - leaving rebasing until after the one-ack thing comes in and we have some hope of merging this without more rebasing.

**Comment by apoelstra** [comment]
CI failure is related to rustdoc concurrency issues -- I had thought we'd fixed that? Do we need to update bitcoin-maintainer-tools here or something?

**Comment by tcharding** [comment]
Ugh, we never merged it. If you merge I'll PR here to update the workflow to use it: https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools/pull/18

**Comment by apoelstra** [comment]
Done.

**Comment by tcharding** [comment]
Let's see if https://github.com/rust-bitcoin/rust-bitcoin/pull/3577 works.

**Comment by tcharding** [comment]
Rebased to pick up changes in #3577, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK ba124757c419aef38019ee7825c32af540b9dcd0; successfully ran local tests

**Pull request merged**
