### PR TITLE
Remove `bech32` dependency from `blockdata`

### PR DESCRIPTION
**Pull request by tcharding**
We have a single usage of the `bech32` crate inside the `blockdata` module, to convert a `WitnessVersion` to a `Fe32`. We then have a single call site where we use the conversion in the `address` module.
    
This code was written without thinking to hard about the introduced dependency on `bech32`, in hindsite it shouldn't have been added.
    
In preparation for splitting a bunch of code in `blockdata` out into the `primitives` crate remove the `bech32` stuff from the `witness_version` module.

### CODE REVIEW

**Review by Kixunil — DISMISSED** [review]
ACK d1397d474b47dcbcdcb02466cf21439818553f8a

**Comment by tcharding** [comment]
I'll sort CI tomorrow.

**Comment by tcharding** [comment]
For context this idea came from: https://github.com/rust-bitcoin/rust-bitcoin/pull/2883#issuecomment-2191721049

**Review by apoelstra — APPROVED** [review]
ACK 010141ecc9a96b0d019c1cca1ef67a95e7b3f623

**Pull request merged**
