### PR TITLE
hash: allow Sha256dHashes to be displayed in a truncated format

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by dpc** [comment]
Isn't `width` supposed to mean the visual width, and not the number of bytes? :) . I think it's a bit of gotcha if it's not the case.

It would make sense to have either:

* an iterator that yields `char`s of a hex-ecoding for a given &[u8], or
* `fn hex_encode_write(data: &[u8], out: &mut [u8])`

to make this more re-usable.

**Comment by clarkmoody** [comment]
> Isn't width supposed to mean the visual width, and not the number of bytes? :) . I think it's a bit of gotcha if it's not the case.

Oops, that's right: [fmt docs](https://doc.rust-lang.org/std/fmt/#width)

To preserve whole bytes in the output, would it make sense to error on odd-valued width inputs?

**Comment by dpc** [comment]
> To preserve whole bytes in the output, would it make sense to error on odd-valued width inputs?

:/ If someone wants first 5 characters of the hash, they should just get it.

**Comment by apoelstra** [comment]
Heh, OK, if you guys wanna do it properly then I'll reopen on bitcoin_hashes and look into what other format modifiers it makes sense to support for hashes.

**Pull request closed without merging**
