### PR TITLE
Fixed typo in comments

### PR DESCRIPTION
**Pull request by taoweicn**

### CODE REVIEW

**Comment by elichai** [comment]
That's what happens when mathematicians write software @apoelstra 😜

**Comment by taoweicn** [comment]
Get it, thanks!
As I have deleted the fork repo, I can not edit this pr again.
If you can, just complete it, otherwise please directly close.

**Comment by stevenroose** [comment]
Yeah was thinking the same that it's not necessarily a typo :p Closing this then?

**Comment by sgeisler** [comment]
I'd say so

**Pull request closed without merging**
