### PR TITLE
Remove accidentally-exported internal macros

### LINKED ISSUE #1176: Messed up release
We messed up by accidentally publishing our internal macros. This is mainly my fault for incorrectly using `macro_export`. I've read they are not exported from crate unless in root but didn't verify it and it looks like it's wrong. I will submit a PR soon.

Suggested approach: release 0.29.1 and yank 0.29.0. Hopefully nobody started depending on it yet.

### PR DESCRIPTION
**Pull request by Kixunil**
Closes #1176

### CODE REVIEW

**Review by apoelstra — DISMISSED** [review]
ACK c9f2aae0c35a684e51f9273333c25f1b13d1d4ee

**Review by tcharding — APPROVED** [review]
ACK c9f2aae0c35a684e51f9273333c25f1b13d1d4ee

**Review by sanket1729 — APPROVED** [review]
ACK c9f2aae0c35a684e51f9273333c25f1b13d1d4ee

**Comment by sanket1729** [comment]
I think rebase would fix this after we merged #1175 . But I don't mind merging it as this _should_ pass on merge commit

**Comment by Kixunil** [comment]
Hmm, I thought GitHub would test against current master, not against one that was there at the time of opening.

**Comment by sanket1729** [comment]
> Hmm, I thought GitHub would test against current master, not against one that was there at the time of opening.

No it does not. One of the main reasons that we have the merge script that runs tests on the merge commit. It is also possible to PR with green lights passes checks from its own CI config, but fails master.

**Review by sanket1729 — APPROVED** [review]
reACK 94eeabfd6c3de9102a3ba05ac2853683bb8492ad

**Review by apoelstra — APPROVED** [review]
ACK 94eeabfd6c3de9102a3ba05ac2853683bb8492ad

**Pull request merged**
