### PR TITLE
NO MERGE: Debug fuzzing

### PR DESCRIPTION
**Pull request by tcharding**
Currently the `deser_net_msg` fuzz test is failing intermittently. To aid debugging delete all the other fuzz tests and run the fuzzer for an hour.

Reasoning: I am unable to reproduce this fail locally, first step in debugging it is getting a reliable repro.

### CODE REVIEW

**Comment by tcharding** [comment]
Have you guys got any ideas on how to debug this? If I can't produce it locally I'm stuck on what to do? The VM this runs in has 2 cores and 7 gig of memory and runs Ubuntu-latest, what could be causing the fuzz test to fail in the VM but not on a desktop?

**Comment by Kixunil** [comment]
Miscompilation? You could try to upload the built binary from the CI somewhere where we can download it from and analyze. GH has a built-in functionality for it called artifacts but IDK how to download it manually.

**Comment by tcharding** [comment]
Cool, cheers. I'll see if I can do that.

**Comment by tcharding** [comment]
I just hit this two times in a row, after not seeing it for a week or two.

**Pull request closed without merging**
