### PR TITLE
Delete contract hash module

### PR DESCRIPTION
**Pull request by tcharding**
This module has been deprecated in commit 1ffdce9 in August 2020, it is safe to delete it now.

Fixes: #322

### CODE REVIEW

**Comment by apoelstra** [comment]
cc @sanket1729 can/should we reimplement this module's functionality in rust-miniscript?

It looks like we use the `tweak_key` function internally in Blockstream. Alternate locations for that function would be the rust-elements repo (since it uses a very Elements-specific tweaking method that we wouldn't implement today), or we could just pull it into Blockstream's internal codebase.

Regardless, concept ACK removing it here.

**Review by apoelstra — APPROVED** [review]
ACK 7f33fe6a9bad303ba58c8db55af2e672f89ff753

**Review by Kixunil — APPROVED** [review]
ACK 7f33fe6a9bad303ba58c8db55af2e672f89ff753

I'm also OK with this being RC fix.

**Review by dr-orlovsky — APPROVED** [review]
ACK 7f33fe6a9bad303ba58c8db55af2e672f89ff753

I'm ok on merging for RC fix, but still put a milestone for `0.29` if we forget to do it now

**Comment by sanket1729** [comment]
> cc @sanket1729 can/should we reimplement this module's functionality in rust-miniscript?

Yes, elements-miniscript needs this functionality. Will re-implement this over there

**Pull request merged**
