### PR TITLE
Elide more lifetimes

### PR DESCRIPTION
**Pull request by tcharding**
clippy found some more lifetimes to elide.

### CODE REVIEW

**Comment by tcharding** [comment]
CI is slow these days, over half an hour.

**Review by jamillambert — APPROVED** [review]
Annoying Clippy didn't just find them all the first (or fourth) time.  Hopefully this is the last of it.  It does seem like more this time.

ACK 3e2c43b19e111ee58fb280232e084ea40263040b

**Review by apoelstra — APPROVED** [review]
ACK 3e2c43b19e111ee58fb280232e084ea40263040b; successfully ran local tests

**Comment by tcharding** [comment]
Better late than never.

**Pull request merged**
