### PR TITLE
Move hash types to where they live

### PR DESCRIPTION
**Pull request by tcharding**
Move hash types out of `hash_types` and into the modules where they are primarily used. Adds deprecated re-export so this is not a breaking change.

Is an alternate solution to #2072

Resolves: #2072

### CODE REVIEW

**Review by Kixunil — COMMENTED** [review]
Hell yeah! I wanted this a long time ago and getting rid of `hash_types` module.

**Comment by tcharding** [comment]
> Hell yeah! I wanted this a long time ago and getting rid of hash_types module.

You inspired me. I rebased, and added a few additional patches fully gutting the `hash_types` module. I also added some docs fixes to the hash moves patches -BOOM!

**Review by apoelstra — DISMISSED** [review]
ACK 755d71afcc9e27b847d74f85ed61d8f51403f3ae

**Comment by tcharding** [comment]
Rebased, no other changes.

**Review by apoelstra — DISMISSED** [review]
ACK 97f44d71591e62e4c7d9b960eada74a2f358a329

**Comment by tcharding** [comment]
Can we get a quick review please @Kixunil

**Comment by tcharding** [comment]
Rebased, includes some fixes to things that either were broken or got borken during rebase. Note:
- Public re-exports from `lib.rs` are now more complete, all hash types are re-exported.
- Some moves of `From` impls were in the wrong patch when I first did this.

**Review by apoelstra — DISMISSED** [review]
ACK 1bc2e10e635391b9a543ccf174c932e76fe1929e

**Comment by tcharding** [comment]
Rebased and removed the trivial docs "fix", it wasn't really worth doing.

**Review by apoelstra — APPROVED** [review]
ACK 801c72e0566e38f98fe93a43074f4a6db8b20958

**Review by Kixunil — APPROVED** [review]
ACK 801c72e0566e38f98fe93a43074f4a6db8b20958

**Pull request merged**
