### PR TITLE
Fix kani codegen CI job

### PR DESCRIPTION
**Pull request by tcharding**
Fix the current failing Kani job on todays PRs. 

FTR our daily `kani` job has been red for ages, perhaps since we created the `units` crate? But today the `--codege-only` job broke (on all PRs). `kani` released a new version 10 days ago, pinning to the previous version seems to resolve the issue. I raised a bug report but did not investigate further. 

- Patch 1: Remove redundant import
- Patch 2: Rename the tests
- Patch 3: Pin kani version

File bug report: https://github.com/model-checking/kani/issues/3142

PR is CI only, can go in with one ack.

(Patch 2 is the result of debugging the _real_ kani failure we have at the moment, I'll save the rant for the PR that fixes it.)

### CODE REVIEW

**Comment by tcharding** [comment]
This is CI only, can go in with one ack.

**Review by sanket1729 — APPROVED** [review]
utACK 0f0bd91929aa140ec6ba380316407552679cb9cf

**Comment by tcharding** [comment]
> I wonder if we shoud comment out the test in rust.yml and file an issue

I don't understand, how is that better than keeping coverage by using an old kani?

**Comment by apoelstra** [comment]
> > 
> 
> I don't understand, how is that better than keeping coverage by using an old kani?

We don't have coverage unless we fix our existing tests. We just have a daily "CI failed" notification that we ignore.

**Comment by tcharding** [comment]
I fixed that yesterday, its in the `amount` error PR

https://github.com/rust-bitcoin/rust-bitcoin/pull/2689#discussion_r1567914186

**Comment by tcharding** [comment]
> We don't have coverage unless we fix our existing tests.

I meant that the `rust.yaml` job adds coverage by doing the `--codegen-only` because otherwise the code is never checked (because of the `#[cfg(kani)]` attribute.

**Comment by apoelstra** [comment]
>Fixing it is what set me off raging about the error types. git blame tells me you wrote the problematic line in the kani test, its bad policy to throw mud but I chuckled when you said it was perfectly clear above :)

I said the fields of the error types were perfectly clear :). I said nothing about the Kani test. If you used git blame a little harder, you would have found that Kix wrote the original code, and when it was intermittently failing on the same line, I simply edited it to invert that specific line (without reasoning through the rest of the test, which tries to do way too many things at once). This appeared to fix it so we merged it, but it seems that it merely turned an intermittent failure into a differently intermittent failure.

**Comment by apoelstra** [comment]
Actually the history on *this* test is a little weirder.

It looks like I wrote the test in https://github.com/rust-bitcoin/rust-bitcoin/pull/1415. Originally it had simple error types (and presumably worked).

Then in https://github.com/rust-bitcoin/rust-bitcoin/pull/2497 (by a new contributor) we changed all the error types to have more information, which broke the Kani tests, which (at the time) we were not compile-testing in CI. Note that in that PR I commented on how much better the error types were ;).

Then **you** "fixed" the test https://github.com/rust-bitcoin/rust-bitcoin/pull/2430 which Kix and I ACKed, presumably because it was a test-only change that made CI pass when it previously wasn't. This was Feb 1st.

However, we did not realize that your fix was wrong, because Kani was separately broken. I "fixed" this on Feb 5 in https://github.com/rust-bitcoin/rust-bitcoin/pull/2450 (this is what I was thinking about my previous comment -- Kix had introduced the offending line a week prior, in https://github.com/rust-bitcoin/rust-bitcoin/pull/2370, though now that I look at it, I actually wrote the rest of the test ;) Kix did not have anything to do with **this** issue).

So, you are welcome to try to untangle the exact sequence of events there. It looks like we had two very-similar-looking-but-unrelated problems being introduced and partially fixed on overlapping timelines, and the root cause was that my old Kani tests (which previously had simple "this should work or this should overflow" semantics) being gangpressed into detecting *different kinds of overflow*. Which would have been complicated and likely-broken no matter how clearly-defined the new more-nuanced error types were.

**Comment by tcharding** [comment]
Wow, so whats the lesson from this? Some possible ones I can think of

- One assertion per test 
- Don't let kani daily job go red

**Comment by tcharding** [comment]
> Well, unless we expect PR authors and reviewers to see the future, we cannot enforce this :).

oh, I should have said "don't let kani _stay_ red"

**Pull request merged**
