### PR TITLE
Implement ArbitraryOrd for relative::LockTime

### PR DESCRIPTION
**Pull request by tcharding**
TL;DR As we do for `absolute::LockTime` and for the same reasons; implement `ArbitraryOrd` for `relative::LockTime`.

locktimes do not have a semantic ordering if they differ (blocks, time) so we do not derive `Ord` however it is useful for downstream to be able to order structs that contain lock times. This is exactly what the `ArbitraryOrd` trait is for.

Fix: #2566

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 11867db7e75413778c1b02603325969dabecd3a4

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK 53c5d4ff74e9514eae13369cacfc6b819a229e4e

**Comment by tcharding** [comment]
Forgot to comment yesterday, IIRC I fixed the rustdoc so its the same in both `absolute` and `relative`. Also at some stage I thought it a good idea to remove the `PartialOrd` impl, but then realized I was wrong. Not sure if that was ever pushed up but FTR both locktimes still implement `PartialOrd` (and now also implement `ArbitraryOrd`).

**Comment by apoelstra** [comment]
The comma after "incommensurate" should be a semicolon.

**Comment by tcharding** [comment]
You mean you want the sentence changed to this?
```rust
/// Locktimes may be height- or time-based, and these metrics are incommensurate; there
/// is no total ordering on locktimes.
```

Currently it is:
```rust
/// Because locktimes may be height- or time-based, and these metrics are incommensurate, there
/// is no total ordering on locktimes
```

(I repeatedly have to look up how to use semi-colons, I did so again last week.)

**Comment by tcharding** [comment]
Done!

**Review by apoelstra — APPROVED** [review]
ACK 3520f550f0d00c96bba7ab0f9912bb5bfd609edd

**Review by sanket1729 — DISMISSED** [review]
ACK 3520f550f0d00c96bba7ab0f9912bb5bfd609edd. `ordered` should be added to all features flags doccomment listed in`lib.rs`

**Comment by tcharding** [comment]
Can do, thanks for the review!

**Comment by tcharding** [comment]
Added as a separate patch, will need re-acking now please @sanket1729

**Review by sanket1729 — APPROVED** [review]
ACK d91cdd20bfc0eebce5a067d37d05381bac2845aa

**Review by apoelstra — APPROVED** [review]
ACK d91cdd20bfc0eebce5a067d37d05381bac2845aa

**Pull request merged**
