### PR TITLE
Transaction and header version is signed int

### PR DESCRIPTION
**Pull request by braydonf**

### CODE REVIEW

**Comment by dpc** [comment]
Seems like it's missing some description/motiviation. Is this because that's how it is in Bitcoin Core or are there any other reasons for it?

**Comment by braydonf** [comment]
See protocol documentation at:
- https://en.bitcoin.it/wiki/Protocol_documentation#tx
- https://en.bitcoin.it/wiki/Protocol_documentation#Block_Headers

**Comment by dpc** [comment]
Out of curiosity - are there any practical reasons for it, or is that just legacy arbitrary choices?

**Comment by braydonf** [comment]
Currently it's not being used for anything consensus related (afaik). If the version was `> 2147483647` or `< 0` and `>= -2147483648` there would be incompatibility.

**Review by sgeisler — APPROVED** [review]
A test case for consensus en/decoding against a fixed test vector would be nice to show that it fixes a bug.

**Comment by apoelstra** [comment]
I don't think there would be any observable change in behavior under any circumstances.

But concept ACK, we ought to formally match the data structures in Core.

**Comment by braydonf** [comment]
@sgeisler I've added test cases for en/decoding. I checked the decoding result matches Bitcoin Core using the RPC method `decoderawtransaction` and a custom method for decoding blocks.

**Review by sgeisler — APPROVED** [review]

**Review by darosior — APPROVED** [review]
ACK 945db009b2638151ac80e3750a11ade455c2a034

**Review by apoelstra — APPROVED** [review]
utACK

**Pull request merged**
