### PR TITLE
script: Audit inlining

### PR DESCRIPTION
**Pull request by tcharding**
Audit the `script` module and improve inlining. While doing this I made an effort to understand and think a bit harder about inlining, I used godbolt.org to compile snippets.

This is non-urgent work, review will require some thought. I no doubt have more to learn yet. If I can please ask for the assistance of reviewers in improving my understanding here then doing the rest of the codebase should require much less review time.

Thanks

### CODE REVIEW

**Comment by tcharding** [comment]
Needs #1594 to get past clippy.

**Comment by elichai** [comment]
unsafe shouldn't be a consideration for inlining, as inlining is done at a much later stage so there shouldn't be any affect for that.

I agree that every non-generic public function that is very small should probably have a `#[inline]` hint on top of it

**Comment by tcharding** [comment]
> unsafe shouldn't be a consideration for inlining, as inlining is done at a much later stage so there shouldn't be any affect for that.

If you have time, and just for my education, can you explain a bit more please?

> I agree that every non-generic public function that is very small should probably have a `#[inline]` hint on top of it

"very small" - is three lines of code (excluding formatting) a fair heuristic or should we use something more flexible?

**Comment by Kixunil** [comment]
> inlining is done at a much later stage

I wouldn't even say that. They are simply completely orthogonal concepts and don't have anything to do with each other. `unsafe` is about the rules of the language, `inline` is low-level codegen directive.

> "very small" - is three lines of code (excluding formatting) a fair heuristic or should we use something more flexible?

I think the only reasonable heuristic is "compile it in your head, applying basic optimizations like inlining, const propagation and dead-code-elimination assuming the caller just did all checks that'd trigger panics (IOW, delete all branches with panics) and if the resulting assembly has only a few instructions it should be inline". No need to compile perfectly of course.

I'm not sure how many devs can do that, but I assume I'm not the only one.

**Comment by tcharding** [comment]
Cheers, the script tagging might  take me a while, I can only work on it when I'm fresh because I have to think really hard about what all the scripts are and what methods operate on what kinds of scripts.

**Comment by tcharding** [comment]
> I'm not sure how many devs can do that

I'm not sure if I'm one but I'll go back over this and have a crack at it :)

**Comment by tcharding** [comment]
Draft until I compile the whole `script` module down to assembler in my head - @Kixunil is certainly pushing me - when I'm a master programmer I will look back on these days fondly :)

**Comment by Kixunil** [comment]
Indeed, having more methods marked `#[inline]` is a bit less bad than too few I think. There's also another way to look at it: are other optimization passes likely to remove dead branches after inlining? The answer is yes for probably all functions that check validity of their arguments as the first step.

**Comment by tcharding** [comment]
@sanket1729 Legend, thanks man! Will re-spin.

**Pull request closed without merging**
