### PR TITLE
Huffman Encoding Bug Test

### PR DESCRIPTION
**Pull request by JeremyRubin**

### CODE REVIEW

**Review by sanket1729 — COMMENTED** [review]
ACK, tested that this test makes sense and correctly passes after rebased on #699

**Comment by dr-orlovsky** [comment]
We need a rebase for the CI to pass and this got merged

**Comment by JeremyRubin** [comment]
@dr-orlovsky good to go

**Review by sanket1729 — APPROVED** [review]
ACK 3b968e482cfc8abf5f54841dd2035026439d7dae

**Review by dr-orlovsky — APPROVED** [review]
utACK 3b968e482cfc8abf5f54841dd2035026439d7dae

**Pull request merged**
