### PR TITLE
Subsidy halving interval

### LINKED ISSUE #801: Add nSubsidyHalvingInterval constant
I'm not sure if the policy of this crate is to only include constants that are used, or to include generally useful constants. If it's the latter, it would be nice to include nSubsidyHalvingInterval.

### PR DESCRIPTION
**Pull request by casey**
Fixes #801.

### CODE REVIEW

**Review by Kixunil — COMMENTED** [review]
I think that it'd be better to squash trivial commit like added period. If you're going to do it you might as well format the number as `210_000` which is easier to read.

**Comment by casey** [comment]
> I think that it'd be better to squash trivial commit like added period. If you're going to do it you might as well format the number as `210_000` which is easier to read.

Done!

**Review by Kixunil — APPROVED** [review]
ACK 94dd57de1261d81604c980dcaac1a325f82758f7

**Comment by Kixunil** [comment]
This is the kind of feature addition that I'm fine with adding to RC.

**Comment by dpc** [comment]
Just a though: I generally add "units" to name of constants when possible. So `SUBSIDY_HALVING_BLOCKS_INTERVAL` or  `SUBSIDY_HALVING_INTERVAL_BLOCKS`? Here it seems rather obvious (I can't think of any other unit that would make sense), but the rule of thumb is a rule of thumb so just letting you know.

**Comment by casey** [comment]
In the case of constants from Bitcoin Core, it's probably best to use whatever name is used in core, adapted to the local naming convention. (I.e. SCREAMING_SNAKE_CASE).

If you [Google nSubsidyHalvingInterval](https://www.google.com/search?q=nSubsidyHalvingInterval) you get a lot of hits, so keeping it consistent with those hits, and with core, is probably a good idea.

**Review by apoelstra — APPROVED** [review]
ACK 94dd57de1261d81604c980dcaac1a325f82758f7

**Pull request merged**
