### PR TITLE
Manually implement comparison traits for `CompactTarget`

### PR DESCRIPTION
**Pull request by tcharding**
The `CompactTarget` is a lossy encoding of a `Target`, as such two `Target` objects may compare differently to the associated `CompactTarget`, this is surprising.

We can manually implement all the comparison traits (incl. `Hash`) by first converting the `CompactTarget` to a `Target` - this way any comparison or ordering will be unsurprising.

Fix: #2110

### CODE REVIEW

**Comment by tcharding** [comment]
On ice until after next release.

**Comment by apoelstra** [comment]
I think we agreed in #2110 to drop `PartialOrd` and `Ord`.

Then as far as `Eq` and `Hash` go, I don't understand why we bother converting to a target. Doing this is functionally identical (for `Eq`) and provides no new information (for `Hash`) versus not doing it.

**Comment by apoelstra** [comment]
Ah, right, some compact targets may be unequal while the expand to the same target.

In https://github.com/rust-bitcoin/rust-bitcoin/issues/2110#issuecomment-1751748756 I proposed dropped *PartialEq* (and therefore Eq and Hash) because the semantics were non-obvious, but suggested we could keep `PartialOrd` because "the compact representation does preserve order". But actually I don't think that's true. If it doesn't preserve (in)equality then how can it preserve order?

**Comment by tcharding** [comment]
> If it doesn't preserve (in)equality then how can it preserve order?

Good observation. Are we back at another "this does not behave as you would expect, welcome to Bitcoin" comment?

**Comment by apoelstra** [comment]
>Good observation. Are we back at another rusdoc "this does not behave as you would expect, welcome to Bitcoin" as the only solution?

I think we should just tell people to either convert to a `Target` or convert to a `u32` if they want equality or ordering, because these have different semantics and it's not obvious which one they want.

**Comment by tcharding** [comment]
Closed in favour of #2754

**Pull request closed without merging**
