### PR TITLE
 Make `sha256t_hash_newtype!` evocative of the output. 

### PR DESCRIPTION
**Pull request by Kixunil**
The Rust API guidelines state that macros should be evocative of the
output, which is a sensible recommendation. We already had this for
`hash_newtype!` macro but didn't for sha256t version.

This changes the macro to have this syntax:

```rust
sha256t_hash_newtype! {
    // Order of these structs is fixed.
    /// Optional documentation details here. Summary is auto-generated.
    /*pub*/ struct Tag = raw(MIDSTATE_BYTES, LEN);

    /// Documentation here
    #[hash_newtype(forward)] // optional, default is backward
    /*pub*/ struct HashType(/* attributes allowed here */ _);
}
```

Closes https://github.com/rust-bitcoin/rust-bitcoin/issues/1427

Depends on #1769 

How do you like the syntax? Is weird `struct Foo = bar(..);` acceptable?

### CODE REVIEW

**Review by tcharding — APPROVED** [review]
ACK 91f45a214fedd353b2dce3c88442b0565a022d9c

**Comment by tcharding** [comment]
Cool.

**Comment by tcharding** [comment]
I think #1758 will fix the CI fail.

**Comment by Kixunil** [comment]
LOL, you merged it already. OK I guess. :)

Regarding naming, all of them are IVs, so telling what's specific about them seems better. Mentioning BIP-340 sounds good. Byte version was added just in case something comes up in the future.

Maybe just `bip340()` and `raw`?

**Comment by apoelstra** [comment]
@Kixunil `bip340` and `raw` sound great to me!

Yes, yes, sorry for going ahead and merging -- the PR seemed reasonably large and conflict-prone, and the naming unimportant enough that it could get slipped, that I figured it'd be nicer to do the renaming (if we decided to) in a different PR.

**Pull request merged**
