### PR TITLE
TryFrom<SignedAmount> for Amount and vice versa

### LINKED ISSUE #2245: units: `impl TryFrom<Amount> for SignedAmount` and vice-versa
These conversions mimic the standard library and should be naturally available. Note that `to_unsigned`/`to_signed` already exist so just call that. However the error types are unfortunate, we should have non-parsing-related ones.

### PR DESCRIPTION
**Pull request by connormullett**
Closes #2245 

Adds `TryFrom<SignedAmount> for Amount` and `TryFrom<Amount> for Amount`

### CODE REVIEW

**Review by Kixunil — DISMISSED** [review]
ACK c1850bac8cc4b71c9ce8acb5313b57432497bc20

**Comment by tcharding** [comment]
I'm a nack on this one I'm afraid. We are in the process of moving `amount` to the new `units` crate, so this will conflict with that, which would be ok but this change needs immediate improvement because of the error stuff. I don't see the advantage in merging this change now.

Appreciate you doing the work though @connormullett, if you are keen the correct solution is to do this fix on top of #1225 [and first fix the error return type of `to_signed` to not use a "parse" error].

**Comment by connormullett** [comment]
> I'm a nack on this one I'm afraid. We are in the process of moving `amount` to the new `units` crate, so this will conflict with that, which would be ok but this change needs immediate improvement because of the error stuff. I don't see the advantage in merging this change now.
> 
> Appreciate you doing the work though @connormullett, if you are keen the correct solution is to do this fix on top of #1225 [and first fix the error return type of `to_signed` to not use a "parse" error].

No worries, I'll keep an eye on that PR and will adjust it then.

**Comment by tcharding** [comment]
Thanks man, appreciate the effort.

**Comment by Kixunil** [comment]
Can you rebase? Hint: if you enable rerere in your git config then rebase should work out of the box.

**Comment by tcharding** [comment]
We are gearing up to release the units crate @connormullett, can you rebase this one? If you don't have time just ping me and I'll pick it up for you. Thanks.

**Comment by tcharding** [comment]
Done by #2462.

**Pull request closed without merging**
