### PR TITLE
Remove extern crates

### PR DESCRIPTION
**Pull request by tcharding**
Do some clean up of `extern crate` statements now we have edition 2018.

4 separate but very similar patches, separated to ease review.

### CODE REVIEW

**Comment by Kixunil** [comment]
Seeing all those `internal_macros` maybe we should have perma-unstable `bitcoin_internal_macros` crate so that we could stabilize `bitcoin_hashes` and `bitcoin` crates at some point.

**Comment by tcharding** [comment]
Soon as v0.29.0 is out crate smashing is the next big task, I copied your comment over there so it doesn't get forgotten.

https://github.com/rust-bitcoin/rust-bitcoin/issues/787

**Review by apoelstra — DISMISSED** [review]
ACK c23c3ff8ce28824522d0574a7639c728e6e699b2

**Review by apoelstra — DISMISSED** [review]
ACK 7b50e82de32e3a973a4fe3c3d0d9eddd4cb6ada0

**Review by sanket1729 — DISMISSED** [review]
utACK 7b50e82de32e3a973a4fe3c3d0d9eddd4cb6ada0. But has conflicts

**Comment by sanket1729** [comment]
utACK 21a1cc791cebd4bd1e83c9b74b50e947668c7d31

(https://github.com/rust-bitcoin/rust-bitcoin/commit/21a1cc791cebd4bd1e83c9b74b50e947668c7d31) . Reviewed the range-diff from  7b50e82

**Review by sanket1729 — APPROVED** [review]
utACK 21a1cc791cebd4bd1e83c9b74b50e947668c7d31

**Review by apoelstra — APPROVED** [review]
ACK 21a1cc791cebd4bd1e83c9b74b50e947668c7d31

**Pull request merged**
