### PR TITLE
Fix weight subtract bug

### PR DESCRIPTION
**Pull request by yancyribbens**
Fix subtraction bug

### CODE REVIEW

**Comment by apoelstra** [comment]
Lol! Thanks. Funny that clippy's stupid "you're calling a different op in an op implementation" lint didn't trigger here, even though it constantly triggers for me when it's wrong.

**Review by apoelstra — APPROVED** [review]
ACK b311e966032b95a9448a58d9c5f4a0a29ce38694

**Review by tcharding — APPROVED** [review]
Process fail huh, we should have seen this during review.

ACK b311e966032b95a9448a58d9c5f4a0a29ce38694

**Comment by apoelstra** [comment]
I'm not too shook up about the process failure -- this is very easy to miss. Even looking at the diff, with color highlighting and everything, it doesn't really jump out at you. (This *is* concerning, but it feels to me like a "human brain failure" rather than a "process failure" and I'm not sure what to do about it.)

I guess, one process lesson to take is that every op ought to have a unit test..

**Review by sanket1729 — APPROVED** [review]
utACK b311e966032b95a9448a58d9c5f4a0a29ce38694

**Comment by yancyribbens** [comment]
@Kixunil don't feel bad, it's an easy mistake to mistake!

**Pull request merged**
