### PR TITLE
Add constants to `InputWeightPrediction`

### PR DESCRIPTION
**Pull request by Kixunil**
There are several common spends in Bitcoin that have known input weight predictions. It can be useful to have these as constants, so this change adds them. However, this only adds native segwit ones as the others are slowly fading away and might clutter the API.

If anyone wants other constants, please write them for me, their value is not that great to me so I'm not motivated to figure out the correct numbers. :)

This would be nice to add to 0.30 since it's small and easy but not critical.

### CODE REVIEW

**Comment by apoelstra** [comment]
The "smallest possible DER" signature is not 70 bytes, but more like 12. I forget the exact value. It's not remotely accessible because you'd need to do 2^512 work or so to grind it out. But it's definitely feasible to grind out more than a byte.

**Comment by Kixunil** [comment]
Oh, so it should be a function of how many bytes you want to grind?

**Review by apoelstra — APPROVED** [review]
ACK 3eb648df01e5d144b034fc5733522aef77494448

**Review by tcharding — APPROVED** [review]
ACK 3eb648df01e5d144b034fc5733522aef77494448

**Review by sanket1729 — APPROVED** [review]
> However, this only adds native segwit ones as the others are
slowly fading away and might clutter the API.

Interesting take. I am ambivalent, but tending towards what you are suggesting. On one hand, having p2pkh is good because it still has considerable usage. But I also like the idea of rust-bitcoin slowly putting in more time into newer things so that we also encourage developers to use native segwit (which is better, cheaper for them and overall easier for us for maintain)

ACK 3eb648df01e5d144b034fc5733522aef77494448

**Pull request merged**
