### PR TITLE
Added regtest network

### PR DESCRIPTION
**Pull request by popzxc**

### CODE REVIEW

**Comment by popzxc** [comment]
Hello guys.
I'm currently working on a few more pull-requests, which are adding consensus parameters for different chains and block header verification and acceptance.

Unfortunately, I can't create them until this regtest PR is merged. 

Could you please give me some feedback, if there is something wrong with this PR?

**Comment by tamasblummer** [comment]
As I wrote before: I do not support panic! in this library. It is fain to fail an application in an unrecoverable state, but a library should rather propagate errors via Result<>

**Comment by popzxc** [comment]
That's ok. I'll fix that in a few days :)

**Comment by popzxc** [comment]
Well, generally `regtest` behaves on the same rules as `testnet`, so I decided to not complicate things and replaced panics such way that `regtest` mimics `testnet`.
On the one hand, it won't bring any erroneous behavior, and even more: developers will be able to test some features without `testnet`.
On the other one, logic is now kind of asymmetric, e.g. `bip32`-encoded `regtest` private key will be decoded as the `testnet` one. But expecting another behavior will mean a logical error in the client-side code, so I think that it's not a big deal.

Another solution will cause more changes: e.g. method `to_string` in bip32 should return `String`, not a `Result`, so we'll have to get rid off of the `ToString` trait for `ExtendedPrivKey`. It may broke some client-side code, and I believe that's not what we want.

**Comment by apoelstra** [comment]
Please clean up the history.

**Comment by apoelstra** [comment]
ACK

**Comment by apoelstra** [comment]
See #94 -- this will need to be reverted and moved to 0.14. Sorry about that.

**Comment by popzxc** [comment]
Maybe then just reorder commits in such way that this feature will be after the commit that'll be marked as 0.13.2? Just for those people who possibly already use this feature.

**Comment by apoelstra** [comment]
We can't reorder commits in `master`.

**Comment by popzxc** [comment]
Ok then.

**Pull request merged**
