### PR TITLE
Bump hex-conservative to 0.3.0

### PR DESCRIPTION
**Pull request by tankyleo**

### CODE REVIEW

**Comment by tankyleo** [comment]
I ran `just update-lock-files` to update the lock files.

**Review by tcharding — APPROVED** [review]
ACK 7f289a9fdf86604cc1ecfb31c6df0ea5bb175465

**Comment by tcharding** [comment]
Thanks man!

**Review by apoelstra — APPROVED** [review]
ACK 7f289a9fdf86604cc1ecfb31c6df0ea5bb175465; successfully ran local tests

**Pull request merged**
