### PR TITLE
Implement constants for `ChildNumber` enum

### LINKED ISSUE #2750: Implement `ZERO_NORMAL` and `ZERO_HARDENED` constants (and variants for `ONE`) for BIP 32
Also unrelated to this PR but maybe we should have `ZERO_NORMAL` and `ZERO_HARDENED` constants (and variants for `ONE`) because 0 and 1 are super common for hardcoded values. (e.g. see BIP 48, 49, 84 and others... all of which are on my shitlist, but they are super popular and widely deployed.) (And, like BIP39, I personally use it because that's the nature of using commercially-available wallets.) Would save a lot of unwraps.

_Originally posted by @apoelstra in https://github.com/rust-bitcoin/rust-bitcoin/pull/2747#discussion_r1590992098_

### PR DESCRIPTION
**Pull request by KnowWhoami**
this aims to fix #2750

### CODE REVIEW

**Comment by apoelstra** [comment]
Did you mean to close this?

**Review by tcharding — APPROVED** [review]
ACK 75b45ff26270081dcc1b852f46907645fb7e574d

**Comment by tcharding** [comment]
Here is your CI fail, not sure why it doesn't show up in the CI run, I got it by running `just lint`

```bash
error[E0599]: no method named `unwrap` found for enum `bitcoin::bip32::ChildNumber` in the current scope
  --> bitcoin/examples/ecdsa-psbt-simple.rs:79:50
   |
79 |     let internal_index = ChildNumber::ONE_NORMAL.unwrap();
```

**Review by tcharding — APPROVED** [review]
ACK 39df0a9fbedb196e18dfdcb4049ee38e5320810d

**Pull request merged**
