### PR TITLE
Don't allow uncompressed pks in witness script addresses

### LINKED ISSUE #433: P2WSH address / script generation accepts PublicKey where compressed = false
Related: #427 #428 

All public keys in the witness stack are required to be compressed.

I can generate a P2WSH address and script by passing an uncompressed key.

Methods with the problem:

- `Script.to_v0_p2wsh()`
- `Address::p2wsh()`

Example:

```
[dependencies]
rand = "0.6"
bitcoin = { version = "0.23.0", features = ["rand"] }
```

```rust
use bitcoin::blockdata;
use bitcoin::network::constants::Network::Bitcoin;
use bitcoin::secp256k1::Secp256k1;
use bitcoin::util::key;
use bitcoin::Address;
use rand::rngs::OsRng;

struct Keypair {
    private: key::PrivateKey,
    public: key::PublicKey,
}

fn get_new_key() -> Keypair {
    let secp = Secp256k1::new();
    let mut rng = OsRng::new().expect("OsRng");
    let (secret_key, _) = secp.generate_keypair(&mut rng);
    let private = key::PrivateKey {
        compressed: false,
        key: secret_key,
        network: Bitcoin,
    };
    let public = private.public_key(&secp);

    return Keypair { private, public };
}

fn main() {
    let keypair = get_new_key();
    assert!(keypair.private.compressed == false);
    assert!(keypair.public.compressed == false);

    let pub_bytes = &keypair.public.to_bytes()[..];
    // This is uncompressed
    assert!(pub_bytes.len() == 65);

    // Make a P2PK manually
    let uncompressed_p2pk = blockdata::script::Builder::new()
        .push_slice(&pub_bytes)
        .push_opcode(blockdata::opcodes::all::OP_CHECKSIG)
        .into_script();

    // Should error but doesn't... SegWit can't take uncompressed pubkey
    let p2wsh1 = uncompressed_p2pk.to_v0_p2wsh();
    // Should error but doesn't... SegWit can't take uncompressed pubkey
    let address = Address::p2wsh(&uncompressed_p2pk, Bitcoin);

    println!(
        "Oops...\nWe got\n{:?}\nand\n{:?}\nwithout errors...",
        p2wsh1, address
    );
}
```

### PR DESCRIPTION
**Pull request by junderw**
Fixes #433

### CODE REVIEW

**Comment by elichai** [comment]
I don't know about this, the fact that it cotains a push for 65 bytes that happens to be a valid pubkey doesn't necessarily mean it's used in the script as a pubkey, so maybe also checking if it has OP_CHECKSIG/VERIFY after it,
but all of this is pattern matching which @apoelstra doesn't like for good reasons

So I'm ~0 at least without a good explanation of why this is actually useful in all scripts.

**Comment by junderw** [comment]
Perhaps adding a parameter called `allow_possible_uncompressed` and force the consumer to make a decision. Then document the parameter to say "it will reject if your script has any 65 byte pushdata with 0x04 for the first byte.

There have been instances in BitcoinJS where devs have used uncompressed pubkeys to generate p2sh-p2wpkh addresses and lost money. We fixed it for p2wpkh and p2wsh, and there's a bool for disabling validation, so a user who wanted to use a 65 byte pushdata with 0x04 as the first byte could try catch the specific error, then redo it without validation.

---

Interestingly enough the current tests for p2wsh script generation on master make a p2wsh-p2pk with an uncompressed pubkey. So don't send any money to it.

---

On a side note: I am new to rust and new to rust-bitcoin. Looking to using this with WASM to speed up our browser bundles. Nice to meet you all, btw.

**Comment by junderw** [comment]
This looks ugly. But I added a possible solution to allow for people who need to use a 65 byte 0x04 starting pushdata that isn't a valid pubkey used for checking signatures.

I'll roll it back if needed. Just some ideas.

Let me know what your thoughts are.

**Comment by apoelstra** [comment]
Concept NACK. Absent Miniscript (which has its own issue about this) there is no way to tell whether a push is being used as a public key or not.

**Comment by junderw** [comment]
Just to clarify, looking at core's source code, the uncompressed pubkey rule for segwit is only enforced when OP_CHECKSIG, OP_CHECKMULTISIG, or their VERIFY variants actually uses the pubkey to try and verify a signature.

Notably, this means that if I have a 1-of-10 multisig and the p2wsh address hash sets the first pubkey only as uncompressed into stone, this address is a blackhole and unspendable. But if the uncompressed key as the 10th key, any of the other 9 keys can sign, and since the code will not even reach the uncompressed key before it has enough signatures to validate, it will not be rejected. (Apparently @achow101 tried to get a change merged that would check every pubkey in every case)

---

While I agree that getting things correct is the way to go over fuzzy things like `maybe_has_uc_pubkey`, I would disagree that it is a direct requirement. Since rust-bitcoin is still in v0.x stage, it would be fairly reasonable to add in a fuzzy "trip up newbies when they are about to accidentally shoot themselves in the foot" at the expense of "in super rare (in fact I can't even think of one) cases where a veteran bitcoin coder decides their p2wsh must have a 65 byte pushdata with 0x04 at the beginning for some use besides signing... that coder has to fight with one more error." (Even if by making the consumer explicitly say "check for uc pubkey-ish data" by passing a bool etc. they will likely not have a problem figuring out the cause and solution for the error)... then when a more correct solution (via miniscript) is available, rework the API to accommodate.

---

As an additional note/question (I'm new to rust). What would be the most visible way that rustaceans would notice a warning in documentation for using a specific public method / function?

Perhaps an alternative would be:

1. fix the test that uses uc pubkey as a vector to test p2wsh (so as to try not to set bad examples)
2. add highly visible documentation to the two methods I modified that tells people not to use uncompressed pubkeys for signing operations.

**Comment by apoelstra** [comment]
Closing as this PR appears to now be tests-only

**Pull request closed without merging**
