### PR TITLE
Bump MSRV to 1.63

### PR DESCRIPTION
**Pull request by Kixunil**
The version 1.63 satisfies our requirements for MSRV and provides significant benefits so this commit bumps it. This commit also starts using some advantages of the new MSRV, namely namespaced features, weak dependencies and the ability to use trait bounds in `const` context.

This however does not yet migrade the `rand-std` feature because that requires a release of `secp256k1` with the same kind of change - bumping MSRV to 1.63 and removing `rand-std` in favor of weak dependency. (Accompanying PR to secp256k1: https://github.com/rust-bitcoin/rust-secp256k1/pull/709 )

Suggested plan:

* merge both PRs
* at some point release `hashes` and `secp256k`
* remove `rand-std` from `bitcoin`
* release the rest of the crates

### CODE REVIEW

**Review by tcharding — DISMISSED** [review]
This is a really nice improvement from a maintenance perspective, I'm excited about not writing `foo-std` features constantly. I only reviewed lightly but ACK from me.

ACK 966b2b5501044bc2f0e7fcf394e1970b2c0c951f

**Comment by yancyribbens** [comment]
Looks good.  However README.md needs updating also.

**Comment by Kixunil** [comment]
@yancyribbens OMG, `rg` output was so large they got lost. Thanks!

**Comment by Kixunil** [comment]
> nice improvement from a maintenance perspective

It also helps crates avoid weird bugs - users will get better API.

**Review by tcharding — DISMISSED** [review]
ACK 7107e6edeb58d16afaee4d901e868b77ad638804

**Comment by apoelstra** [comment]
Needs rebase.

**Comment by Kixunil** [comment]
I wonder if I should try to do the `secp256k1` without release by using git-based `[patch]`. Possibly as a separate PR.

**Comment by apoelstra** [comment]
Yeah, let's do it in a separate PR. But ACK doing it because we don't have a clear schedule for doing a rust-secp update. Nobody is pushing for one and we haven't done very much to the API over there.

**Review by apoelstra — APPROVED** [review]
ACK c72069e921d1fac8add62dde85c3ea388f364eb7

**Review by tcharding — APPROVED** [review]
ACK c72069e921d1fac8add62dde85c3ea388f364eb7

**Pull request merged**
