### PR TITLE
Remove deprecated code

### PR DESCRIPTION
**Pull request by tcharding**
We only keep deprecated code around for one release so we can now remove code deprecated in v0.30.0

Done in preparation as we gear up for v0.31.0 release.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 50ada8298f14d4ee35e3f14284119c2321205d0a

**Comment by yancyribbens** [comment]
The second commit doesn't remove deprecated code but instead moves it.  Ack for commit https://github.com/rust-bitcoin/rust-bitcoin/pull/1957/commits/1b7dc51ccbf116affcada27c2b75da0a2fc8ed8e although I'm sure about the second commit (no opinion rn).

**Comment by tcharding** [comment]
> The second commit doesn't remove deprecated code but instead moves it. Ack for commit [1b7dc51](https://github.com/rust-bitcoin/rust-bitcoin/commit/1b7dc51ccbf116affcada27c2b75da0a2fc8ed8e) although I'm sure about the second commit (no opinion rn).

Correct, the second commit moves code that was used by the deprecated code removed in patch 1 to the module where is now used.

**Review by sanket1729 — APPROVED** [review]
ACK 50ada8298f14d4ee35e3f14284119c2321205d0a

**Pull request merged**
