### PR TITLE
Use UFCS in macros

### LINKED ISSUE #3304: hashes: Check if we can remove trait imports
One can use Uniform Function Call Syntax (UFCS) and not import traits, we should check `hashes` over for other instances of this improvement.

Pointed out to me here: https://github.com/rust-bitcoin/rust-bitcoin/pull/3128#discussion_r1743138964

### PR DESCRIPTION
**Pull request by liamaharon**
Closes #3304

### CODE REVIEW

**Comment by apoelstra** [comment]
Why is this marked as draft? I guess because it's incomplete?

**Comment by liamaharon** [comment]
@apoelstra taking this PR out of draft. 

I couldn't find any other macros that required a trait to be in scope to use like in https://github.com/rust-bitcoin/rust-bitcoin/pull/3128#discussion_r1743138964, but there were some that I feel are cleaner with UFCS.

**Review by apoelstra — APPROVED** [review]
ACK 25d906d936eed34cf398e1a8b1abe8176c1b7c02 successfully ran local tests

**Review by tcharding — APPROVED** [review]
ACK 25d906d936eed34cf398e1a8b1abe8176c1b7c02

**Comment by tcharding** [comment]
Nice!

**Pull request merged**
