### PR TITLE
Split Prevouts errors out into specific error types

### PR DESCRIPTION
**Pull request by tcharding**
Done as part of the great error clean up.

Currently we are returning a general `Error` from `Prevouts` functions, this is un-informative, we can do better by returning specific types that indicate the exact error path.

### CODE REVIEW

**Comment by apoelstra** [comment]
Nice!

I wonder if the new dummy-struct error types should be marked `#[non_exhaustive]`? Fine by me either way.

**Review by apoelstra — DISMISSED** [review]
ACK 3d0d2d7df87555cdec143bc9177c9972f2ed1e2d

**Comment by tcharding** [comment]
> I wonder if the new dummy-struct error types should be marked #[non_exhaustive]? Fine by me either way.

Is the aim to non_exhaustive anything with the slightest chance of being changed? Either way I'd say before we go 1.0 someone will need to look hard at each error to decide if we are committed to not changing it, or else add `non_exhaustive`, FTR I did not think super hard about these errors, I'm doing error work when my brain is half dead so I'd prefer to put the thinking off to another time. (I'm playing with this method of splitting deep tasks and shallow tasks up into different work sessions.)

**Comment by tcharding** [comment]
They should also have `Copy` on them if they don't have `non_exhaustive`, that is what I stated before that I was doing. I'll wait for any more comments then do one or the other.

**Comment by apoelstra** [comment]
> They should also have `Copy` on them if they don't have `non_exhaustive`, that is what I stated before that I was doing. I'll wait for any more comments then do one or the other.

Yeah, agreed with this.

My feeling is that for *errors* we should default to `#[non_exhaustive]` unless somebody can argue otherwise (since in theory we can basically always add more context to errors, if somebody asks). And for other thingsn we should default to `Copy` unless somebody argues otherwise.

I'm also fine with "let's not think about it during this PR" :).

Note that we can add `Copy` after the fact as a non-breaking change.

**Comment by tcharding** [comment]
Two birds with one stone, this works for me and I also don't have to think that hard :)

**Comment by tcharding** [comment]
Force push adds `non_exhaustive`, no other changes.

**Comment by apoelstra** [comment]
Heads up that you didn't actually push :)

**Comment by tcharding** [comment]
Thanks :)

**Review by apoelstra — DISMISSED** [review]
ACK c71224a84930653962174634208f71d0c0457688

**Comment by tcharding** [comment]
I'm not sure if error handling should be considered "trivial API redesign" and considered for the refactor carve-out. I definitely think error handling is too boring and produces too many notifications to think anyone is going to review this other than for high level discussion. IMO this can merge. If it turns out the concepts are not liked I'll come back and do it all again.

**Comment by tcharding** [comment]
On ice until next release.

**Comment by Kixunil** [comment]
> My feeling is that for _errors_ we should default to `#[non_exhaustive]` unless somebody can argue otherwise (since in theory we can basically always add more context to errors, if somebody asks).

Exactly.

> I definitely think error handling is too boring

Not for me. But it's challenging (which IMO makes it not boring).

**Review by Kixunil — APPROVED** [review]
ACK e21ee381bcc07c3c541fd14fc7d5761ce6f085ed

**Comment by tcharding** [comment]
>> I definitely think error handling is too boring

> Not for me. But it's challenging (which IMO makes it not boring).

Oh I wasn't clear, I meant too boring for reviewers (outside of you and Andrew), I also find it interesting because its challenging. We've (I've) had a fair bit of struggle getting things reviewed while you were gone, hence the two carve-outs in `CONTRIBUTING`. One of the reasons, I believe, is the refactor and minor API things are 'too boring' for other reviewers. That is the 'too boring' I was referring to :)

**Pull request merged**
