### PR TITLE
Rearrange all the modules

### PR DESCRIPTION
**Pull request by apoelstra**
Alternate/more agressive version of #518 

This is a very invasive change but it's something I've wanted to do for years. Curious what others think.

### CODE REVIEW

**Comment by dpc** [comment]
Anything flattening the namespaces is a great improvement.

**Comment by stevenroose** [comment]
Hmm yeah this is fine. As for `network::VersionMessage` vs `network::message::Version`, I'm rather indifferent. Maybe slightly towards the former as in the latter, the `network::XXX` namespace is quite empty, though. It has `Network` (but that one is exposed as `bitcoin::Network` as well), `ServiceFlags` and `Address`.

Perhaps rename `mod message;` to `mod msg;`?

**Comment by stevenroose** [comment]
but yeah utACK d7389df8f9fdb2c8b76ae1c07b3de19f94e5652a (but slight preference to make message full names slightly shorter).

**Comment by apoelstra** [comment]
That's fair. I should put `VersionMessage` back because `Version` by itself is easy to confuse with service flags.

I'm also happy to rename `message` to `msg`.

**Comment by apoelstra** [comment]
Regarding `primitives` ... aside from the constants I don't expect people will be using `primitives::` paths directly since all of the actual primitives should be re-exposed at the root. So maybe it is okay to have a long name.

**Comment by apoelstra** [comment]
Let's bundle this with #494 in a "dramatically break the API but don't change functionality" release after the next release.

**Comment by justinmoon** [comment]
> Anything flattening the namespaces is a great improvement.

What do people think about getting rid of the `util` module? Half of our code lives in there ...

**Comment by apoelstra** [comment]
Yeah, I think it might be reasonable to make `util` private and re-export all of its submodules at the root.

**Comment by RCasatta** [comment]
> Let's bundle this with #494 in a "dramatically break the API but don't change functionality" release after the next release.

Maybe we can take the occasion for `cargo fmt`?

**Comment by dr-orlovsky** [comment]
Yeah, I was looking for something like this for a long time!!!

Few more suggestions of what can be bundled with this huge breaking change release:
1) Agree with @RCasatta above on `rust fmt`. And, it's review may be very much simplified by the reviewers if they will just checkout commit before `rust fmt`, apply `fmt` and make sure the result match the committed version. No need to review a plenty of code in this case.
2) What about adding `bitcoin_num` migration https://github.com/rust-bitcoin/rust-bitcoin/issues/467 ?
3) Such things as `bitcoin::amount::Amount` and `bitcoin:address::Address` does not make much sense, if we have `bitcoin::PublicKey` and not `bitcoin::key::PublicKey`.

**Comment by apoelstra** [comment]
@dr-orlovsky I'm definitely in favor of reexporting `Amount` and `Address` at the top level if they aren't already.

rustfmt is still really invasive. If there were a way we could phase it in over multiple commits or even multiple PRs I'd be much more willing to take it on.

**Comment by tcharding** [comment]
If we are bumping MSRV [soon](https://github.com/rust-bitcoin/rust-bitcoin/issues/510) and considering enabling rustfmt (#959) do we want to revisit this at the same time?

**Comment by apoelstra** [comment]
Yes -- though let's do a MSRV-only release first.

**Comment by tcharding** [comment]
I've started to bring this back to life:
- Patches 1-3 are in: #1296 
- Patch 7 is in: #1295

If these two are well received I can do patches 4-6 as well.

**Comment by apoelstra** [comment]
Probably we should close this specific PR though?

**Comment by tcharding** [comment]
Closing this, will re-do the network message stuff.

**Pull request closed without merging**
