### PR TITLE
Add needs-rebase bot

### PR DESCRIPTION
**Pull request by tcharding**
Add a bot by way of github actions that checks for PRs that have merge conflicts with `master` branch i.e., need rebase.

Action runs on various occasions using `pull_request` and `pull_request_review_comment`.

I think we can iterate on the action after we see it in action (pun intended :)

### CODE REVIEW

**Comment by thomaseizinger** [comment]
I think this might produce a lot of spam? :)

Perhaps a label would be better? Applying a label is idempotent whereas a comment is not.

**Comment by tcharding** [comment]
Good point. Does adding a label cause the author to get notified, or will we then have to manually check our open PRs for the label. I guess that's just a single `gh pr` command.

**Comment by thomaseizinger** [comment]
> Does adding a label cause the author to get notified

I don't think so.

I guess comments could still be fine. I often subscribe myself to PRs where I am only interested in when they are merging and there is a separate notification setting for that.

**Comment by apoelstra** [comment]
@thomaseizinger in my view the point is to create spam, so that we notice (or at least, the PR author notices) the conflict.

**Comment by tcharding** [comment]
Changes in force push:
- Re-wrote PR description
- Squashed into a single patch
- rebased

**Comment by tcharding** [comment]
Please do not merge without explicit ack by @apoelstra because we are using his username for the action.

**Comment by Kixunil** [comment]
IMO it'd be best to notify the author only. If a PR is dormant for a long time then the stale bot would be a better solution.

**Comment by tcharding** [comment]
hmm, I think we have old 'stale' PRs that are useful to keep open. At least I personally go through them from time to time and I think they are adding value by being there still, perhaps I'm wrong?

> IMO it'd be best to notify the author only.

That would be nice, do you know any way of doing that? I'm not that interested in learning how to write github actions myself, the one used in this PR just posts a message.

**Review by apoelstra — APPROVED** [review]
utACK 8d56dd3075978f0fd2f6456ff9bbfd8ca8b262db

But let's not merge this if @Kixunil is uncomfortable with the spam.

**Pull request closed without merging**
