### PR TITLE
Return the correct `LeafVersion` when building a Taproot `ControlBlock`

### PR DESCRIPTION
**Pull request by afilini**

### CODE REVIEW

**Review by Kixunil — APPROVED** [review]

**Comment by Kixunil** [comment]
I like having smaller commits but merging it myself would feel like imposing it on others. :)

**Review by sanket1729 — APPROVED** [review]
ACK 0af5a433b67e1503a3c7958b9b80928973d4bf64

**Comment by sanket1729** [comment]
Done. @Kixunil if you can `ACK <commit-hash>` it would be useful because it helps tools like https://github.com/bitcoin-core/bitcoin-maintainer-tools to generate a nice merge commit message as shown for this PR. 

I also recommend using it whenever you merge a commit, it allows you to sign off commits with your key.

**Comment by Kixunil** [comment]
Thanks for info! I will have to look into proper GPG *commits* setup with git and Qubes. Was only doing tags so far by manually copying repo to a different VM. :D

**Pull request merged**
