### PR TITLE
Feature: Add difficulty_float method for block::Header.

### PR DESCRIPTION
**Pull request by junderw**
Header had a passthrough method for difficulty so I added one for difficulty_float as well.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 05fdead2a4f062ccfbe3319d8b7b8ce63d5cabd3

**Review by sanket1729 — APPROVED** [review]
ACK 05fdead2a4f062ccfbe3319d8b7b8ce63d5cabd3. Don't mind the floating point comparison as it is in tests.

**Review by Kixunil — APPROVED** [review]
ACK 05fdead2a4f062ccfbe3319d8b7b8ce63d5cabd3

**Review by tcharding — APPROVED** [review]
ACK 05fdead2a4f062ccfbe3319d8b7b8ce63d5cabd3

**Comment by apoelstra** [comment]
Ok, cool, I'll merge it and #1721 before the release.

**Pull request merged**
