### PR TITLE
Backport #1941 to 0.30.x and release new patch version

### PR DESCRIPTION
**Pull request by apoelstra**
Needed to unstick https://github.com/rust-bitcoin/rust-miniscript/pull/482

### CODE REVIEW

**Comment by apoelstra** [comment]
CI failure is just the usual serde stuff, because this is targeted at an old branch.

**Review by tcharding — APPROVED** [review]
ACK 99ded547467b3d3560032c6eac841725370af797

**Review by sanket1729 — APPROVED** [review]
utACK 99ded547467b3d3560032c6eac841725370af797

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
