### PR TITLE
Trivial docs fixes

### PR DESCRIPTION
**Pull request by tcharding**
Do 2 trivial docs fixes, found while investigating  #2103

### CODE REVIEW

**Comment by tcharding** [comment]
PR is eligible for the One ACK carve-out (ack and merge at any time).

**Review by junderw — APPROVED** [review]
I'm not an ACKer but ACK anyways :-P

**Review by sanket1729 — APPROVED** [review]
ACK be8aee696860aca6dcf32750a0ee814ca503959b

**Comment by tcharding** [comment]
IMO all the reviews help, more eyes hopefully means less bugs. If you review on the command line you might like this function I use to ack
```bash
ack-tip () {
        git log -1 --format=full @
        read "ack?Really ACK this commit? "
        if [[ "$ack" =~ ^[Yy]$ ]]
        then
                gh pr review -a -b "ACK $(git rev-parse @)"
        fi
}
```

**Pull request merged**
