### PR TITLE
consensus::Params should be non_exhaustive

### PR DESCRIPTION
**Pull request by hrouis**
fixes: https://github.com/rust-bitcoin/rust-bitcoin/issues/1213

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 445037fb700d1fa59ba34001f9c7f0daa7ef3ac6

**Comment by tcharding** [comment]
Thanks for the contribution @hrouis! If you put `fixes: #1213` in the PR description github will autoclose the issue for us.

There are a bunch of other keywords one can use instead of 'fixes', here is a list https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/using-keywords-in-issues-and-pull-requests

**Review by tcharding — APPROVED** [review]
ACK 445037fb700d1fa59ba34001f9c7f0daa7ef3ac6

**Comment by hrouis** [comment]
Thank you for the pointers and links, will definitely apply them for the next PRs

**Review by Kixunil — APPROVED** [review]
ACK 445037fb700d1fa59ba34001f9c7f0daa7ef3ac6

I don't mind the commit message here, this is almost as trivial as fixing a typo. :)

**Comment by tcharding** [comment]
> Thank you for the pointers and links, will definitely apply them for the next PRs

Thanks man, hope I didn't come across too nit-picky :)

**Pull request merged**
