### PR TITLE
Remove `hashes::hex::HexWriter`

### PR DESCRIPTION
**Pull request by tcharding**
The `HexWriter` is not used any more since we added the new hex code in internals for fast hex encoding.

While we are removing the benches for `HexWriter` also remove the last remaining bench for writing using `Display` because this is not the correct place for that code - its trivial to re add later in the correct module.

### CODE REVIEW

**Review by Kixunil — APPROVED** [review]
ACK e079524b2a44f7085782ef366e8df9b3df53c0c6

**Comment by Kixunil** [comment]
For the hex crate we should have this available but in improved form: generic over `fmt::Write`. Same with reading and iterators.

**Comment by tcharding** [comment]
Am I understanding you correctly, you are happy to remove this now but I should raise an issue to re-implement it in the hex crate generic over `fmt::Write`?

**Comment by Kixunil** [comment]
Exactly.

**Comment by tcharding** [comment]
Done, thanks.

**Review by apoelstra — APPROVED** [review]
ACK e079524b2a44f7085782ef366e8df9b3df53c0c6

**Pull request merged**
