### PR TITLE
Bump MSRV to 1.48.0

### PR DESCRIPTION
**Pull request by tcharding**
Just patch 2, patch 1 is #1728  

From the commit log of patch 2

    Bump MSRV to 1.48.1
    
    As per discussion [0] bump our MSRV for all crates in `rust-bitcoin`
    repo to 1.48.1 [1].
    
    [0] https://github.com/rust-bitcoin/rust-bitcoin/discussions/1329
    [1] https://blog.rust-lang.org/2020/11/19/Rust-1.48.html

### CODE REVIEW

**Comment by Kixunil** [comment]
Concept ACK, will wait for rebase. I'd like to take look into actually making use of this changes.

**Comment by tcharding** [comment]
Another question please @Kixunil, why do `Index` impls get a `track_caller` attribute? Is it because `Index` uses the user input index without bounds checking and if out of bounds panics and the resulting stack trace points to the trait in stdlib and not the line of code where `Index` paniced?

**Comment by tcharding** [comment]
Rebased on master and removed `rust_1_46`.

**Review by apoelstra — APPROVED** [review]
ACK 1dc04fe10ff906e92ceef18b0a8cfa0e56b9de99

**Review by sanket1729 — APPROVED** [review]
ACK 1dc04fe10ff906e92ceef18b0a8cfa0e56b9de99

**Comment by Kixunil** [comment]
@tcharding if you know what to look for feel free to do it yourself, I kinda felt like I was the only one who had an idea because of my enthusiasm. :) There are already some things tracked in #1060 but I was thinking more about arrays/const generics - we should be able to add `AsRef<[u8]> + AsMut<[u8]> + Borrow<[u8]> + BorrowMut<[u8]>` bound to `Hash::Bytes`, also `where &[u8]: TryInto<Self::Bytes, Error=core::array::TryFromSliceError>`.

But I think I did see some other places that would be less annoying now, don't remember where. Also note that neither `hex` nor `PushSlice` can use it since they require specific lengths.

**Comment by tcharding** [comment]
No worries, I don't know what to look for but its a good chance for me to read the release notes of Rust 1.41 -> 1.48 and try to learn. Won't be the last time we bump MSRV. I definitely won't claim to find everything that can be improved.

**Pull request merged**
