### PR TITLE
Add constructor to `FeeRate`

### PR DESCRIPTION
**Pull request by rustaceanrob**
This is partially to check my understanding. I did poorly in physics class as part of my misunderstanding of unit conversions. 

The `feefilter` message expresses the fee as satoshis per 1,000 vbyte, see the [p2p handling](https://github.com/bitcoin/bitcoin/blob/1dda1892b6bcc3d4f9678960cc9e9920f491e87e/src/net_processing.cpp#L5331) which calls [this function](https://github.com/bitcoin/bitcoin/blob/master/src/policy/feerate.h#L63) on the mempool. I presume all that needs to happen to express this in `kwu` is to divide by 4, but ideally a `FeeRate` may be constructed directly from a `feefilter` message using a constructor. 

My conversion is (sat / kvb * kvb / 4 kwu)

### CODE REVIEW

**Comment by yancyribbens** [comment]
I think your math checks out.  1vb = 4wu implies 1 kvb = 4kwu therefore 1/4kvb = 1kwu.

**Review by storopoli — APPROVED** [review]
Concept ACK.
Nice docstrings

**Review by apoelstra — APPROVED** [review]
ACK b96501981ffef1d32c839cd44861736ce3683964; successfully ran local tests

**Review by tcharding — APPROVED** [review]
ACK b96501981ffef1d32c839cd44861736ce3683964

**Pull request merged**
