### PR TITLE
Automated daily update to rustc (to nightly-2024-09-01)

### PR DESCRIPTION
**Pull request by apoelstra**
Automated update to Github CI workflow `rust.yml` by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Review by tcharding — DISMISSED** [review]
ACK 3940b4cba16658fe0dfe3d875cdf41a74abc9278

**Comment by tcharding** [comment]
Needs #3268

**Comment by apoelstra** [comment]
Nice. Success for the cronjob workflow!

**Review by tcharding — APPROVED** [review]
ACK eccd3c4a3d9e315715e85bad8de92c0c4b71b361

**Pull request merged**
