### PR TITLE
INCOMPLETE DEMO - DO NOT MERGE: Split up CI tasks and unify test scripts

### PR DESCRIPTION
**Pull request by Kixunil**
I started doing this and then I found Tobin is doing the same thing, so
I stopped. This is INCOMPLETE and UNTESTED. Things that I would do if I
continued:

* Delete `contrib/*/test.sh`
* Add `contrib/*/test_vars.sh`
* Test and fix any outstanding bugs

### CODE REVIEW

**Comment by Kixunil** [comment]
I've fixed at least the Prepare job which is the hard part so that a working solution to generate the matrix can be demonstrated.

**Comment by Kixunil** [comment]
Forgot to point out that this implements single source of truth for crates, so no more adding of new crates to a bunch of places. (IME SSOT is super-important in programming.)

**Comment by tcharding** [comment]
I agree wholeheartedly, except on the name, I always call it Single Point Of Truth (SPOT) :)

**Comment by tcharding** [comment]
Closing in favour of #2353

**Pull request closed without merging**
