### PR TITLE
Revert "Remove unnecessary m/ prefix requirement"

### PR DESCRIPTION
**Pull request by tcharding**
This reverts commit ccbd09d5fbdb7ec26362b6b6719755e000f56e9c.

There were merits to the change in #2451, and the bip is somewhat unclear on the matter, however the change breaks our ability to parse output from Bitcoin Core RPC call `getaddressinfo`.

For the release to progress we need to revert this change.

### CODE REVIEW

**Comment by apoelstra** [comment]
CI failure is real.

**Comment by tcharding** [comment]
Ha, your too quick today. Fixed now.

**Comment by tcharding** [comment]
I had a go at explaining why patch 2 is needed, its a guess though.

**Comment by apoelstra** [comment]
I don't think it's correct that the first part *must* be `m`. This makes it impossible to express partial paths (or paths which start with fingerprints; but we don't support this anyway).

**Comment by tcharding** [comment]
> I don't think it's correct that the first part must be `m`. 

I agree but was just going to revert for this release and fix it in the next on (hence #2673). Would you prefer to see it fixed this release?

**Comment by apoelstra** [comment]
> I agree but was just going to revert for this release and fix it in the next one (hence #2673). Would you prefer to see it fixed this release?

I would prefer that we be able to parse with or without a `m` in this release. Not clear what "fix" will mean but at least for now let's be able to parse all the paths that are out there.

**Comment by tcharding** [comment]
Replaced by #2677

**Pull request closed without merging**
