### PR TITLE
script: give `Builder` ability to verify-ify opcodes

### PR DESCRIPTION
**Pull request by apoelstra**

### CODE REVIEW

**Comment by stevenroose** [comment]
What do you envision this is useful for? It doesn't seem to be a good idea to encourage people to do operations on scripts they don't fully know beforehand.

**Comment by apoelstra** [comment]
By definition a `script::Builder` is a script the user "doesn't fully know". If they fully knew it it would be a `Script`.

**Comment by stevenroose** [comment]
I don't think many people build a script if they don't know what script they are going to build beforehand.. I mean that almost all usage of `Builder` is with hard-coded opcodes and variable data pushes.

If you know all your script opcodes upfront, you can just as well manually verify-ify the last opcode and if you don't know all upcodes upfront, you're doing dangerous stuff.

**Comment by apoelstra** [comment]
Updated to fix bug where slices that ended in a `CHECKSIG` byte (or similar) would be modified by the function.

@stevenroose This function is semantically equivalent to `.push_opcode(opcodes::all::OP_VERIFY)` except that it saves a byte when possible, something that is subtle and difficult and tedious to do by hand. Similarly we have `.push_int` which finds the most efficient way to push a given integer. I really don't understand how it's dangerous for the user not to want to deal with this accounting himself.

**Pull request merged**
