### PR TITLE
rustfmt: Use `show_parse_errors`

### PR DESCRIPTION
**Pull request by tcharding**
There are no behaviour changes with this patch applied.

In https://github.com/rust-lang/rustfmt/pull/5961 the `hide_parse_errors` was changed to `show_parse_errors` with default `true`.

Since we run the formatter with nightly we are getting the following warning

 Warning: the `hide_parse_errors` option is deprecated. Use
 `show_parse_errors` instead

Rename the variable and keep the default value `true`.

### CODE REVIEW

**Review by Kixunil — APPROVED** [review]
ACK e2c36941842a8a458222bff6f0386e0c92fd283b

**Review by storopoli — APPROVED** [review]
ACK e2c36941842a8a458222bff6f0386e0c92fd283b

Great that warning was driving me nuts!

**Review by apoelstra — APPROVED** [review]
ACK e2c36941842a8a458222bff6f0386e0c92fd283b

**Comment by tcharding** [comment]
Needs doing in all the other repos in our org.

**Comment by jamillambert** [comment]
All other affected repos in https://github.com/rust-bitcoin have been updated and PRs opened.

**Pull request merged**
