### PR TITLE
Use new `hex-conservative` crate

### PR DESCRIPTION
**Pull request by tcharding**
Use the newly released `hex-conservative` crate, by doing the following:
    
- Depend on `hex-conservative` in `bitcoin` and `hashes`
- Re-export `hex-conservative` as `hex` from both crate roots.
- Remove all the old hex code from `hashes`
- Remove all the old hex code from `internals`
- Remove the now unused `internals::prelude`
- Fix all the import statements (makes up the bulk of the lines changes in this patch)

### CODE REVIEW

**Comment by apoelstra** [comment]
I think we should rename it to `Iter` and yeah, we should export it at the crate root.

**Comment by apoelstra** [comment]
Nice! This looks good now.

**Comment by tcharding** [comment]
Thanks man, looks sweet huh.

**Comment by tcharding** [comment]
This will need the lock files updating still, hopefully https://github.com/rust-bitcoin/rust-bitcoin/pull/1916 will be in by then so msrv pinning stuff is resolved.

**Comment by apoelstra** [comment]
I think we should do the hex stuff before any other releases.

**Comment by tcharding** [comment]
Something is wrong with the `core2` build and I can't seem to see it, does anything cry out?
```diff
git diff @~ hashes/Cargo.toml
diff --git a/hashes/Cargo.toml b/hashes/Cargo.toml
index 0516af97..ac8591b9 100644
--- a/hashes/Cargo.toml
+++ b/hashes/Cargo.toml
@@ -14,9 +14,10 @@ exclude = ["tests", "contrib"]
 
 [features]
 default = ["std"]
-std = ["alloc", "internals/std"]
-alloc = ["internals/alloc"]
+std = ["alloc", "internals/std", "hex/std"]
+alloc = ["internals/alloc", "hex/alloc"]
 serde-std = ["serde/std"]
+core2 = ["actual-core2", "hex/core2"]
 
 [package.metadata.docs.rs]
 all-features = true
@@ -24,12 +25,15 @@ rustdoc-args = ["--cfg", "docsrs"]
 
 [dependencies]
 internals = { path = "../internals", package = "bitcoin-internals", version = "0.1.0" }
+hex = { package = "hex-conservative", version = "0.1.0", default-features = false }
 
-core2 = { version = "0.3.0", default_features = false, optional = true }
 schemars = { version = "0.8.3", optional = true }
 # Only enable this if you explicitly do not want to use "std", otherwise enable "serde-std".
 serde = { version = "1.0", default-features = false, optional = true }
 
+# Do NOT use this feature! Use the `core2` feature instead.
+actual-core2 = { package = "core2", version = "0.3.0", default-features = false, optional = true }
+
```

**Comment by apoelstra** [comment]
@tcharding did you update Cargo-recent.lock and Cargo-minimal.lock after making those changes to Cargo.toml?

**Comment by tcharding** [comment]
Yeah I did, I couldn't get `hashes` to build even with `cargo check` locally so I figured it was something brain dead and I was just blind to it. I'll play more with it today.

**Comment by tcharding** [comment]
FTR the solution was
```rust
extern crate actual_core2 as core2;
```
But yesterday I hade `extern crate core2;`

**Comment by apoelstra** [comment]
Awesome, glad CI is passing.

I'm temped though to get hex-conservative 0.1.1 out first (with the new `hex!` macro and fixing the `fmt` impls to respect `{:8}`)

**Comment by tcharding** [comment]
Agree, mind if I call it v0.2.0? I've given up understanding Rust semver rules for under v1.0, just feels too trivial increasing only the patch number :)

**Comment by apoelstra** [comment]
LGTM. May be a bit easier to review split into multiple commits, one for each crate, and a final one which deletes the hex stuff from -internals.

**Review by apoelstra — DISMISSED** [review]
ACK bd8a74bdefa2be53ffd60bd9f3ca2a771b9f5dda

**Comment by tcharding** [comment]
Can do!

**Comment by tcharding** [comment]
I had a go but we can't split it up without removing the workspace patch of `hashes` because of the `hash_newtype!` macro.

**Comment by tcharding** [comment]
I pulled the `internals` changes out into a separate patch, its all red :)

**Comment by tcharding** [comment]
And I removed the unnecessary `actual-core2` dependency trick from `bitcoin` because its unneeded since we only ever expect users to use "no-std" to activate the "core2" dependency - added an initial patch to this PR that comments the "core2" feature as such.

**Review by apoelstra — APPROVED** [review]
ACK bb8bd1630206f4fc72bffed814a581bd77c3a04c

**Comment by tcharding** [comment]
Draft because we may be able to make the `hex-conservative` library available as `hex` after all - @stevenroose prompted me to look into it just now.

**Comment by tcharding** [comment]
The hex lib rename thing got closed so this is good to go.

**Comment by tcharding** [comment]
@sanket1729 would you mind taking a look at this if you get a chance please? The green in the diff is almost all import statements and error type renames. The red is 1000+ lines of mostly removing all the stuff that has been released already in `hex-conservative` - I don't think you need to put much thought into those lines.

One thing stand out as non-obvious, the implementation of `FromHex` in `internal_macros` has a lot of code removed and we call through to `FromHex` which has exactly the same code as that removed, might have to open the editor to confirm that.

Thanks man.

**Review by sanket1729 — APPROVED** [review]
utACK bb8bd1630206f4fc72bffed814a581bd77c3a04c

**Comment by tcharding** [comment]
Oh my goodness we can merge this now, this has been a loooooong time coming :)

**Pull request merged**
