### PR TITLE
Hex fixups

### PR DESCRIPTION
**Pull request by Kixunil**
This fixes minor mistakes that I made in previous PR.

### CODE REVIEW

**Comment by Kixunil** [comment]
Thanks, sadly it's still not that great: #1270 

I actually previously suggested to remove the default features so that we won't have to write annoying `default-features = false` everywhere. I could rewrite the tests to not require `alloc`, I wrote them using `String` out of laziness. But I'd rather do that later as it doesn't seem so important.

(If anyone wants to do it, ask me first, I have a cool idea.)

**Review by apoelstra — APPROVED** [review]
ACK 6b96050d1f9c74a0c2392773f529b52470142592

**Review by tcharding — APPROVED** [review]
tACK 6b96050d1f9c74a0c2392773f529b52470142592

Do we need to add "alloc" to the `[package.metadata.docs.rs]` section of the manifest also?

**Comment by Kixunil** [comment]
No because `std` depends on it already.

**Comment by tcharding** [comment]
I went reading and I think we can use `all-features = true` now that we don't have "unstable" feature.

**Pull request merged**
