### PR TITLE
Clear clippy warnings from `--all-targets`

### PR DESCRIPTION
**Pull request by tcharding**
Clear all the clippy warnings (excl. #1042) that are returned by running `cargo clippy --all-targets`. 

I apologize in advance for the review burden :)

### CODE REVIEW

**Review by dpc — APPROVED** [review]
Looked through it and LGTM

**Review by elichai — APPROVED** [review]
ACK 271d0ba0685d9504deec15a23af71de89c138bb0

Reviewed all the changes and none of them seem to be behavior changing, and using clippy is great

**Comment by tcharding** [comment]
Thanks guys! Just got all the feature gate code to go and then hopefully we can get clippy running on CI.

**Review by apoelstra — APPROVED** [review]
ACK 271d0ba0685d9504deec15a23af71de89c138bb0

**Comment by apoelstra** [comment]
Yep, lots of commits but all small and non-controversial.

**Pull request merged**
