### PR TITLE
Remove unused rand dependency

### PR DESCRIPTION
**Pull request by jonasnick**

### CODE REVIEW

**Comment by stevenroose** [comment]
Can't we have `bitcoin::PrivateKey::generate`? I'd like that :)

**Comment by jonasnick** [comment]
Travis fails because the fuzzer seems to actually trigger a crash. I don't really see why as I haven't touched any functioning code. I can't find any helpful fuzzer output. The content of the file `hfuzz_workspace/outpoint_string/SIGABRT.PC.7ffff7dbc82f.STACK.dae3564e1.CODE.-6.ADDR.(nil).INSTR.mov____0x108(%rsp),%rcx.fuzz` is
```
$ xxd 'hfuzz_workspace/outpoint_string/SIGABRT.PC.7ffff7dbc82f.STACK.dae3564e1.CODE.-6.ADDR.(nil).INSTR.mov____0x108(%rsp),%rcx.fuzz'
00000000: 3636 3636 3631 3931 3432 3931 3432 3931  6666619142914291
00000010: 3432 3934 3130 3932 3135 3037 3736 3636  4294109215077666
00000020: 3139 3134 3239 3134 3239 3134 3239 3431  1914291429142941
00000030: 3039 3231 3531 3737 3736 3631 3931 c2bf  09215177766191..
00000040: 3a2b 00                                  :+.
```

**Comment by stevenroose** [comment]
I thought for a sec it might have been https://github.com/rust-bitcoin/rust-bitcoin/pull/271, but that one's not merged yet. I don't understand the fuzzer quite that well..

**Comment by apoelstra** [comment]
Oof. This is a bug in the `FromHexIterator` in bitcoin_hashes which uses `.len()` (byte length) to determine if we have an even-length string but then the `.chars()` iterator to take characters, meaning that multibyte characters may fool our even/odd detection.

**Comment by jonasnick** [comment]
Hmm, suddenly it says "All checks have passed" ... Let's try again.

**Comment by jonasnick** [comment]
looks like it's working

**Comment by apoelstra** [comment]
We can deal with changes to rust-secp the next time we update our rust-secp dependency; for now we should just fix the badly out-of-sync `rand` dependency in rust-bitcoin.

**Pull request merged**
