### PR TITLE
Fix TapTree derserialization

### PR DESCRIPTION
**Pull request by sanket1729**
Trees should only be serialized if both of the following conditions
hold:
1) Tree is complete binary tree(is_finalized)
2) Tree does not have any hidden nodes

### CODE REVIEW

**Comment by sanket1729** [comment]
Currently, this is not an issue because we cannot serialize/deserialize hidden nodes. But in the future, when we add support for serde of hidden nodes, this will be an issue.

**Comment by sanket1729** [comment]
Requesting reviews from @apoelstra and @tcharding to get a 0.28 release out

**Comment by tcharding** [comment]
ACK c97589f8de4f62e3448ec397df5db288ebe2b20c

**Comment by sanket1729** [comment]
@tcharding can you approve using the github UI?

**Review by tcharding — APPROVED** [review]

**Comment by tcharding** [comment]
Woops, done.

**Review by apoelstra — APPROVED** [review]
ACK c97589f8de4f62e3448ec397df5db288ebe2b20c

**Pull request merged**
