### PR TITLE
Convert numeric representation of ServiceFlags to bitwise OR of the f…

### PR DESCRIPTION
**Pull request by kiminuo**
…lag names

Integer numbers are harder to understand than flag names

### CODE REVIEW

**Comment by kiminuo** [comment]
@stevenroose @apoelstra Do you like the change?

**Comment by elichai** [comment]
ConceptACK. Haven't checked that it's the correct Flags

**Comment by apoelstra** [comment]
Yeah, concept ACK

**Comment by kiminuo** [comment]
Rebased

**Pull request merged**
