### PR TITLE
Use correct terminology: carve out

### PR DESCRIPTION
**Pull request by tcharding**
One "carves out" something, not "carve output" - woops.

### CODE REVIEW

**Comment by apoelstra** [comment]
I think it should be "carveout" as one word. Or use a hyphen.

Weirdly I cannot (in 30 seconds of searching) find a dictionary reference to support using "carve-out" as a noun like this, but I'm sure that it's legit.

**Comment by tcharding** [comment]
Ha! I had also previously done a 30 second search and was particularly amused by the top result 

https://duckduckgo.com/?q=carve+out+def&t=canonical&ia=web

> to create or obtain something that helps you by skillful activities

**Comment by tcharding** [comment]
And for a more in depth answer this one is good:

https://english.stackexchange.com/questions/472783/carve-out-vs-carve-out-as-an-action

**Comment by apoelstra** [comment]
Nice. I believe we are using it as a noun here, and that SE post supports the use of a hyphen (though it seems to just mention this as an aside).

**Review by apoelstra — APPROVED** [review]
ACK b229fd55559faf89d4460c8efa2cf5206fb51e62

**Comment by tcharding** [comment]
Can be merged under the one ack carve-out

**Pull request merged**
