### PR TITLE
hashes: Wrap `hex` error

### PR DESCRIPTION
**Pull request by tcharding**
Draft because on top of https://github.com/rust-bitcoin/rust-bitcoin/pull/3579, this one is just the last patch.

We would like to make `hex` an optional dependency. In order to do so we must not expose the `hex::HexToArrayError` in the public API.
    
Add a new `HexError` type (with hidden innards) and convert the `hex` error to the new error. This is complicated by the fact that the error is converted in public code (via a macro) so we cannot access the innards of the new error. As such we add a bunch of ugly as hell constructors (and getters).

### CODE REVIEW

**Comment by tcharding** [comment]
Not happy with this.

**Comment by apoelstra** [comment]
Yeah, gross.

I think we should just leave the hex error exposed. We can continue to feature-gate `hex` (in which case string de/serialization won't work) but if we have methods that literally just pass through a hex error ... I think we should just pass through the hex error.

**Comment by tcharding** [comment]
> Yeah, gross.

So good, describes exactly how I felt.

I realized this morning that I had this by the wrong end of the stick, I'm going to try just feature gating the `FromStr` / `Display` etc and then only implementing a minimal `Debug` - which is, I think, exactly what you say above.

**Comment by tcharding** [comment]
Oooo, I remember now, if we try to feature gate `FromStr` and `Display` on an optional `hex` dependency (and still implement `Debug` unconditionally) it wreaks havoc with the `Hash` trait.

Is this make-hex-optional really worth the effort?

**Pull request closed without merging**
