### PR TITLE
Move `TxIn` and `TxOut` to `primitives`

### PR DESCRIPTION
**Pull request by tcharding**
Turn the crank; move `TxIn` and `TxOut` to `primitives`.

### CODE REVIEW

**Comment by tcharding** [comment]
944 green lines of trivial ;)

**Comment by apoelstra** [comment]
Done reviewing 7ce4c99dc8bc33ddfb73e4f49660ddf4fbe97054

**Comment by tcharding** [comment]
The whole `primitives` crate is basically useless without `alloc` feature. You are correct though, this does make it slightly worse. I thought it better not to put feature guards on what will be almost everything in the `transaction` module just so that `OutPoint` is available. I almost think we should just put "alloc" requirement on the whole crate really.

**Comment by tcharding** [comment]
Had to rebase I'm afraid because of merge conflicts.

**Comment by tcharding** [comment]
Hey @apoelstra, just this one then we can move `Transaction` - I think we are actually getting close.

**Comment by tcharding** [comment]
CI fail is unrelated, its the `-j1` thing. https://github.com/rust-bitcoin/rust-bitcoin-maintainer-tools/pull/18

**Review by apoelstra — APPROVED** [review]
ACK 4c72b2e1eff725f69f757f5ff4d5d207166bc00d; successfully ran local tests

**Review by apoelstra — APPROVED** [review]
ACK 003dc9cf4d80c2a6d614de1e3a1c7c4b1d5372e0; successfully ran local tests

**Pull request merged**
