### PR TITLE
Clear all lint errors and warnings

### PR DESCRIPTION
**Pull request by tcharding**
Backport a bunch of patches to get the clippy job passing.

- the first two patches from #2785 
- Update `nightly-toolchain` 
- the single patch from #2667

After rebase I just manually fixed all remaining lint warnings/errors

### CODE REVIEW

**Comment by tcharding** [comment]
Requested here: https://github.com/rust-bitcoin/rust-bitcoin/pull/3379#issuecomment-2358533789

**Comment by apoelstra** [comment]
Lol. I guess we should decide what to do about the `cfg(feature = "no-std")` code which can't ever be enabled except via cursed `RUSTFLAGS` settings.

Probably we should just delete that code.

**Comment by tcharding** [comment]
Didn't see your comment before I force pushed. Thinking now ...

**Comment by apoelstra** [comment]
Oh, right, the bad code was just unit tests. So backporting my "enable and fix" is probably the right way to go. Let's see if CI likes it.

**Comment by tcharding** [comment]
With the other patch from your original PR this is good now, there are no remaining `feature = "no-std"`

**Comment by tcharding** [comment]
Oh boy, if we are going to keep 0.32.x around for ages we should backport the CI re-write as well ...

**Comment by tcharding** [comment]
Picked up #2667 as well and changed the scope of the PR (title and description).

**Comment by tcharding** [comment]
Note please the last 2 patches were created manually, not by backporting.

**Review by apoelstra — APPROVED** [review]
ACK d99b256c45c48030de52ff2438fa6b3d7d7a0aa4 successfully ran local tests; nice! especially updating the rust-nightly version, which probably was not strictly necessary. will one-ack merge

**Pull request merged**
