### PR TITLE
Add `PartialMerkleTree::calc_tree_height` method

### PR DESCRIPTION
**Pull request by tcharding**
Add a private `PartialMerkleTree::calc_tree_width` function and a unit test to test it.

### CODE REVIEW

**Comment by tcharding** [comment]
Rebased on top of #1388, no changes to the last 2 patches which make up this PR.

**Comment by tcharding** [comment]
Seems no one is that keen on this one. Closing

**Comment by tcharding** [comment]
Oh woops, its just that we have to wait for https://github.com/rust-bitcoin/rust-bitcoin/pull/1388

**Review by apoelstra — APPROVED** [review]
ACK 752adff9d1f322b6ee0caab96e3fedfb5e0c8948

**Review by clarkmoody — APPROVED** [review]
ACK 752adff9d1f322b6ee0caab96e3fedfb5e0c8948

**Pull request closed without merging**
