### PR TITLE
 Separate all bitcoinconsensus validation stuff in module

### PR DESCRIPTION
**Pull request by stevenroose**
Includes https://github.com/rust-bitcoin/rust-bitcoin/pull/327.

Not sure if it's the right place to put the module, but I think it makes
more sense to have all validation stuff inside the same module and have
a `validation::Error` type for validation methods.

### CODE REVIEW

**Comment by tamasblummer** [comment]
if you are fancy this could also have functions

- to do locktime check, asking if a transaction is valid to be included into a block with given height or under assumption of an block time average.
- to check if the transaction has no output less than DUST limit
- pays at least x sats/vByte

**Comment by elichai** [comment]
I think you forgot to commit the validation.rs file. :)

**Comment by stevenroose** [comment]
Haha, of course I did! Fixed.

**Comment by tamasblummer** [comment]
@stevenroose this does not compile, please fix or close

**Comment by stevenroose** [comment]
updated

**Review by tamasblummer — DISMISSED** [review]

**Comment by apoelstra** [comment]
Needs rebase.

concept ACK.

@stevenroose one thing I like about this is that it removes `#[cfg(...)]` markers on enum variants. I think these are problematic because it makes it a breaking change to enable/disable features, for users who are matching on these enums. Because of how cargo resolves features, it means that a user might find their build breaks when they add an unrelated dep.

In https://github.com/rust-bitcoin/rust-bitcoin/pull/413 you add some new instances of feature-gated enum variants. I wonder if we should change that too?

**Comment by stevenroose** [comment]
Rebased and updated this PR.

**Review by apoelstra — APPROVED** [review]
ack 310f9926049cd379675c242154f7d37f3cda0fc4

**Comment by JeremyRubin** [comment]
I think it might be a superior approach for compatibility to implement the functions in the validation module on the type rather than as standalone funcs.

e.g.

```rust
pub struct Foo;
 impl Foo {
     pub fn foo(){
         println!("foo");
 
     }
 }
 
 mod extend {
     impl super::Foo {
         pub fn bar() {
             println!("bar");
 
         }
     }
 }
 fn main() {
     Foo::bar();
     Foo::foo();
 }
```

**Comment by stevenroose** [comment]
Hmm, in what way do you mean "for compatibility"?

**Comment by JeremyRubin** [comment]
the method names do not change, nor does how you call them. less impact on the crate's current users.

**Comment by stevenroose** [comment]
Oh yeah this PR is so old I forgot it removes existing methods. How about
adding them so that we have the bare module functions and the existing
methods that refer to them?

**Comment by JeremyRubin** [comment]
not sure what you're suggesting -- it's fine that this is a breaking change w.r.t. a feature flag on the crate, I'm more pointing out that you can just move the impls to a split out feature module and not rename or remove any exisiting method.

**Comment by stevenroose** [comment]
@JeremyRubin I added the methods you suggested. Now they're duplicated with the raw module functions though. I somehow feel that it makes sense to bundle validation in one module and just have it there as module functions. Perhaps I should mark the type methods as deprecated? Thoughts? @apoelstra @elichai @sgeisler ?

**Comment by elichai** [comment]
Concept ACK for splitting, 
I don't really like that now `impl Transaction` and others are scattered in multiple modules, I'd rather have a `Trait Validation` if we really want to have methods on the objects themselved

**Comment by JeremyRubin** [comment]
The issue with `trait Validation` is there isn't a consistent API on the methods -- you could do `trait TransactionValidation` though?

@stevenroose I guess I was saying that I don't see a reason to introduce the non type methods at all? Is this a general direction we're going or is there a plan to make this a separate crate?

**Comment by stevenroose** [comment]
Yeah sure, go ahead use whatever I put here.

**Comment by tcharding** [comment]
Done in #1912

**Pull request closed without merging**
