### PR TITLE
Remove schemars all together 

### LINKED ISSUE #3393: CI on master is broken because of schemars again
cc #3200 most recent instance before this (40 days ago).

Let's just delete schemars.

### PR DESCRIPTION
**Pull request by tcharding**
We introduced schemars as a personal favor to a user, and it broke our CI repeatedly but eventually it seemed like it was stable (mainly, our MSRV caught up with its MSRV) so we just let it slide. In the end having schemars on hashes but nowhere else in the rust-bitcoin ecosystem did not prove that useful.
    
Remove schemars all together.

Fix: #3393

### CODE REVIEW

**Comment by apoelstra** [comment]
I'm not sure it should be a separate issue -- if we drop this test crate then we won't know when `schemars` eventually breaks. I think we should remove it all at once.

**Review by apoelstra — APPROVED** [review]
ACK 58704c2eff09ac4d36d138ff3fd8f002e4050a8c successfully ran local tests

**Comment by apoelstra** [comment]
I will let my ACK sit for 24 hours before merging to give Kix a chance to complain -- but because this is breaking CI I'll be more agressive about one-ack merging it than I normally would for a "rip out a feature" PR.

**Comment by tcharding** [comment]
FTR its an easy one to revert if needed.

**Comment by tcharding** [comment]
While reviewing #6163 this came up. Shall we backport this to 0.32 and 0.31 @apoelstra? I.e. remove schemars test crate all LTS branches.

**Comment by tcharding** [comment]
cc @jamillambert

**Comment by apoelstra** [comment]
>Shall we backport this to 0.32 and 0.31 @apoelstra? I.e. remove schemars test crate all LTS branches.

No, that would be a breaking change.

**Comment by tcharding** [comment]
Woops, I did not realize there was code involved. I only hit the `extendend_tests/schemars` crate in what ever I was doing yesterday when I did this. My bad.

**Pull request merged**
