### PR TITLE
CI: Pin `syn`

### PR DESCRIPTION
**Pull request by tcharding**
Lets see if this fixes CI.

### CODE REVIEW

**Comment by tcharding** [comment]
Perhaps this ...

**Comment by junderw** [comment]
No dice... :cry:

**Comment by tcharding** [comment]
Such good use of developer resources ... maybe this will work.

**Comment by tcharding** [comment]
I'm EOD, will try again tomorrow.

**Comment by apoelstra** [comment]
In rust-miniscript we pinned syn to some particular version of 2.x.

I would rather we just avoid syn 2 by pinning whatever its parent is .. but if it's a PITA then we might as well just do that. Later we can remove `serde_derive` entirely which should fix this for good. TBH I'm quite impressed that we've never yet run into a "permanent" problem with these syntax extensions where there isn't any version of `syn` that will satisfy us and all deps.

**Comment by tcharding** [comment]
ooph, should have read my notification before starting work on this this morning. #2079 doesn't work anyways, I'll have a go at just pinning syn like you say.

**Comment by junderw** [comment]
Yaaay it seems to work. We should also add it to the README so people know what to pin.

**Review by apoelstra — DISMISSED** [review]
ACK 34890827ae3352371e5e7822ae63edef785deaeb

**Comment by tcharding** [comment]
> Yaaay it seems to work. We should also add it to the README so people know what to pin.

The readme pinning docs are stale, I just removed them and pointed devs towards the ci script. I thought I did this once before but I can't remember what was the result of it, perhaps folks didn't like it.

Thanks for the review!

**Comment by tcharding** [comment]
Ah sorry @apoelstra I bet you are running your CI scripts right now for this PR and I pushed an additional patch.

**Comment by tcharding** [comment]
I guess not, please merge when you get a chance, this qualifies for the one-ack for CI changes carve-out.

**Review by apoelstra — APPROVED** [review]
ACK f5bc9b3cd4cf832735b42b4df2e9179643a3d8b8

**Pull request merged**
