### PR TITLE
It is annoying to have a difference between debug and regular print for Sha256dHash

### PR DESCRIPTION
**Pull request by tamasblummer**
Any reason for this?

### CODE REVIEW

**Comment by stevenroose** [comment]
I discussed this change with @apoelstra before. I totally agree with this change.

**Comment by stevenroose** [comment]
I discussed this change with @apoelstra before. I totally agree with this change.

You've got a test failure, though.

**Comment by tamasblummer** [comment]
Thanks for the heads-up, fixed the test.

**Comment by dongcarl** [comment]
Unfortunately the user-visible serialization of Sha256d hashes have always been displayed backwards... :-/

**Comment by tamasblummer** [comment]
yes, hence all prints of Sha256dHash-es are satoshi style in user 
interfaces. doing a debug print in a different style just makes it 
difficult to tie back to UI. This is not about some pedantic display of 
memory but usefulness in logs. The difference is esp. annoying if debug 
printing an object that contains a hash.

**Pull request merged**
