### PR TITLE
Deprecate the util::contracthash module

### PR DESCRIPTION
**Pull request by stevenroose**

### CODE REVIEW

**Comment by apoelstra** [comment]
@sgeisler superceded by Miniscript. There is some key-tweaking logic in there that doesn't exist elsewhere but it's not hard to implement independently.

**Comment by apoelstra** [comment]
...and I am planning to implement it in rust-miniscript, when we update our Liquid code to use this version of rust-bitcoin

**Comment by elichai** [comment]
I chased a warning on deprecated empty test for half an hour until I've found that this was the culprit :(
https://pastebin.com/raw/SyJvV5p8

Can we please add a reason to ease finding the source? (ie  `#![deprecated = "superceded by Miniscript"]`)

**Comment by elichai** [comment]
> I chased a warning on deprecated empty test for half an hour until I've found that this was the culprit :(
> https://pastebin.com/raw/SyJvV5p8
> 
> Can we please add a reason to ease finding the source? (ie `#![deprecated = "superceded by Miniscript"]`)

Saw this now: https://github.com/rust-bitcoin/rust-bitcoin/pull/475/commits/05f3451b108c5fdec518c0a54d6ebace07990e3c sigh.

**Pull request merged**
