### PR TITLE
Fix compilation warning when comparing usize and u64 on 32-bit arch

### LINKED ISSUE #117: Literal out of range in src/blockdata/script.rs
It only happens on i686. Not sure how to proceed.

```
warning: literal out of range for usize
   --> src/blockdata/script.rs:525:22
    |
525 |             n if n < 0x100000000 => {
    |                      ^^^^^^^^^^^
    |
    = note: #[warn(overflowing_literals)] on by default
    = note: the literal `0x100000000` (decimal `4294967296`) does not fit into an `usize` and will become `0usize`
```

[Offending code](https://github.com/rust-bitcoin/rust-bitcoin/blob/45c699f00501263523993930a052405a7bf31364/src/blockdata/script.rs#L525)

### PR DESCRIPTION
**Pull request by dongcarl**
Closes #117

### CODE REVIEW

**Comment by dpc** [comment]
Maybe it would be worthwile to add one compilation pass for 32-bit arch in `.travis.yml` ?

**Comment by dongcarl** [comment]
@dpc That'd be nice, if we're planning on officially supporting these.

**Comment by apoelstra** [comment]
@dpc We'd love to do that, but AFAIK the simplest way to do it is to spin up a VM inside Travis, which is a PITA that we haven't taken the time to do. Is there an easier way?

**Comment by dpc** [comment]
I was aware of: https://github.com/carllerche/travis-rust-matrix , but @jeandudey  's solution looks better to me.

I've just created https://users.rust-lang.org/t/test-i686-builds-in-travis/19709/2 - maybe there's something even better around.

**Pull request merged**
