### PR TITLE
units: Release tracking PR: `0.1.0` - BOOM!

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for release do two things:

- Patch 1: Attempt to improve the re-exports and HTML docs
- Patch 2: Add an initial changelog file

Note the version number is set already and does not conflict with the current `v0.0.0` version: https://crates.io/crates/bitcoin-units

### CODE REVIEW

**Comment by tcharding** [comment]
Its a shame to not have @Kixunil here for this one, mentioning you Kix in case you see it. This is definitely not in the state you had hoped for but we did our best. I intend on iterating as soon as `rust-bitcoin v0.32.0` is out.

**Comment by tcharding** [comment]
`cargo publish --dry-run` runs cleanly on my machine.

**Review by sanket1729 — APPROVED** [review]
ACK a7041f84cd29fad871091d36dcce27b0887f9c6b

**Comment by tcharding** [comment]
Thanks for all the reviews @sanket1729! We are getting close now.

**Comment by apoelstra** [comment]
In the CHANGELOG of a7041f84cd29fad871091d36dcce27b0887f9c6b there is a typo on `Weight`

**Review by apoelstra — DISMISSED** [review]
ACK a7041f84cd29fad871091d36dcce27b0887f9c6b will merge/publish in the morning

**Comment by tcharding** [comment]
Fixed typo and use backticks around all types

**Review by sanket1729 — APPROVED** [review]
utACK a05da2294e2b5e423756b669b54a94ca01e5a68d

**Comment by tcharding** [comment]
Crikey, that was fast @sanket1729

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
