### PR TITLE
fmt: Use style_edition = 2021

### PR DESCRIPTION
**Pull request by tcharding**
`rustfmt` is emitting:

 Warning: the `version` option is deprecated. Use `style_edition` instead.

As suggested add a config option and set it to 2021. 

- Patch 1: Manually configure rustfmt to skip some code
- Patch 2: Run the formmater with current configuration
- Patch 3: Add the new config option (remove old one), introduces no new formatting requirements

### CODE REVIEW

**Comment by tcharding** [comment]
I did this just so I could do #3431 without introducing a bucket load of formatting issues but it is going to make rebasing #3408 hard, draft until that goes in.

**Comment by jaoleal** [comment]
Will this be merged ? Im kinda formatting a lot of things just by running `just fmt`

**Comment by tcharding** [comment]
Woops, wrong button

**Comment by tcharding** [comment]
> Im kinda formatting a lot of things just by running just fmt

@jaoleal quick history, this is the current state of affairs in `rust-bitcoin`: we had a **lot** of discussion on how/when/if/if not to use `rustfmt` (includes a bunch of drama about nightly). The best compromise we could find was

- Use nightly
- No CI requirement to be formatter correctly
- Run a weekly formatting using a bot

This means that sometimes there are a bunch of formatting issues on master, I personally deal with this by running the formatter and commiting the changes locally, then removing the patch before pushing PRs. Usually there are no major conflicts. If there are you can always push up a "run formatter" PR and not wait for the bot.

Its sub-optimal I know but its the best we could come up with to keep everyone kind of happy.

**Comment by tcharding** [comment]
I'm not sure whats up with the labeler job, perhaps we just kick it again in a few hours.

**Comment by jaoleal** [comment]
> Its sub-optimal I know but its the best we could come up with to keep everyone kind of happy.

makes sense, thanks for explaining !

**Review by apoelstra — APPROVED** [review]
ACK 323e70611358c7db5b7e7be0c064df69725fafc1 successfully ran local tests

**Pull request merged**
