### PR TITLE
Automated daily update to rustc (to nightly-2024-10-23)

### PR DESCRIPTION
**Pull request by apoelstra**
Automated update to Github CI workflow `rust.yml` by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Review by tcharding — DISMISSED** [review]
ACK 4c1608797ff009e811d0ac329530468bb4da0fc1

**Comment by apoelstra** [comment]
Looks like it fails due to new lifetime lints.

**Review by jamillambert — COMMENTED** [review]
Lifetime lint failures fixed in #3473

**Review by tcharding — DISMISSED** [review]
ACK 10b925a99594a0a89e850bd72db2a2e3087d986a

**Comment by tcharding** [comment]
Needs #3504

**Comment by tcharding** [comment]
More lifetime lint warnings, `<insert explicative here>`.

**Comment by apoelstra** [comment]
Lol. This is why we pin nightly!

**Comment by jamillambert** [comment]
#3154 fixes the most recent warnings

**Comment by tcharding** [comment]
Closing, bot will pick up the fixes in #3514 next time.

**Pull request closed without merging**
