### PR TITLE
Do trivial docs cleanup

### PR DESCRIPTION
**Pull request by tcharding**
We are trying to stabalise `units`; do a few trivial docs cleanups.

### CODE REVIEW

**Comment by apoelstra** [comment]
I think having `a` in place is more correct.

**Comment by tcharding** [comment]
No sweat, will re-spin after the weekend.

**Comment by apoelstra** [comment]
Will hold up on this until #3575 is sorted out.

**Comment by tcharding** [comment]
This PR is so trivial I'll just close it and leave it for #3575

**Pull request closed without merging**
