### PR TITLE
Refactor Arbitrary for Sequence

### PR DESCRIPTION
**Pull request by yancyribbens**
Personally, I think this is a bit nicer and easier to reason about.

### CODE REVIEW

**Comment by apoelstra** [comment]
NACK. This changes the behavior from something sensible to something hard to reason about (and wrong AFAICT).

**Comment by yancyribbens** [comment]
This PR just improves the readability but does't change the semantics.  Of course with the usual AFAICT.

Before, there was the cfg that checks if alloc feature is enabled or not.  if it is enabled than do a match on 8 options.  If not alloc then do a match of 4 options:
```rust
        let mut choice_range = 4;
        if cfg!(feature = "alloc") {
            choice_range = 8;
        }
```

instead, add impl with 8 options if alloc or add impl with 4 options if not alloc.

**Comment by apoelstra** [comment]
Oops, sorry, I was looking at #3240 rather than #3420. (And my curt reply was because I remembered clearly already litigating this.)

**Comment by apoelstra** [comment]
This one seems reasonable to me.

**Review by tcharding — APPROVED** [review]
ACK d39334e651b58d1a5e7a0a00ee3b9c5b04aad634

**Comment by yancyribbens** [comment]
> Oops, sorry, I was looking at https://github.com/rust-bitcoin/rust-bitcoin/pull/3240 rather than https://github.com/rust-bitcoin/rust-bitcoin/pull/3420. (And my curt reply was because I remembered clearly already litigating this.)

No worries, thanks!

**Review by apoelstra — APPROVED** [review]
ACK d39334e651b58d1a5e7a0a00ee3b9c5b04aad634 successfully ran local tests

**Pull request merged**
