### PR TITLE
Repr(C) for OutPoint and SigHashType

### PR DESCRIPTION
**Pull request by dr-orlovsky**
As was discussed on IRC.

Can be merged, but will work in practice only after https://github.com/rust-bitcoin/bitcoin_hashes/pull/108

### CODE REVIEW

**Comment by apoelstra** [comment]
I would expect `#[repr(C)]` on an enum to eliminate space-saving optimizations.

**Comment by dr-orlovsky** [comment]
@apoelstra done

**Comment by elichai** [comment]
I'll just say that this means that `SigHashType` will always be 4 bytes in memory for all our users. even those who don't care about FFI.

Example: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=bd3c2892799f33c98b87f072f45ba071

**Comment by apoelstra** [comment]
@dr-orlovsky I'm going to concept-NACK this because it increases the size of `SigHashType` so much and because the value is so limited.

Your similar pr to bitcoin_hashes I think we could probably accept, since arrays of bytes are probably represented same as in C no matter what we do, so there's no harm in making it a guarantee.

**Pull request closed without merging**
