### PR TITLE
improve example: take hex-encoded seed instead of WIF in bip32 example

### LINKED ISSUE #748: BIP32 example is misleading
The example is starting from a WIF key and generating a master xpriv, which is perfectly fine (though I guess it is a pretty weird thing to do .... the point I believe was to demo how to create a BIP32 derivation starting from a master seed, and we may have reached for WIF because it was handy, not because it was a normal/wise way to store a seed).

What it does *not* do, and can't do, is derive any non-master xpriv, and you cannot convert xpriv -> WIF -> xpriv in this way.

I think we should hex-encode the master seed in our example. Agreed that using WIF here is confusing and potentially misleading.

_Originally posted by @apoelstra in https://github.com/rust-bitcoin/rust-bitcoin/issues/745#issuecomment-999941910_

### PR DESCRIPTION
**Pull request by bruteforcecat**
This is my understanding of what we want to fix the confusing bip32 example. Apologize in advance if I misunderstand it.

Closes #748

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 1bd54ab82cca8e39ab86eaa02ee6b6087a8f3493

This looks perfect, thanks!

**Comment by bruteforcecat** [comment]
> ACK [1bd54ab](https://github.com/rust-bitcoin/rust-bitcoin/commit/1bd54ab82cca8e39ab86eaa02ee6b6087a8f3493)
> 
> This looks perfect, thanks!

Thanks. just rebased master and fix test in `contrib/test.sh`

**Review by dr-orlovsky — APPROVED** [review]
ACK bb70820fede6038254fa4d7af6873ef55b49fd11

**Review by RCasatta — APPROVED** [review]
utACK bb70820fede6038254fa4d7af6873ef55b49fd11

**Pull request merged**
