### PR TITLE
Reverts #84, bumps Cargo minor version number, and re-adds #84

### PR DESCRIPTION
**Pull request by apoelstra**
Lets us `cargo publish` a new rev of 0.13 that unbreaks things.

### CODE REVIEW

**Comment by apoelstra** [comment]
@tamasblummer @TheBlueMatt this is a bit of a weird one. Would appreciate at least a concept ack from you.

**Comment by tamasblummer** [comment]
ACK. 
Remark: It is arguable if adding an enum value is an API change. Yes, it can break compilation if there is no catch-all case in a match statement, but it could also remain even semantically correct if there is one. Assume that the range of return value of a function returning an integer changes; would we consider it an API change? Maybe it is if e.g. returning a special value now has a special meaning, not if it fits well with its current use. It is certainly simpler to keep the rule that a change that can break compilation should only be done with major version increment.

**Comment by apoelstra** [comment]
@tamasblummer Yeah, I think we should call this a "breaking change" because it can break compilation, and not dig too deep into the philosophy of it.

**Comment by apoelstra** [comment]
Thanks. Published and tagged 0.13.2

**Pull request merged**
