### PR TITLE
Remove the check api tool

### PR DESCRIPTION
**Pull request by tcharding**
Both Andrew and myself think this was an improvement but Kix won't stop whinging about it.

Just remove the whole thing.

### CODE REVIEW

**Comment by tcharding** [comment]
lol 36,000 lines of red - irrespective of any other considerations that is a win.

**Comment by Kixunil** [comment]
Feel free to postpone this until an alternative is ready. Though it might make me reluctant to make PRs while the check is in.

**Comment by Kixunil** [comment]
> So then we're back to making them run a local tool.

`git pull --rebase` or `git push -f` and let the bot handle the changes.

> We could vendor cargo-check-api into this repo itself?

If you publicly claim you've reviewed the code and found no backdoors or other stuff you can just publish a git hash. :)

**Comment by tcharding** [comment]
Lets back up, what we have today is (please correct me if I'm wrong):
- A tool that @apoelstra and myself find useful when developing and reviewing patches
- A workflow that creates annoying but acceptable friction for Andrew and myself
- A workflow that is unacceptable to @Kixunil 
- A workflow that is a bit annoying to drive-by-devs

Would the following keep all the benefits and remove all the negatives:
- Remove the check-api CI job and text files
- Add a script that does something along the lines of "create a new tmp branch, add a patch at the front with current api, add a patch at the end with api changes (or after each patch)"

This would allow:

- Creating an on-push-bot that runs the script so there is a public branch that can be linked to if discussion needs to happen on the api file changes. 
- Andrew and myself to run the script locally either during dev or review when it seems it would help.

**Comment by apoelstra** [comment]
@tcharding ok, yeah, that looks like a good summary. And yes, if there were a local tool that would just show the API diff for individual commits (and maybe whole PRs) that would be great.

**Comment by tcharding** [comment]
Leave it with me.

**Comment by tcharding** [comment]
#2946 does the removal, leaving this in draft to remind me to write the tool to use locally.

**Comment by tcharding** [comment]
Script written, see #2986

**Pull request closed without merging**
