### PR TITLE
Replaced Deprecated Function

### PR DESCRIPTION
**Pull request by Sh0g0-1758**
Changed deprecated Function with a supported one.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 08a9962035a30a52e119580f79c5978b5dfb6d69 yep, this seems reasonable. Thanks!

**Comment by Sh0g0-1758** [comment]
@apoelstra, safe to land?

**Comment by apoelstra** [comment]
No, I'll wait for a second approver before merging, which is our policy here.

**Review by tcharding — APPROVED** [review]
ACK 08a9962035a30a52e119580f79c5978b5dfb6d69

**Comment by Kixunil** [comment]
Oh, not really. This should've been silenced for the time being and completely deleted with the offending function in the next release.

**Comment by apoelstra** [comment]
@Kixunil what's the point of waiting for a release? We already replaced the function and we've had several weeks of testing the deprecated function since then.

Also the new function is obviously a subset of the old one, and the test only covers that subset, and clearly neither function is going to change functionality ever./

**Pull request merged**
