### PR TITLE
Add tests for block version

### PR DESCRIPTION
**Pull request by shinghim**
Add unit tests for block `Version`

### CODE REVIEW

**Comment by tcharding** [comment]
Appreciate the effort but I don't think these tests add any real value. What exactly are you thinking that theses tests prove (or what are you imagining that they test)?

**Comment by shinghim** [comment]
These tests will test the functionality of `Version::is_signalling_soft_fork`. Mainly for regression testing, in case (for whatever reason) `Version::is_signalling_soft_fork` gets updated, it should still follow the behavior defined in BIP 9

**Comment by tcharding** [comment]
Cool, if they are regression tests then they should be marked as such and probably live in `tests/` (for examples we already have see `bitcoin/tests/serde.rs` or `hashes/tests/regression.rs`

**Comment by shinghim** [comment]
It’s also testing the different branches of logic with different versions to make sure that it’s only returning true for versions that are signaling soft fork. Seems like they would be fine as unit tests

**Comment by apoelstra** [comment]
I agree with @shinghim. There's not much conceptual difference between a unit test or a "regression test" on a single function. These seem fine to me.

**Comment by tcharding** [comment]
Alright, I'm with you guys. If this is unit testing functionality perhaps this makes it easier to read

```rust
    #[test]
    fn version_is_not_signalling_with_invalid_bit() {
        let arbitrary_version = Version::from_consensus(1234567890);
        // The max bit number to signal is 28.
        assert!(!Version::is_signalling_soft_fork(&arbitrary_version, 29));
    }

    #[test]
    fn version_is_signalling() {
        let version = Version::from_consensus(0b00100000000000000000000000000010);
        assert!(Version::is_signalling_soft_fork(&version, 1));
    }

    #[test]
    fn version_is_not_signalling() {
        let version = Version::from_consensus(0b00100000000000000000000000000010);
        assert!(!Version::is_signalling_soft_fork(&version, 0));
    }

    #[test]
    fn version_is_not_signalling_when_use_version_bits_not_set() {
        // Top three bits must be 010 to signal.
        let version = Version::from_consensus(0b01000000000000000000000000000010);
        assert!(!Version::is_signalling_soft_fork(&version, 1));
    }
```

**Review by apoelstra — APPROVED** [review]
ACK 778af49f1097909729b0d8382a94f8fb7af2e1cc successfully ran local tests

**Comment by tcharding** [comment]
hmm, I don't want to ack because I think the added code comments are beneficial but please BDFL over me @apoelstra and merge if you think I'm being overly pedantic.

**Comment by apoelstra** [comment]
No, go ahead and hold it up over the comments. I don't think there's any particular rush on this PR.

**Comment by shinghim** [comment]
Added the comments 👍🏼

**Review by tcharding — APPROVED** [review]
ACK 0e0192c02534d799c4ab12f8646adc73f34a25f3

**Comment by tcharding** [comment]
Thanks man!

**Pull request merged**
