### PR TITLE
Remove unused `absolute::Error`

### PR DESCRIPTION
**Pull request by tcharding**
I don't remember how this error came to be like this but it is currently unused. Remove it.

### CODE REVIEW

**Comment by Kixunil** [comment]
Didn't we agree we will keep errors in modules so people don't have to define their own? IIRC I intentionally left it in because we did. But I can see a point for not doing so: the errors are often unrelated.

**Review by sanket1729 — DISMISSED** [review]
ACK 66a5946420d5fc3e621956db8cb601e55c7e9922

**Comment by apoelstra** [comment]
I don't remember either -- I think that, in general, if we find ourselves in a situation where we either need to make an error generic, or provide a few unused variants for downstream users to use, we should try to provide unused variants. But I can't think of a motivation to define entire error *types* which we don't use.

**Review by apoelstra — APPROVED** [review]
ACK 66a5946420d5fc3e621956db8cb601e55c7e9922

**Comment by apoelstra** [comment]
Will wait for Kix to respond to this before merging.

**Comment by apoelstra** [comment]
Also conflicts #2516

**Comment by Kixunil** [comment]
If you start cutting all things unused by this library you'll eventually end up with an empty crate :) - because it's a library, it's for downstream users to use.

My thinking was to provide these errors in case downstream users don't want `anyhow` & co and want to match on variants but higher up their call stack. But now I realize it may be a too niche use case and we could add these things back later if actually needed. Meanwhile users can define their own enums which will be also more precise.

**Comment by apoelstra** [comment]
Sounds good. But @tcharding this needs a rebase.

**Comment by tcharding** [comment]
Rebased and changed the commit log in light of the discussion above to be
```
    Remove unused absolute::Error
    
    The `absolute::Error` is not used, we originally intended it as possibly
    useful for users of the library. We have not made effort in other
    modules to provide such errors - lets remove it.
```

**Comment by tcharding** [comment]
Leaving the PR description as is.

**Comment by tcharding** [comment]
This PR has not materially changed since 2 previous acks.

**Comment by tcharding** [comment]
Waiting for this to merge then undrafting #2569 just hold us up another 24 hours. This is P-high so I'm closing it and pushing it in via 2569.

**Pull request closed without merging**
