### PR TITLE
WIP: Split `ecdsa` types up

### PR DESCRIPTION
**Pull request by tcharding**
Make another attempt at splitting the `ecdsa` types (sighash type and signatures) up into `legacy` and `native` (I posted #1762, and from @apoelstra comment probably need to change "native" back to "segwit_v0" here, will leave as is for now because its a minor thing to change).
    
This is a bit curly because of PSBT's classifying things as either taproot or non-taproot - and we currently use `ecdsa` types for that - as such this PR _duplicates_ the ecdsa stuff without removing it.

### CODE REVIEW

**Comment by apoelstra** [comment]
TBH I think this is a big improvement. I have some nits but I'll re-review and bring them up once #1597 is in.

**Comment by tcharding** [comment]
> TBH I think this is a big improvement.

Oh yeah, cool. I was a bit disheartened yesterday with it. You've motivated me to improve it again.

**Comment by sanket1729** [comment]
concept ACK. I also think this is a big improvement.

**Review by Kixunil — COMMENTED** [review]
Just noticed I had a pending comment, will properly review after rebase.

**Comment by tcharding** [comment]
The fact that `psbt::Input` puts ecdsa signatures into a single key/value map make splitting these two types kinda painful.

**Comment by Kixunil** [comment]
@tcharding that sounds similar to what I found in json RPC lib. I think we will need another type for it.

**Comment by tcharding** [comment]
> Internally to the PSBT could we just store byte vectors?

That's what I was thinking, I was hesitant because all the other types in `Input` are "proper" types. Related quesiton, whats the state of the PSBT stuff and whats the plan for it? Is it going to be totally overhauled for PSBTv2 or are we going to keep supporting both v0 and v2?

**Comment by tcharding** [comment]
cc @DanGould in case you want to chime in.

**Comment by apoelstra** [comment]
@tcharding I think we should support both v0 and v2 forever, but v0 should become a second-class citizen and if we have to make v0 inefficient or have a crappy API, that's ok.

As for the other `Input` types having "real" types .... I'd argue nothing in PSBT is properly typed right now. In an ideal world we would typestate the entire PSBT workflow, but I don't know if any human is smart enough to do that.

**Comment by Kixunil** [comment]
I think it makes sense to treat PSBT as a serialization format. Perhaps raw bytes isn't that bad, I had recently changed types in `serde`-deserialized structs to be `Spanned<String>` and did validation manually afterwards because it gave 10 times better error messages. Although it could be really annoying for projects that don't care.

**Comment by DanGould** [comment]
I don't have much to say about ecdsa types or sighash in PSBT. I've never run into a problem with them and I don't feel informed enough to comment on what this PR tries to achieve.

Regarding the discussion here about PSBT in general, V2 exists to make in-place input + output mutation ergonomic. We should support that improved internal representation and allow ser/de into and out of v0, sort of like we ser/de from `Transaction`. I agree with making v0 a second-class citizen.

I don't think the v0 roles are well defined enough for typestate. It seems like the protocols of today (at least bip78) even [ignore them](https://github.com/bitcoin/bips/pull/1396). I am hopeful typestate may be possible with v2 roles, if only for a subset of normal use cases. I wonder if role typestate can exist at a higher level than the serialization format, which I think would be handy for FFI bindings that don't want to translate all of that typestate.

I should have some bandwidth to return to drafting v2 support next week.

**Comment by tcharding** [comment]
Superseded by #1989

**Pull request closed without merging**
