### PR TITLE
contributing: Add section about release versions and deprecation

### PR DESCRIPTION
**Pull request by stevenroose**
I keep forgetting the exact string, hope this helps.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK dba526293c4f91ff48f9a34457bf3d94fd1b9219

**Comment by tcharding** [comment]
Sweet, I always forget this too. I think the string needs tweaking though.

I get
```rust
error: the since field must contain a semver-compliant version
   --> bitcoin/src/address/mod.rs:614:18
    |
614 |     #[deprecated(since = "NEXT_RELEASE", note = "use alternative_method() instead")]
```

This seems to work:
```rust
    #[deprecated(since = "1.0.0-NEXT-RELEASE", note = "use alternative_method() instead")]
```

**Comment by tcharding** [comment]
Note, I had to change the underscore to a `-`.

**Comment by clarkmoody** [comment]
Concept ACK

**Review by jamillambert — COMMENTED** [review]
This PR is being brought back alive because of #3306.

`NEXT_RELEASE` should be changed to `TBD`

**Comment by tcharding** [comment]
Hey @jamillambert, I know @stevenroose in person and he does not tend to check GitHub notifications, he also is typically happy to just see his work merged without having to follow up on it (I think, Steven please correct me either here or offline if I'm wrong). 

So if you feel like it  you could pick this up for him. If you do feel like it this is the basic process but there is no hard-and-fast protocol:

- Grab the patch from this branch (copy the commit hash, create a new branch, use `git cherry-pick <hash>`)
- Fix the changes and amend the patch. 
- Include this line at the bottom of the commit log: `Co-authored-by: Steven Roose <his-email-address>`. 
- Raise a new PR and in the description write "picked up Steven's PR #2137".

At least that is how I do it. The idea is just we are all working together to move forward without treading on each others toes too much, giving attribution where required.

**Comment by jamillambert** [comment]
I have picked up this PR and made the change to `TBD` in #3476.

Suggest to close this PR

**Comment by apoelstra** [comment]
Yeah, gonna close this since it is a year old and there is a replacement. If Steven complains I'm happy to re-open.

**Pull request closed without merging**
