### PR TITLE
Cleanup block module

### PR DESCRIPTION
**Pull request by tcharding**
Do some clean ups to the `blockdata::block` module.

- Patch 1: Change predicate names (API breaking, could be seen as unnecessarily changing the API), can remove if NACK'd
- Patch 2: Refactor to assist code clarity
- Patch 3 and 4: are docs improvements, shouldn't be too controversial

### CODE REVIEW

**Comment by apoelstra** [comment]
Honestly I prefer the old names. `check_X` is clear that it's checking whether the data X in the header is correct. `X_matches` implies that maybe one or the other could be wrong, and it's not clear what "the other" even is since these methods take no inputs.

**Comment by tcharding** [comment]
Fair points. Will remove the rename `check_` patch from this PR.

**Comment by tcharding** [comment]
Changes in force-push
- Rebased on master
- Removed the patch changing predicate names

**Review by apoelstra — APPROVED** [review]
ACK 146d5e83d1744f1ae6143e472e7a24bde3110e16

**Review by dr-orlovsky — APPROVED** [review]
ACK 146d5e83d1744f1ae6143e472e7a24bde3110e16

**Pull request merged**
