### PR TITLE
A couple of kani fixes

### PR DESCRIPTION
**Pull request by tcharding**
PR does two things because a recent upgrade of `kani` broke our setup. I'm not sure why it just showed up.

We fix the verification for `amount` types which recently broke because of `MAX_MONEY` changes and then we add a verification function to `internals` because build fails and one fix is to just add something.

- Patch 1: units: Assumes correct values
- Patch 2: units: Removes a stale check now that MAX_MONEY is being used for MAX
- Patch 3: Add verification to `internals::ArrayVec`.

### CODE REVIEW

**Comment by tcharding** [comment]
This code will break again if/when we enforce the invariant in `from_sat` as per #3730

**Comment by tcharding** [comment]
Ouch, 2nd merge queue related problem on master this week. And the lint PR is likely going to be the 3rd. Maybe all the merge queue talk was more warranted than I thought.

**Comment by tcharding** [comment]
I'm not sure what is going on now, I can run `cargo kani` in `units` and also in repo root.

**Comment by jamillambert** [comment]
This PR fixes the kani check in units for me too, but I do get an error in internals.  The same error as here "error: Failed to detect Kani functions"

If I add a kani function in internals everything passes.  But I don't know why it complains when there is none.

**Comment by tcharding** [comment]
Can you post the command you run to get the error please (and from what directory).

**Comment by jamillambert** [comment]
I just ran `cargo kani` from `internals/`, but I also get the same error if I run it in the repo root.  It runs fine in `units/`.
Maybe due to a kani update? I only just installed it then (V 0.57.0)

**Comment by tcharding** [comment]
> It looks like it's an issue with kani V0.57.0. If I revert back to 0.56.0 I don't get the error.

Oh that explains it, good debugging bro.

**Comment by tcharding** [comment]
Holy moly, I have `v0.17.0` installed.

**Review by jamillambert — APPROVED** [review]
ACK e378cdd8fa340469b8c9b046ea6d6f0dd4e04414

**Comment by jamillambert** [comment]
Just thought I should clarify my ACK that this PR is fine and fixes the described kani failure.  The conclusion above is that there is an issue with kani causing the current CI fail.

**Comment by tcharding** [comment]
I added a kani verification to `internals::ArrayVec`. Clears the error we were experiencing and adds some value by verifying no out of bounds in `ArrayVec`.

**Comment by apoelstra** [comment]
Nice! Will ACK and merge this so we can get CI moving.

But we should separately change `Amount::to_signed` to no longer return a `Result`.

**Comment by tcharding** [comment]
Added to #3787

**Review by apoelstra — APPROVED** [review]
ACK f4617e71f5fd074000d1e3a9376644c744210562; successfully ran local tests

**Pull request merged**
