### PR TITLE
Removed stale doc comment

### PR DESCRIPTION
**Pull request by roy9495**
Hello sir ,
This pr solves this issue #1850 

 I removed the  "only available in 1.46.0" doccomment from the file.

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you squash these commits?

**Comment by tcharding** [comment]
Thanks for the contribution! There is another one in `blockdata/trascation.rs`, can you grab that one too while we are at it? Cheers

**Comment by roy9495** [comment]
> Thanks for the contribution! There is another one in `blockdata/trascation.rs`, can you grab that one too while we are at it? Cheers

Sure

**Comment by yancyribbens** [comment]
This could be just one commit I think since it's so similar.

**Comment by apoelstra** [comment]
Could you fix the commit message?

**Review by tcharding — APPROVED** [review]
ACK 963a5f26f42cce3378fa8b6c0668a1c8c63e2565

**Comment by roy9495** [comment]
I need some help here , after changing the commit message one commit converted to three commits .

**Comment by yancyribbens** [comment]
Type `git rebase -i commit` where commit is the oldest commit hash.  You can find the commit hash using `git log`.  The rebase command allows you to edit, reword or squash the commits.

**Comment by roy9495** [comment]
Can I close this pr and open a new one?
I apologise for the inconvenience.

**Comment by yancyribbens** [comment]
you could just reset this branch with: `git reset --hard origin/master` and then re-do the commit.

**Comment by tcharding** [comment]
> I need some help here , after changing the commit message one commit converted to three commits .

Review time is limited, we don't have time to teach basic git skills in `rust-bitcoin` I'm afraid.

**Comment by Harshil-Jani** [comment]
@roy9495 Devs are really busy building cool stuff out there, So they truely expect basic git skills. 
But, Assuming this as your very first contribution to this project, I would love to help you get started with this.
```
git reset --hard origin/main
# Redo the changes
git add .
git commit -m -s "Your Message"
git push -f
```

OR

```
git rebase -i HEAD~6
```
This will open an editor with some commit messages, You can delete the last 5 messages and keep the most upper one which in your case should be `pick Update transaction.rs` something. Rename the commit message with what you feel would be something good and someone can understand even after years about the change just after looking at the commit message. Save it. and do
```
git push -f
```

Since the PR is already closed, Just ping tcharding once if you are really willing to contribute and he can reopen it. 
For future git uses, I would recommend learning about basics and advanced git commands from good resource.

**Comment by roy9495** [comment]
@Harshil-Jani I apologize for any inconvenience caused. I understand that they are busy individuals and it was my responsibility to familiarize myself better with the git commands. I realize that when rebasing, GitHub Desktop automatically commits two files to the branch without my intention. In order to rectify the situation, I will open another pull request. I sincerely apologize for any inconvenience this may have caused.

**Comment by Harshil-Jani** [comment]
Just try to avoid Github Desktop and use terminal and get super duper comfortable with it. Maybe this time a new PR would just do the work and it is fine. But, Everyone expects the work to be done neatly so in future please avoid that and follow contribution guidelines. So, You will definitaley learn along the way for your future contributions !!

**Comment by roy9495** [comment]
Will do. Thank you sir.

**Comment by tcharding** [comment]
Legendary effort @Harshil-Jani, appreciate you taking the time.

**Pull request closed without merging**
