### PR TITLE
Release tracking PR: `bitcoin 0.32.4`

### PR DESCRIPTION
**Pull request by tcharding**
In preparation for release add a changelog entry, bump the version, and update the lock files.

### CODE REVIEW

**Review by storopoli — APPROVED** [review]
ACK fff73bdd045c00e65900235c95368b8c00fc14ce

**Comment by tcharding** [comment]
Add leading patch to remove the lint warning, just an unused import statement.

**Comment by tcharding** [comment]
Re-ack please @storopoli, you were too quick for me!

**Review by storopoli — APPROVED** [review]
ACK b795bbdacb34dc6d21fd8cdb8e705cd37d84cdf3
Just removed an unused statement

**Comment by tcharding** [comment]
Shall we hobble WASM on `0.32.x` branch also @apoelstra?

**Comment by apoelstra** [comment]
Yes please! Can you do that in this PR?

**Comment by romanz** [comment]
Tested ACK b795bbdacb34dc6d21fd8cdb8e705cd37d84cdf3.

**Comment by tcharding** [comment]
Now includes patch from #3505. No other changes. I think this is ready to release.

**Comment by tcharding** [comment]
Thanks @romanz!!

**Review by apoelstra — APPROVED** [review]
ACK 074af722409c1cb2ed57781082ee3d661860cb0d; successfully ran local tests

**Comment by apoelstra** [comment]
Tagged and published.

**Pull request merged**
