### PR TITLE
Implements #400: WScriptHash -> WitnessProgram

### PR DESCRIPTION
**Pull request by dr-orlovsky**

### CODE REVIEW

**Comment by stevenroose** [comment]
I know it's in the BIP and all, but that doesn't mean that it's a descriptive name.. :/

Anyhow, ACK. I suppose we should also change the name of the address payload. I'll make a followup PR.

**Comment by dr-orlovsky** [comment]
It is so. The naming is clearly bad and misleading. But anyways, any words has the meaning we attach to them, and in order to rich some social consensus/coordination we have to attach the meaning according to some common standards, out of which BIPs work the best.

**Comment by dr-orlovsky** [comment]
Travis needs a cache reset here as well :(

Would be nice to merge, since it fixes the discussed #400. @apoelstra can you review pls?

**Comment by stevenroose** [comment]
Cleared and reset.

**Comment by apoelstra** [comment]
Sorry for very late review, and thanks for waiting for me.

As it looks like @dr-orlovsky noticed in #400, `WitnessProgram` is an arbitrary-sized byte vector, not any specific hash type. So I think this PR is not how we want to approach this.

**Comment by dr-orlovsky** [comment]
Oh yes, true. So we need to keep WScriptHash/WPubkeyHash, however generate it not directly from scriptPubkey value, but via SegWit-version-aware function through intermediate value of some WitnessProgram (not a hash type)?

```rust
let txout: TxOut = ...;
let wp: WitnessProgramm = txout.get_witness_program();
if Some(WScriptHash) = wp.get_wscript_hash() {
   // means we have V0 witness program containing script hash (and not pubkey hash)
}
```

**Comment by apoelstra** [comment]
I'm not sure why we need a distinct type for a witness program beyond `Script`. There are no other scriptPubkey templates for which we have a distinct type.

**Pull request closed without merging**
