### PR TITLE
Automated daily update to rustc (to nightly-2024-03-20)

### PR DESCRIPTION
**Pull request by apoelstra**
Automated update to Github CI workflow `rust.yml` by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by apoelstra** [comment]
Neat! It does run CI, but it uses my name as the PR author. I guess I'm okay with that.

**Comment by tcharding** [comment]
If you are the author then someone else will have to ack, I was planning on just acking mechanically and not doing any checks - just stating in case something else is expected.

**Comment by tcharding** [comment]
ACK 5d078ce660b40548c8b71b346568cf7ed8916a7e

**Review by tcharding — APPROVED** [review]

**Comment by apoelstra** [comment]
@tcharding sgtm. The point of this pinning is to avoid CI breaking out from under us, so in theory CI is the only check that we need.

**Comment by tcharding** [comment]
Seems like the system is working, our code does not build cleanly with this version of `nightly` so we shouldn't merge it, right - we have to do the update manually? Did you guys have a timeframe in mind for how often that should be done? Within a week, within a month, just when we get round to it?

**Review by tcharding — APPROVED** [review]
ACK b9bb1b92b846d1c94832154d8db2d674d775bba8

**Comment by apoelstra** [comment]
Still failing and no update on our clippy issues.

**Pull request closed without merging**
