### PR TITLE
Ready for Review: Add derive_* methods to Extended*Key

### PR DESCRIPTION
**Pull request by dongcarl**
- Add derive_pub to ExtendedPubKey
- Add derive_priv to ExtendedPrivKey
- Removed from_path from ExtendedPrivKey as it is superseded by
  derive_priv
- Add checking of derive_pub and derive_priv to test_path
- Add checking of correct error when invoking ckd_pub on a hardened
  ChildNumber
- Add test vector 3 from BIP32 specification

### CODE REVIEW

**Comment by dongcarl** [comment]
Closing and reopening to retrigger Travis... Networking issues...

**Comment by jeandudey** [comment]
It's happening in #128 too

**Comment by dongcarl** [comment]
Again...

**Comment by dongcarl** [comment]
@jeandudey Ready!

**Pull request merged**
