### PR TITLE
Remove 1.46 from build file

### PR DESCRIPTION
**Pull request by yancyribbens**
Remove 1.46 and 1.55 and add 1.53 and 1.60 to build script.  Also add comments and minor fix to expect message.

### CODE REVIEW

**Comment by apoelstra** [comment]
While you are deleting 46, could you add `53` and `60` which both appear to be used but are not in build.rs?

**Comment by yancyribbens** [comment]
> While you are deleting 46, could you add 53 and 60 which both appear to be used but are not in build.rs?

Yes sure.  Although I'd also like to make this file more maintainable.  Maybe we could add some comments about how this file works?  For example, were does RUSTC env get passed in?

**Comment by apoelstra** [comment]
> Yes sure. Although I'd also like to make this file more maintainable.

Well, I'd kinda prefer we not encourage people to use this file, so I don't think it should be in the README. I guess we could give it a smal section in CONTRIBUTING.md. But I'm unsure how much it'd help to have it documented better. The problem is that the numbers here need to be in sync with the uses of `rust_v_1_*` in the codebase and they need to be manually synced. (I guess we could write a CI/lint script that could check.)

> Maybe we could add some comments about how this file works? For example, where does RUSTC env get passed in?

This file is build.rs, which cargo compiles and runs before building the rest of the codebase. When it outputs lines of the form `cargo:rustc-cfg=X` this tells cargo to add `RUSTFLAGS=--cfg=X` when it is compiling everything else. This allows us to check the current toolchain versions and set rustflags dynamically based on that.

**Comment by yancyribbens** [comment]
> Well, I'd kinda prefer we not encourage people to use this file, so I don't think it should be in the README. I guess we could give it a smal section in CONTRIBUTING.md.

I wasn't suggesting adding it to CONTRIBUTING.md, only looking to add some comments to the file itself.  For example, I can see that `env::var_os(RUSTC)` is used to discover what rustc the compiler is resolved to use.  This defaults to `rustc` it looks like if nothing is set.  Is this env ever set?  Also, I think just `env::var` is good enough since the compiler name should always be valid UTF8? but I guess it doesn't hurt to leave this as is.

> This file is build.rs, which cargo compiles and runs before building the rest of the codebase. When it outputs lines of the form cargo:rustc-cfg=X this tells cargo to add RUSTFLAGS=--cfg=X when it is compiling everything else. This allows us to check the current toolchain versions and set rustflags dynamically based on that.

Thanks, I vaguely remember this now from the last time I looked at the build script.  The Cargo book does a pretty good job of documenting this actually: https://doc.rust-lang.org/cargo/reference/build-scripts.html#rustc-cfg

**Comment by yancyribbens** [comment]
> While you are deleting 46, could you add 53 and 60 which both appear to be used but are not in build.rs?

done here: https://github.com/rust-bitcoin/rust-bitcoin/pull/2125/commits/3c05a91606020240097cecf7cec3bfbe823777e1

I also added some comments to the file which hopefully make it quicker to to read:
https://github.com/rust-bitcoin/rust-bitcoin/pull/2125/commits/4ee47c0ff3f36606cd18418a1984ab7d59e723a8

**Comment by Kixunil** [comment]
> Is this env ever set?

This is settable by the user and it's the same variable cargo already uses. So if a user overrides rustc by setting `RUSTC` both cargo and our script will do the right thing.

**Comment by Kixunil** [comment]
> I guess we could write a CI/lint script that could check.

I'd like to see that if anyone has the time.

**Review by tcharding — COMMENTED** [review]
NACK to all these "what" comments (comments are mainly useful when they say "why" code does something not what it does, we can see what it does by looking at the code).

**Comment by vincenzopalazzo** [comment]
I agree with @tcharding, also because I am still not understanding what this PR is proposing an why.

**Comment by yancyribbens** [comment]
> This is settable by the user and it's the same variable cargo already uses. So if a user overrides rustc by setting RUSTC both cargo and our script will do the right thing.

@Kixunil thanks, I came to the same realization after reading https://doc.rust-lang.org/cargo/reference/environment-variables.html.

> I agree with @tcharding, also because I am still not understanding what this PR is proposing an why.
@vincenzopalazzo this PR started primarily to sync the cfg attributes that are defined in the buildscript with the cfg attributes defined in the codebase.  If you run `git grep "rust_v_1_`

```
bitcoin/src/blockdata/script/borrowed.rs:#[cfg(rust_v_1_53)]
bitcoin/src/blockdata/script/borrowed.rs:#[cfg(rust_v_1_53)]
bitcoin/src/blockdata/script/mod.rs:#[cfg(any(not(rust_v_1_60), target_has_atomic = "ptr"))]
bitcoin/src/blockdata/script/mod.rs:#[cfg(any(not(rust_v_1_60), target_has_atomic = "ptr"))]
bitcoin/src/blockdata/script/push_bytes.rs:    #[cfg(rust_v_1_53)]
bitcoin/src/blockdata/script/push_bytes.rs:    #[cfg(rust_v_1_53)]
bitcoin/src/consensus/encode.rs:#[cfg(any(not(rust_v_1_60), target_has_atomic = "ptr"))]
bitcoin/src/lib.rs:    #[cfg(all(not(feature = "std"), not(test), any(not(rust_v_1_60), target_has_atomic = "ptr")))]
internals/build.rs:            println!("cargo:rustc-cfg=rust_v_1_{}", version);
internals/src/serde.rs:        #[cfg(rust_v_1_55)]
internals/src/serde.rs:        #[cfg(not(rust_v_1_55))]
```

And in the build script, we currently have compile time flags for `v_1_46` and `v_1_55` https://github.com/rust-bitcoin/rust-bitcoin/blob/master/internals/build.rs#L30.  This means that 1_46 is never used while `1_53` and `1_60` will never be compiled in.  It looks like I made a mistake in this PR by removing 1_55 which I'll add back.  There should be a sanity check for this during compile time so we don't have these mismatches, but for now it's just re-syncing the versions.


> NACK to all these "what" comments (comments are mainly useful when they say "why" code does something not what it does, we can see what it does by looking at the code).

@tcharding  I'm fine with not including the comments with this PR if they are noise.

**Comment by apoelstra** [comment]
adcaa2cdea28e8e9b4359db9114e028d395c4d43 still has a lot of "what" comments which slow down the code because it forces the reader to interpret them and check that the code matches. But neither the human reader or the compiler learns anything new from them.

**Comment by yancyribbens** [comment]
dropped https://github.com/rust-bitcoin/rust-bitcoin/commit/adcaa2cdea28e8e9b4359db9114e028d395c4d43 since it's not helpful to others.

**Comment by apoelstra** [comment]
In d6024bd2351247a4b33d236fa8cec08491653b5c can you explain where the "expect message should show what you expect" convention comes from? I have never heard of this, it makes the resulting error messages confusing, and I couldn't find it after a quick web search.

**Comment by Kixunil** [comment]
@apoelstra I believe the convention is valid for internal invariants. E.g. `write!(vec, "foo").expect("vec never errors")` however in this case it's used as a quick "hack" parsing outside information since I considered it pointless to do proper error handling. As such the error message should really be what it was originally.

**Comment by yancyribbens** [comment]
> can you explain where the "expect message should show what you expect" convention comes from? 
@apoelstra see: https://doc.rust-lang.org/std/option/enum.Option.html#recommended-message-style

```
let item = slice.get(0)
    .expect("slice should not be empty");
```

Really I'm fine either way.  It would be nice to have a standard format for the project.

**Comment by Kixunil** [comment]
@yancyribbens the doc you reference links to another doc which says:

> There are two common styles for how people word `expect` messages. Using the message to present information to users encountering a panic (“expect as error message”) or using the message to present information to developers debugging the panic (“expect as precondition”).

This is exactly what I said above. Parse error is intended for the user because it triggered from outside. (And could happen if someone tried to wrap `rustc` in a way that breaks `--version`.)

**Comment by apoelstra** [comment]
I've gotta say, these are pretty poor docs (and they wouldn't even be necessary if the format of the `expect` panic message wasn't stupid).

But thanks for the citation.

I agree we should just "pick something and be consistent", and in my own code I've always taken the "choose a message that would provide a reasonable error message" except for cases where I'm really certain will never trigger, and which I'm only avoiding `unwrap_unchecked` because I don't want to argue about the presence of unsae blocks.

**Comment by tcharding** [comment]
We are discussing the same thing over here https://github.com/rust-bitcoin/hex-conservative/pull/31.

**Comment by yancyribbens** [comment]
Yeah, I'm not a fan of the docs here.  Also, it really takes a high amount of cognition to decide how to format a simple error message which is annoying.  Although, if we are to follow the docs suggestions, I agree that @Kixunil had it right to begin with since in this particular case, it's a parse error that should be presented to the user.  I'll drop this the `expect` commit.

**Comment by Kixunil** [comment]
> it really takes a high amount of cognition to decide how to format a simple error message which is annoying.

I think that the only places where an error might be presented to the user are build scripts and examples, so that should help.

**Review by Kixunil — APPROVED** [review]
ACK 4146ca6a5ef4e17053614a1da8c6856639f3f8f5

**Comment by Kixunil** [comment]
FYI we're getting "dependencies could be updated" warnings. Someone could look into updating Cargo-recent.lock when there's time.

**Comment by apoelstra** [comment]
@Kixunil we know that there are several MSRV breaks in Cargo-recent.lock and that we can't update it to the latest versions. Personally I think we should just drop the warnings.

But sure, I can update it to the most recent versions that work, since we haven't done that in a while.

(For reference, you added these warnings in https://github.com/rust-bitcoin/rust-bitcoin/pull/1764 and @tcharding commented that "we'd probably have to override it somehow in case of MSRV breaks".)

**Comment by tcharding** [comment]
> While you are deleting 46, could you add 53 and 60 which both appear to be used but are not in build.rs?

You've thrown him a curve ball here @apoelstra, there are now some problems with this PR:

- `internals/build.sh` uses all versions used in the workspace (53 and 60 are only used in `bitcoin` not in `internals`)
- `bitcoin/build.sh` only uses those versions used in the crate (53 and 60)

Can we be uniform and either use all versions in both `build.rs` files, or just use the ones needed by the actual crate.

**Comment by Kixunil** [comment]
@apoelstra I don't remember if we decided whether `Cargo-recent.lock` should be MSRV-compliant but I think it shouldn't (or at least we should have one that isn't). We can do MSRV testing with `-minimal`.

@tcharding I don't think we need to check all those versions - just MSRV and stable. The reason is the gates strictly add things so none of them are active in MSEV and all of them are on stable. Unless you're worried that we make off-by-one mistake (we're copying those from the doc/rust releases, so unlikely) or that there will be interactions between the activated features that make some combinations wrong - unlikely in practice IMO. And if you're worried about these things I'd just test (cargo check) on every version in `MSRV..=STABLE`.

**Comment by apoelstra** [comment]
@Kixunil Cargo-recent.toml is supposed to be "the latest version that we've tested and confirm works". If stuff breaks MSRV then it's confirmed *not* to work.

@tcharding yeah, I think being uniform is the best/simplest thing. I'm tempted to dynamically get the list using grep (or maybe to store the list in a flat file that we regenerate in CI using grep?)

**Comment by Kixunil** [comment]
@apoelstra since IIRC my original idea was to make it non-MSRV would it make sense to add a third one?

**Comment by apoelstra** [comment]
Sure, we could add a third one, but I wouldn't be testing it locally because it'd increase my machine workload in order to test dep versions that I don't actually care to test.

I'm not sure what the value would be beyond our existing CI run that just runs `cargo update` and blithely tests whatever versions crates.io gives us on the day of the test.

**Comment by Kixunil** [comment]
Similar to testing with nightly, we would get the chance of reporting any bugs found in other crates early.

**Comment by yancyribbens** [comment]
I dropped the commit to add 53 and 60 to `internals/build.rs`.  Thanks @tcharding for pointing that out, I didn't realize that there was a few of theses build.rs files and that they are workspace specific, but that makes sense.  Nice curve ball @apoelstra :)

**Comment by yancyribbens** [comment]
> I'm tempted to dynamically get the list using grep (or maybe to store the list in a flat file that we regenerate in CI using grep?)

This is a good idea I think.

**Comment by yancyribbens** [comment]
> I'm tempted to dynamically get the list using grep..

The problem is 1) it slows down the build ever so slightly since grep runs each build, and I guess windows and other dev stacks may not have grep installed.  Related to the conversation here https://github.com/rust-bitcoin/rust-bitcoin/pull/2144

**Comment by yancyribbens** [comment]
Why not just loop over all possible versions in each build.rs file greater than the msrv like:

````rust
for version in &[msrv..99] {
    println!("cargo:rustc-cfg=rust_v_1_{}", version);
}
```

There's no consequence afaik for supplying versions that don't exists.  Then we don't need to grep or anything.   Maybe we add something to CI to check for stale flags that are in the codebase less than MSRV.

**Comment by Kixunil** [comment]
@yancyribbens that's what I suggested in https://github.com/rust-bitcoin/rust-bitcoin/pull/2144#discussion_r1374352559
I think we should do it. Note that your 99 is wrong, it has to be the current version.

**Comment by yancyribbens** [comment]
@Kixunil oops, sorry I didn't read the code snippet and instead read just read the part about running grep.  Anyway, good idea :) - yes lets do that.

>  Note that your 99 is wrong, it has to be the current version.

Ah ok, I didn't test trying higher numbers than the current compiler version, although I can see why that would be the case.  That's annoying kind of since that means this needs to be updated every time a new compiler drops I guess.

**Comment by yancyribbens** [comment]
Or maybe we can just auto update this file when a new compiler drops.

**Comment by Kixunil** [comment]
No, the version must be read from rustc stdout. Only MSRV needs to be updated when we change it.

**Not** emitting numbers higher than the current version is the entire point of that build script!

**Comment by yancyribbens** [comment]
> Not emitting numbers higher than the current version is the entire point of that build script!

Ha, good to know.

> No, the version must be read from rustc stdout. Only MSRV needs to be updated when we change it.

Yes, but the file that echos to stdout could be auto built by CI for example.. right?

**Comment by yancyribbens** [comment]
> No, the version must be read from rustc stdout. Only MSRV needs to be updated when we change it.

Ok, I see what you mean now.

**Comment by yancyribbens** [comment]
Closing this PR in favor of: https://github.com/rust-bitcoin/rust-bitcoin/pull/2146

**Comment by Kixunil** [comment]
> Ha, good to know.

It'd be helpful if you invested more time into understanding the purpose of any code before you try to change it. I believe it can minimize noise and confusion. Of course feel free to ask if you can't figure things out.

**Comment by yancyribbens** [comment]
> It'd be helpful if you invested more time into understanding the purpose of any code before you try to change it. I believe it can minimize noise and confusion.

IMO a few high level comments would help in this file, although I know my opinions are not always the same here as others.

> Of course feel free to ask if you can't figure things out.

Now that you say, I was going to ask this on a related PR, but I guess I can ask it here.  Since we can probably pull out the check for the minor numbers https://github.com/rust-bitcoin/rust-bitcoin/pull/2146 here as you commented, could we just remove all parsing and version checking?  For example, why do we care if the major version number starts with 1?

**Comment by Kixunil** [comment]
Maybe a comment that explains the purpose of the code would be better than a comment explaining the steps.

We need to know the minor version and checking major is just a sanity check that we're talking to `rustc`. Exiting early if something is messed up is much better for debugging.

**Comment by yancyribbens** [comment]
> checking major is just a sanity check that we're talking to rustc

I think that's the responsibility of cargo.  I suppose someone could do something silly and set RUSTC env to something else on their system, but that's not something we should care to check imo.

**Comment by Kixunil** [comment]
That check is super cheap though.

**Comment by yancyribbens** [comment]
> That check is super cheap though.

cheap computationally doesn't mean it should be done.  Although it's already setup that way so I wont try to change it :)

**Comment by apoelstra** [comment]
We definitely should be sanity checking that a string is shaped the way we expect before we try extracting data from it.

**Comment by yancyribbens** [comment]
> We definitely should be sanity checking that a string is shaped the way we expect before we try extracting data from it.

I guess my confusion is what makes `2.x.x` an insane version for example.

**Comment by Kixunil** [comment]
> cheap computationally

Not just computationally. It's a single obvious line in the code.

> I guess my confusion is what makes `2.x.x` an insane version for example.

Rust uses semver so 2.x.y literally means incompatible with 1.u.v.

**Comment by yancyribbens** [comment]
nevermind, the fact that we are starting from MSRV minor version means we are being specific about all version 1.u.v greater.

**Pull request closed without merging**
