### PR TITLE
Automated daily update to rustc (to nightly-2024-04-09)

### PR DESCRIPTION
**Pull request by apoelstra**
Automated update to Github CI workflow `rust.yml` by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by apoelstra** [comment]
Hooray!

**Comment by apoelstra** [comment]
Oh, right, I cannot ACK these because I am the "author". Need @tcharding to do it.

**Review by tcharding — APPROVED** [review]
ACK fe928105ae15326875fef93214c73631d92d064a

**Review by tcharding — APPROVED** [review]
ACK 00572ae24b53407f6ade5eabaf9f9687ad996a56

**Pull request merged**
