### PR TITLE
Rename Midstate::into_parts to Midstate::to_parts since it derives Copy

### LINKED ISSUE #3079: Follow up #3010 rename `into_parts` to `to_parts`
ref: https://github.com/rust-bitcoin/rust-bitcoin/pull/3010#discussion_r1681706302

### PR DESCRIPTION
**Pull request by shinghim**
This is a follow up to #3010

Fixes #3079

### CODE REVIEW

**Comment by apoelstra** [comment]
Can you deprecate the old method?

Should backport.

**Comment by shinghim** [comment]
I just browsed the source at the tag of the latest release [bitcoin_hashes-0.14.0](https://github.com/rust-bitcoin/rust-bitcoin/releases/tag/bitcoin_hashes-0.14.0), and at that point, `into_parts` hadn't been introduced so i think we should be good without deprecation

**Comment by apoelstra** [comment]
Ok, perfect. Thanks for checking!

**Comment by tcharding** [comment]
I edited you PR description to throw "this is a follow up to #3010" - that verifies that you are correct and we don't need to deprecate.

Thanks man!

**Review by tcharding — APPROVED** [review]
ACK be94c9e54b38e4ac364001e3b5b7e1501bd65527

**Review by apoelstra — APPROVED** [review]
ACK be94c9e54b38e4ac364001e3b5b7e1501bd65527 successfully ran local tests

**Pull request merged**
