### PR TITLE
Import bitcoin hashes

### PR DESCRIPTION
**Pull request by tcharding**
#1337 was split out of this in an attempt to help review, I think we can merge this one though now it has some traction.

We would like to bring the `bitcoin_hashes` crate into the `rust-bitcoin` repository. https://github.com/rust-bitcoin/rust-bitcoin/issues/550#issuecomment-1248071843
    
Import `bitcoin_hashes` crate into `hashes`. 

Commit hash that was tip of `bitcoin_hashes` at time of import:
    
     commit 2a78c250f78d391599040223870a4d1d6f6f5482

Please note the commit history of `bitcoin_hashes` is only preserved on the soon-to-be-archived `bitcoin_hashes` repository.

### CODE REVIEW

**Comment by tcharding** [comment]
Fuzzing isn't being run on `bitcoin_hashes` ATM, here we enable it and it seems its hitting a crash
```
 Crash: saved as 'hfuzz_workspace/ripemd160/SIGABRT.PC.7ffff7dba00b.STACK.c94ef10c8.CODE.-6.ADDR.0.INSTR.mov____0x108(%rsp),%rax.fuzz'
[2022-09-16T02:43:05+0000][W][5481] arch_checkWait():237 Persistent mode: pid=5483 exited with status: SIGNALED, signal: 6 (Aborted)
Seen a crash. Terminating all fuzzing threads
```

I do not know what to do about that?

**Comment by apoelstra** [comment]
This is pretty frustrating. The fuzztests are basically completely broken in bitcoin_hashes because the dummy hash logic does not round trip.

cc @TheBlueMatt I am going to change the `cfg(fuzzing)` logic to require a different, rust-bitcoin-specific config flag that you will need to enable in rust-lightning.

@tcharding I think we should move all the fuzz targets into crate-specific directories because it's confusing to see them all in a flat directory structure like this.

**Comment by apoelstra** [comment]
@TheBlueMatt oh, this isn't about round-tripping, it's about getting the same result with the `hash` function as you do by running through a hash engine.

**Comment by tcharding** [comment]
Changes in force push:
- Moved `fuzz` -> `bitcoin/fuzz`
- Imported `bitocin_hashes/fuzz` into `hashes/fuzz` - DID NOT ENABLE IN CI

**Comment by tcharding** [comment]
I'd like to squash the last three patches before merge. Will wait for an ack and a green CI run before doing so.

**Review by apoelstra — DISMISSED** [review]
ACK 874db5d05d153546bc5bfb0c5193f497eba83903

**Comment by tcharding** [comment]
Changes in force push:
- Squashed last three commits into one
- Added commit hash from tip of `bitcoin_hashes:master` to the changelog file
- Removed stale `exclude = ["embedded"]` from workspace manifest
- Remove duplicate newline at end of `.gitignore` file

**Review by apoelstra — DISMISSED** [review]
ACK 4b48da0384f2fe1d9d4939d00996cd19aa8990ab

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — DISMISSED** [review]
ACK 096d7a99b6a9844069ec894645fd6ac098fd8a58

**Comment by tcharding** [comment]
Not sure right now what to do about the new changes merged into `bitcoin_hashes` since this PR was first done. I think I'll re-do this PR so its up to date with master branch on `bitcoin_hashes` - I don't really want to be doing this every day though so I'll leave it for a day or two to see if I have a better idea.

**Comment by tcharding** [comment]
I've indicated high priority even though this is a draft, just needs co-ordination between @apoelstra and myself regarding updating this PR and possibly freezing `bitcoin_hashes`. There are three new commits on the `bitcoin_hashes` repo that need adding to this PR before it can be reviewed but the concept is reviewable. Thanks.

**Comment by apoelstra** [comment]
I merged the last bitcoin_hashes PR that you asked me. There are now two open PRs there that we can re-open here (one is by you, the other is Jeremy's `schemars` PR that has no clear path to being merged).

I guess on bitcoin_hashes we should open one last PR (that we won't bring over here) that basically updates the README to say that the repo has been frozen while it's being migrated to rust-bitcoin, and to watch this PR. Then once this is merged we can add another which says that the repo is deprecated in favor of this one.

concept ACK.

**Comment by tcharding** [comment]
I've spilt out #1337 to ease review, this PR is only the actual move of `bitcoin_hashes` now.

**Review by apoelstra — DISMISSED** [review]
ACK dbc7c6dcb63d0c6d7130cd2ac2069e445453b674

**Comment by Kixunil** [comment]
Oh, I just realized: won't this slow down the development by running all tests for every change?

**Comment by tcharding** [comment]
CI is already slow as hell IMO, we should definitely look into some ways to speed it up. I don't think this PR makes it any worse than writing more tests makes it worse, or am I missing something?

**Comment by Kixunil** [comment]
It makes it slow in the same way writing tests that are only relevant sometimes make things slow.

If we're going to have a single repository maybe we should somehow detect which crates changed and only run tests for those and maybe also crates that depend on them (but we would have to use path dependencies and update downstream crates which is probably actually a good thing).

**Comment by tcharding** [comment]
Aight, this seems like a thing to go near the top of my todo list as we progress with crate smashing.

**Comment by tcharding** [comment]
With "improve CI to only run tests for code that effected by this PR" on my todo list does this PR get an ACK from you @Kixunil?

**Comment by tcharding** [comment]
Changes in force push:
- Re-worked the CI script as I had not done it correctly initially, could be improved still but I think it maintains reasonable coverage now. It may be inefficient, of not `DO_FEATURE_MATRIX` does not exist in `bitcoin/contrib/test.sh` so all features are tested all the time - may be a waste of resources.
- Added final patch to fix clippy warnings in `hashes` introduced recently by the new Clippy version.

**Review by sanket1729 — APPROVED** [review]
ACK 9674bf29fe996a1f4c73c8a78193674214f9733c. Did my best to review the CI code, it looks good, and seems like we are testing everything when we add "hashes" to the root level `./contrib/tests.sh`. I would like other reviewers to confirm the same.

**Review by apoelstra — APPROVED** [review]
ACK 9674bf29fe996a1f4c73c8a78193674214f9733c

**Comment by apoelstra** [comment]
@Kixunil could we have an ACK from you?

I'd like to get this merged fairly quickly since it'll require I change my local build scripts (and also we can merge this now without rebasing, unlike several other big open PRs)

**Comment by apoelstra** [comment]
Also, as @tcharding notes in https://github.com/rust-bitcoin/rust-secp256k1/pull/509 we really ought to change the `_` in the name ... this may be an opportunity to do so. But we can do that in a followup PR.

**Comment by Kixunil** [comment]
This a bit big that's why I didn't find the time yet. Will try later today.

**Comment by apoelstra** [comment]
Thank you! The majority of it is a literal copy/paste from the bitcoin_hashes repo which you can recreate and check that way.

**Comment by tcharding** [comment]
There are actually no merge conflicts with `fuzz/fuzz_targets/deserialize_psbt.rs`, not force pushing so as to minimize re-acks. Since we don't use the "merge" button this should be ok to merge without rebase, right? You use `github-merge.py` don't you @apoelstra? I took a quick re-read of it.

**Comment by apoelstra** [comment]
Yep, looks like it -- I'm just running my tests on the merge commit and then we should be good to go!

**Comment by apoelstra** [comment]
```
WARNING: merge differs from github!
Type 'ignore' to continue. ignore

Difference with github ignored.
[pull/1284/local-merge 8da07951e] Merge rust-bitcoin/rust-bitcoin#1284: Import bitcoin hashes
 Date: Fri Nov 18 18:20:26 2022 +0000
rust-bitcoin/rust-bitcoin#1284 Import bitcoin hashes into master
* 9674bf29fe996a1f4c73c8a78193674214f9733c hashes: Fix clippy warnings (Tobin C. Harding) (pr/1284/head, pull/1284/head)
* b9643bf3e9b21e4e2207ea210d1d57ffa014d271 Import bitcoin_hashes crate into hashes (Tobin C. Harding)
* 580feab3f9d8fac1a7dc315f3a7dc371bbb9a8d5 internals: Add CHANGELOG file (Tobin C. Harding)
* bae64e156ee21d7dd2fae12b77674d330419ed0d Move CHANGELOG to bitcoin crate (Tobin C. Harding)
* 9a2c856be6c90d14ab79cfa6f864e6eb75549f1a Update gitignore file (Tobin C. Harding)
ACKs:
* ACK 9674bf29fe996a1f4c73c8a78193674214f9733c. Did my best to review the CI code, it looks good, and seems like we are testing everything when we add "hashes" to the root level `./contrib/tests.sh`. I would like other reviewers to confirm the same.  (sanket1729)
* ACK 9674bf29fe996a1f4c73c8a78193674214f9733c (apoelstra)
Type 's' to sign off on the above merge, or 'x' to reject and exit. s
```
Neat.

**Comment by tcharding** [comment]
Win!

**Pull request merged**
