### PR TITLE
Automated weekly update to rustc stable (to 1.80.1)

### PR DESCRIPTION
**Pull request by apoelstra**
Automated update to Github CI workflow `semver-checks.yml` by [create-pull-request](https://github.com/peter-evans/create-pull-request) GitHub action

### CODE REVIEW

**Comment by Kixunil** [comment]
It works!

**Review by Kixunil — DISMISSED** [review]
ACK 06f604d9badf587bec51e35f2a324fb4c7e257e5

**Review by tcharding — APPROVED** [review]
ACK 06f604d9badf587bec51e35f2a324fb4c7e257e5

**Comment by storopoli** [comment]
> It works!

Yes! Noice!

**Review by tcharding — APPROVED** [review]
ACK 78f091fb3f2b78e8a4de2729ae4b5b7eb97ff39c

**Pull request merged**
