### PR TITLE
Add an example for bip32 key derivation

### PR DESCRIPTION
**Pull request by rikitau**
Dear 🦀-bitcoin people, I started using rust-bitcoin crate for my thesis and it is wonderful! Thank you for your amazing work!

For some people like myself it might be difficult to start using the crate without hello-world examples.
So I got up the courage to offer an example on the bip32 functionality.

Excuse me if the quality of my code does not meet the standards. I will be happy to improve it if you give me a code review.

### CODE REVIEW

**Comment by apoelstra** [comment]
This looks great!

I'm a little surprised that you had to do so much parsing of the seed -- it looks like this is a standard WIF-encoded privkey? Could you have used bitcoin::PrivateKey::from_str to do the parsing?

**Comment by rikitau** [comment]
Thank you! I updated the example using `::from_wif` for parsing.

**Comment by rikitau** [comment]
Continuous integration fails, last time it was ok...
CI details say it's because of `bitcoin_hashes` and `serde_macros`.
I assume it's not my fault because I didn't touch anything except my example... 
What should I do now?

**Comment by apoelstra** [comment]
I'm sorry, it's my fault -- I broke the build in the last update of bitcoin_hashes. I'll try to have a fix published this weekend then I'll restart the CI here. Nothing you need to do.

**Review by apoelstra — APPROVED** [review]
Looks great, thanks!

**Review by stevenroose — APPROVED** [review]
Looks good!

**Pull request merged**
