### PR TITLE
Add .rustfmt.toml and .editorconfig and format all files

### PR DESCRIPTION
**Pull request by stevenroose**
Fixes https://github.com/rust-bitcoin/rust-bitcoin/issues/172.

### CODE REVIEW

**Comment by apoelstra** [comment]
1. You need to add `rustup component install cargo-fmt` or something before `cargo fmt` in the test script.
2. I'd like to hold off on merging this til the other pending big PRs get in, because it's easier to rebase this than to rebase non-mechanical code changes.

**Comment by tamasblummer** [comment]
NACK Is there a real issue with format? Otherwise it is bikeshedding with potential to waste lots of time submitting PRs.

**Comment by stevenroose** [comment]
I'm not super hard on making this a merge requirement. I'd be ok with just having the config files in the repo as a "suggested style guide" so that reformats in PRs are accepted. That would allow rustfmt users to use it on the files they are working on.

But personally I think the step towards enforcing it is not that big. "waste lots of time" is quite exaggerated. Everyone has cargo installed, so it takes a second to do a cargo fmt before push. If you forget, it'll be noticed and it'll just be part of the code review process.

In your BIP158 PR, I also requested some format changes. With the .rustfmt files committed, I could just have commented "please do cargo fmt" and you'd have been fine.

Anyway no strong opinion on making this a requirement, but I'd like to have the files committed.

**Comment by tamasblummer** [comment]
If no strong opinion then why doing it? I think a programmer formats such that it helps understanding the code. Re-formatting manual or automatic should be requested only if that is not the case.

**Comment by stevenroose** [comment]
> If no strong opinion then why doing it?

Because I do have an opinion, just not strong enough that I want to try get this through if most other contributors don't want it.

I use rustfmt on the files I'm working on all the time. I don't want to waste time formatting code manually, so whenever I make structural or indentation changes or paste code inline, I just rustfmt to fix the format. When the file is not formatted before you start, you start introducing all kinds of changes unrelated to the code you changed, which is annoying for (1) having an overview of your actual changes, (2) spreading changes across commits and most importantly (3) review.

Sadly code formatters aren't smart enough yet to only format the code that you changed. (In fact let me make a feature request for that in rustfmt.)

**Comment by stevenroose** [comment]
I rebased and updated. Could we perhaps reconsider this?

**Comment by tamasblummer** [comment]
repeat NACK. This addresses an issue which is not there, but fucks up the history of most files introduces a potential new hurdle to pass with PRs. Go for problems that are some and are not solved instead.

**Comment by jb55** [comment]
Concept ACK

**Comment by thomaseizinger** [comment]
> repeat NACK. This addresses an issue which is not there, but fucks up the history of most files introduces a potential new hurdle to pass with PRs. Go for problems that are some and are not solved instead.

How exactly is language like this adding value to the discussion? If you disagree with the benefits of automatically formatting code, then we should discuss it on a factual basis, like the time saved during development (by not having to format code manually) and during code review (by eliminating discussions around code style/formatting).

**Comment by tamasblummer** [comment]
@jb55 about 2 years ago I tried to contribute to lnd and could not get my PR past the automated gofmt as there was some disagreement between the gofmt I used and the one executed by the commit trigger. I gave up after a week. The story has a happy end because it pushed me to join this project instead. 

Last week I asked Andrew to cut a release. He made a change upgrading the version number and the README.md. For two days and numerous attempts the build, which was not even necessary since there were no code changes, did not go through. At some point Andrew agreed to override the checks, so we could release. This experience also makes me also wary of adding further commit hooks.

@thomaseizinger You are right, this comment of mine was not as considerate as others I gave in #335 and here on the same topic. In short again:
1. where is the code that desperately needs this?
2. Those who actually commit often in this repo seem to be quite close and adaptive in our style.
3. code is handwriting and if done right can carry information lost in automated reformatting
4. the change is disruptive to history
5. commit hooks suck

If @stevenroose and two other approver think this is an issue that needs to be addressed, then let it be.

**Comment by thomaseizinger** [comment]
> could not get my PR past the automated gofmt as there was some disagreement between the gofmt I used and the one executed by the commit trigger.

That is definitely not how it should be. Automated checks, if put in place, definitely have to be reliable, useful and a "no-brainer"! (A possible solution for this particular problem is the `rust-toolchain` file, which guarantees that everyone is working with the same toolchain for a particular project. Same toolchain = same rustfmt version)

> In short again:
> 1. where is the code that desperately needs this?
> 2. Those who actually commit often in this repo seem to be quite close and adaptive in our style.
> 3. code is handwriting and if done right can carry information lost in automated reformatting
> 4. the change is disruptive to history
> 5. commit hooks suck

Thanks for writing down those points. (3) can definitely be an issue. You can always opt-out of rustfmt for certain parts of the codebase. Depending on how often that would be the case, it may not be worth activating it in the first place.

**Comment by stevenroose** [comment]
Personally, I tend to be way more productive writing code when I don't have to think about formatting. I can copy paste sections of code into strange places and let the formatter take care of the new layout. Think moving if-blocks into match variants etc.

Of course there are some uncommon cases where the formatter makes a choice that I don't like, but in general I think the benefit of not having to think about formatting outweighs those rare cases.

rust-bitcoin is one of the few Rust codebases where formatting is not applied to all files. So this means that often when I work on a file that is not a new file, I use rustfmt and then in the end I have to `git add --patch` to make sure I don't commit formatting changes to sections I didn't work on.

**Comment by tamasblummer** [comment]
@stevenroose that sounds like a reasonable way of using that tool. I am also not doing all formatting manually but write Rust code with IntelliJ IDEA that e.g. positions brackets places the cursor to the right ident while I type. It also adapts to the format the the file already has in the sense of space/tabs and does only suggest format where I type.

**Comment by apoelstra** [comment]
A few thoughts

* I really don't think we should have a `rust-toolchain` file. This causes all manner of surprising behavior (mostly, the library will compile with a different compiler depending on whether you're building it directly or as a dep, resulting in different warning sets or even different behavior).
* One idea is to enable `cargo fmt` in CI and add `#[cfg_attr(feature="cargo-fmt", rustfmt_skip)]` on every single module, and have separate PRs that enable specific low-turnover modules as they are modified. (And new modules would have rustfmt on to start.) This will minimize disruption and avoid any giant "touch every LOC and break `git blame` commits.
* Regarding CI hooks causing friction, we've had many cases, like the recent situation with 0.21.0, where Travis simply run. This has nothing to do with what hooks we enable or disable, typically we get the "!" icon and Travis has done literally nothing. So I'm not too worried that a rustfmt pass would make the Travis situation any worse.
* Similarly, there is only one version of rustfmt now and it rarely changes. I don't think we'll have a lot of trouble running it on the "stable" CI run, like in Tamas' example.

I also encourage everyone to remain calm and civil. This is a very conservative project with very cautious maintainers. We are not going to merge anything that certain major contributors strongly oppose, and we are not going to merge anything at all (of this magnitude) without a long period of discussion.

**Pull request closed without merging**
