### PR TITLE
refactor: use amount type

### PR DESCRIPTION
**Pull request by yancyribbens**
Separate out refactor commit from https://github.com/rust-bitcoin/rust-bitcoin/pull/3794.  Can be merged independently.

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK da3ba6aade5f305778a4275761f3a4b632f25fe1; successfully ran local tests; yeah, this looks good

**Review by sanket1729 — APPROVED** [review]
utACK da3ba6aade5f305778a4275761f3a4b632f25fe1

**Comment by apoelstra** [comment]
Will wait on @tcharding to ack since he is in the middle of working on these modules.

**Comment by tcharding** [comment]
I am not willing to put my ACK on any PRs from @yancyribbens with single line commit logs. Explained here: https://github.com/rust-bitcoin/rust-bitcoin/pull/3769#issuecomment-2558603414

**Comment by tcharding** [comment]
This diff is unreviewable on its own with no commit log because from the diff one has no idea what the implementation of `checked_add` and `checked_sub` are for `Amount` and if it matches the `u64`.

**Comment by yancyribbens** [comment]
@tcharding, I updated the commit message.  I agree, it was a pretty half-ass commit message to begin with.  It's a trivial change but that's no reason to be lazy about the commit message.

**Review by tcharding — APPROVED** [review]
ACK 774f066879c8ad1af81c7e46b404fa63682a0b4c

**Review by apoelstra — APPROVED** [review]
ACK 774f066879c8ad1af81c7e46b404fa63682a0b4c; successfully ran local tests

**Pull request merged**
