### PR TITLE
Derive Eq for PSBT types

### LINKED ISSUE #931: PSBT lacking Eq implementation
`PartiallySignedTransaction`, `psbt::Output` and `psbt::Input` all lacking `Eq` implementation (but have `PartialEq`). Was this intentional?

If not, I see two ways forward with the implementation: adding derive or manual implementation doing BIP-174 serialization to a vector and byte-comparing those vectors.

### PR DESCRIPTION
**Pull request by dr-orlovsky**
Closes #931

### CODE REVIEW

**Review by apoelstra — APPROVED** [review]
ACK 603e75eb77555b0c8e07c38bffece813b9563ff8

**Review by sanket1729 — APPROVED** [review]
utACK 603e75eb77555b0c8e07c38bffece813b9563ff8.

**Comment by sanket1729** [comment]
Any reason why this is 0.29.0? We can get it in, it has 2 ACKs and is a short PR.

**Comment by dr-orlovsky** [comment]
@sanket1729 because I was afraid of making you guys angree at me LOL :D Let's merge it!

**Comment by sanket1729** [comment]
This is a simple/easy to review and useful change. I don't operate on some hard rules for what's allowed and what's not in RC, mostly subjective based on 

- Ease of review
- Whether it is a bug
- Necessity of feature
- Timeline near release.

**Pull request merged**
