### PR TITLE
Upgrade `bitcoin_hashes` dependency

### PR DESCRIPTION
**Pull request by tcharding**
We just released a new version of `bitcoin_hashes`, upgrade the dependency to v0.11.0

### CODE REVIEW

**Review by apoelstra — DISMISSED** [review]
ACK ca766f14d3158f6faee7a8d8a0d45b00bdfa64d4

**Comment by tcharding** [comment]
Changes in force-push:
- Pulled the first patch out into a separate PR: #1094 because it is trivial and unrelated to this.
- Rebased on master

No other changes.

**Review by apoelstra — APPROVED** [review]
ACK ede6f8785e4ea97ffb048ae63614a798fd5861f7

**Review by Kixunil — DISMISSED** [review]
ACK ede6f8785e4ea97ffb048ae63614a798fd5861f7

**Comment by tcharding** [comment]
Rebase only, no other changes.

**Review by apoelstra — APPROVED** [review]
ACK 1e46eeaa88aa5fc2c0d3dd163043a724f7af7ac9

**Review by Kixunil — APPROVED** [review]
ACK 1e46eeaa88aa5fc2c0d3dd163043a724f7af7ac9

**Pull request merged**
