### PR TITLE
Minor refactoring

### PR DESCRIPTION
**Pull request by LeL94**
Uniformed the code with 1 line spacing.

### CODE REVIEW

**Comment by LeL94** [comment]
I am new to open source contributions and I thought of starting with some trivial task, hope that is ok.

**Comment by sgeisler** [comment]
Hi, we generally avoid pure formatting PRs as they just make it harder to read the commit history. There is also no standard for formatting in place right now, so every new PR could break it again, making it pointless. If we ever enforce a formatting standard it will most likely be through `rustfmt`, see #290 and #172 for reference. But for now it has been regarded as too invasive.

**Comment by LeL94** [comment]
@sgeisler I see, thanks for your feedback.

**Comment by sanket1729** [comment]
I think we should welcome small changes(file by file) that enforce `rustfmt`. 
See: https://github.com/rust-bitcoin/rust-bitcoin/issues/172#issuecomment-756312998

**Comment by sgeisler** [comment]
Only if it's enforced by CI first, otherwise it's an entirely pointless exercise. There is no official agreement so far afaik, neither on if it should happen nor on how. But I'd be happy to push this forward in #172.

**Pull request closed without merging**
