### PR TITLE
Add mutation testing to the `locktime` module

### PR DESCRIPTION
**Pull request by tcharding**
Add mutation testing to the `locktime` module and add unit tests to cover all mutants and ensure they are killed.

### CODE REVIEW

**Review by sanket1729 — APPROVED** [review]
ACK ca471557a55a42eec92ecf1e75b8e5f178de2192. How stable are the mutation tests?

Does it also change constants like 512 or 500_000? Would be really cool if can detect boundary conditions.

**Comment by sanket1729** [comment]
I am not really sure about the inlining part, but I guess it does not hurt. I just don't want to see inline above 90% of the functions that we have, but that maybe the correct way to do things

**Comment by apoelstra** [comment]
I have no opinion (and never have had an opinion) about the `#[inline]` markers.

But I can't figure out how to test this .. whenever I run mutagen I get "29 mutants, 0 killed" all from pow.rs, and I don't see any indication that it's using the locktime mutants at all.

**Comment by apoelstra** [comment]
Never mind, I forgot to set my `RUSTFLAGS`.

**Review by apoelstra — APPROVED** [review]
ACK ca471557a55a42eec92ecf1e75b8e5f178de2192

**Comment by tcharding** [comment]
> I just don't want to see inline above 90% of the functions that we have, but that maybe the correct way to do things

I was under the impression that any small function should be inlined. I don't have a strong argument for it though, perhaps others do?

**Comment by Kixunil** [comment]
The trade-off is between compilation speed and speed of resulting binary. I think inlining trivial functions which only delegate to something else is totally fine. The others are less obvious. `std` inlines almost eveything for instance. Note that for people compiling with LTO this doesn't matter.

I'm personally leaning towards inline.

**Pull request merged**
