### PR TITLE
Remove double spacing in rustdocs

### LINKED ISSUE #3761: Remove all instances of double spacing in rustdocs
Change all double spacing after a `.` to a single space in rustdocs.

### PR DESCRIPTION
**Pull request by jamillambert**
Fixes #3761

### CODE REVIEW

**Review by tcharding — DISMISSED** [review]
ACK f4f13bf62ab5f9e8c6400a2c6c87241b0d179957

**Review by apoelstra — APPROVED** [review]
ACK f4f13bf62ab5f9e8c6400a2c6c87241b0d179957; successfully ran local tests

**Comment by apoelstra** [comment]
Needs rebase.

**Comment by tcharding** [comment]
Might want to wait till the api files thing is sorted @jamillambert to save your self having to rebase this multiple times.

**Review by tcharding — APPROVED** [review]
ACK bb294903086e2e317c9a7a6f298a36ec17082c39

**Pull request merged**
