### PR TITLE
Remove Address::p2pk

### PR DESCRIPTION
**Pull request by stevenroose**
There is no address format for p2pk.

Script Descriptors should probably be used to construct scriptPubkeys and scriptSigs for using them instead of the `Address` type.

### CODE REVIEW

**Comment by tamasblummer** [comment]
Pay to public key is used in Bitcoin blockchain, with most of satoshi's coins. Why should it be removed?

**Comment by stevenroose** [comment]
@tamasblummer Because it's not an address. It's just a script. Script descriptors make it possible to construct scriptPubKeys for them, so we don't need to have them awkwardly put in the `Address` type.

**Comment by tamasblummer** [comment]
This script is usually interpreted by explorer as sending to an address. I do not see value in a PR removing an interpretation that is common.

**Comment by stevenroose** [comment]
Yeah, that's a wrong interpretation of that script. And more modern explorers will also [not show it as such](https://blockstream.info/tx/f4184fc596403b9d638783cf57adfe4c75c605f6356fbc91338530e9831e9e16#expand).

I agree that it's unfortunate to remove features from a codebase. But it's in the wrong place and script descriptors can cover the lost functionality.

**Comment by dongcarl** [comment]
Hmmm I remember @apoelstra had some thoughts on this.

**Comment by apoelstra** [comment]
Yeah, fine by me. If the ambiguous interpretation is not even universally used I'd rather drop it because it's confusing and could lead to lost coins.

**Comment by dongcarl** [comment]
Sounds good. @stevenroose please rebase!

**Comment by stevenroose** [comment]
@dongcarl done.

**Pull request merged**
